### ISSUE TITLE
Time-dependent speed limits

### ISSUE THREAD

**Issue by 9662** [westnordost/StreetComplete#581] opened 2017-09-03 10:26 UTC
As a user adding speed limits to the map, I need to have an option to enter a [time-dependent speed limit](http://wiki.openstreetmap.org/wiki/Conditional_restrictions), in order that I can enter accurate information in OSM.

**Comment by rugk** [comment] 2017-09-03 11:25
Duplicate of https://github.com/westnordost/StreetComplete/issues/449

**Closed** 2017-09-03 17:14 UTC
