### ISSUE TITLE
Support specific object IDs (was "Support street light and garbage bin numbers")

### ISSUE THREAD

**Issue by PanderMusubi** [westnordost/StreetComplete#81] opened 2017-04-02 11:39 UTC
Support street light numbers and garbage bin numbers, that is their ID that can be found on them. Usually, local government put a visible sticker on these objects. Same goes for traffic lights, recycle bins, major road signs, etc.

**Comment by PanderMusubi** [comment] 2017-04-02 12:34
Bus stops, post/letter box (to send letters), electrical switch boxes, fire hydrants

**Comment by lightonflux** [comment] 2017-04-03 04:05
One category of tag is already enough to talk about. You already named more than 5 different items in this issue.

The problem is that you can't make a generic quest "ID of object" because different objects have different types of IDs that are not easily distinguishable for many people.

I made two issues that go more into detail for mail boxes (#85 ) and lit streets ( #84 ).

**Comment by PanderMusubi** [comment] 2017-04-03 09:02
Thanks for the split-off. I have tried to improve both issues. As for street_lamp ID, recycle bing ID and road sign ID, there is indeed the question on how to do this. I have seen simple IDs but also major/minor such as "2.95" or "7689473(newline)34" and bar codes. Would it be okay to use this issue to discuss ID of object capturing in general and split-off specific issues?

**Comment by lightonflux** [comment] 2017-04-03 19:33
Sure. Just change the title of this issue so it reflects the type of discussion.

**Comment by westnordost** [comment] 2017-04-28 18:35
What I need for this is a list of countries where street lamps usually _have_ clearly identifiable numbers. Also, I just went out to check: In Hamburg (DE) at least, I see four different numbers on the lamp post and I have no idea what they stand for and which I would have to input if I were asked.
The ref tag for street lamps (etc.) needs much more in depth (per country) documentation until this quest becomes anywhere near realizable. This research and documentation can be done in the wiki.

**Comment by PanderMusubi** [comment] 2017-04-28 18:49
Netherlands (in mainland Europe) has clearly identifiable numbers too.

**Comment by ninjamask** [comment] 2017-07-27 06:13
In germany and austria streetlights can be `lit=limited` for lights that are not lit the whole night. They may but don't have to show a time at which they go off.

https://de.wikipedia.org/wiki/Laternenring

**Comment by HolgerJeromin** [comment] 2017-07-27 06:36
Is there a real use case for this information?

**Comment by PanderMusubi** [comment] 2017-07-27 07:26
Yes, to help in reporting issues with these objects to their respective operator. For example, contacting local government that a lamp post is broken or a garbage bin has been destroyed by vandals. On might know which object it concerns. When filing the report at home, one can look up the ID of the particular object on OSM. Another use case is to use an ID of a lamp post on a really really long road to find out your exact location in case you do not have access to GPS.

**Comment by fgouget** [comment] 2018-02-17 21:11
I'm very interested in getting this for the French post boxes.

In France each post box has a unique id which which takes the form of 3 letter+number pairs. This id is shown on the post box, for instance A4H8Y3 in [this picture](https://commons.wikimedia.org/wiki/File:Savign%C3%A9_86_Bo%C3%AEte_aux_lettres_2012.jpg). The id is further stored in the ref field of the amenity=post_box node in OpenStreetMap.

The government (well, La Poste really) publishes a list of all post boxes with their id and their sometimes very imprecise location as open-data. So having the ref field being set is critical in assessing whether OpenStreetMap is missing post boxes or not, and to detect post boxes that have been removed, replaced, etc. Also, should the government one day see fit to publish the collection times, the ref field will be needed in order to match that data with the OpenStreetMap objects. The id would also make it possible to provide corrected coordinates for this open-data file.

So a quest that let users easily fill in the post_box ref field would really be great. In fact if the solution is specific to French post boxes that's quite fine by me ;-)

**Comment by ENT8R** [comment] 2018-02-17 21:23
But what kind of value should be set if the object (speaking not only of post boxes in French) has no ID/ref value at all?
Is it valid to set ref=no?

**Comment by fgouget** [comment] 2018-02-17 22:54
All French post boxes have an id. There are some cases where it's not (easily) readable like if someone puts an advertisement sticker or a graffiti on top of it. So for post_boxes ref=no would not be valid.

I don't know about other object types, even less so for those abroad. That's why it may make more sense to not try to handle everything at once.

**Comment by westnordost** [comment] 2019-11-06 22:26
I am going to close this one as the only thing mentioned here where it probably makes sense to collect the ref is the post box, for which there is #1556 now.

**Closed by westnordost** 2019-11-06 22:26 UTC
Labels: blocked, feedback required, new quest

**Comment by MegaArthur** [comment] 2019-11-07 06:12
Except postboxes, it could also make sense to collect bus stop refs

**Comment by westnordost** [comment] 2019-11-07 09:03
Already the name is recorded, that's already enough to identify it

**Comment by ferdinand0101** [comment] 2019-11-07 15:19
I'd disagree
For public transport routing it can be very useful to know which ref your bus platform has especially for bigger bus stops
As you can usually see signs at the station pointing to specific platform numbers

**Comment by westnordost** [comment] 2019-11-07 15:52
But platform number is not the same as ref

**Comment by HolgerJeromin** [comment] 2019-11-07 18:50
I think he meant something like `local_ref` rendered on transport map:

https://www.openstreetmap.org/node/365204823#map=19/50.77546/6.09584&layers=T

**Comment by PanderMusubi** [comment] 2019-11-08 04:24
The initial request to collect IDs from "street furniture" still exists for reporting damages to responsible parties such as local government. Perhaps later a new issue for this is more appropriate as the priority is not that high.

**Comment by goldfndr** [comment] 2019-11-09 22:21
> Already the name is recorded, that's already enough to identify it

For what it's worth, [around here](https://www.openstreetmap.org/#map=18/47.61691/-122.11736&layers=T), the same name is used for the bus stops on both sides of the street. [The Transport Map layer](https://wiki.openstreetmap.org/wiki/Transport_Map) uses somewhat of an oval when this occurs. The ref uniquely identifies the stop.

(Obviously, for a damage investigation, it would probably be relatively trivial to check both bus stops after arriving for one. But for [a timetable/schedule](https://github.com/OneBusAway), the ref is more useful.)

**Comment by Lee-Carre** [comment] 2021-11-06 22:19
Street lamps have IDs in Jersey.
