### ISSUE TITLE
No POIs for "bicycle parking covered" or "type of bicycle parking" quest filters

### ISSUE THREAD

**Issue by rouelibre1** [westnordost/StreetComplete#2185] opened 2020-10-21 14:31 UTC
No POIs are shown for "What type of bicycle parking is this ?" or "Is this bicycle parking covered (protected from the rain) ?" quest selection.

But when I select "How many bicycles can be parked here ?" there are POIs that are missing the "capacity" tag in OSM, and some of them are also missing the "bicycle_parking" (type) and "covered" tags as well, which leads me to believe there is some issue preventing these from appearing in the 2 other filters in quest selection.

**How to Reproduce**
Select one of these 3 filters (excluding all other kind of quests) and go back to the map to witness the presence/absence of POIs for quest.

**Versions affected**
v24.2 / Android 8.0.0 / Device SM-A520F

**Comment by matkoniecz** [comment] 2020-10-21 15:30
Note that StreetComplete is not downloading all quests at once (for technical reasons, see #1901 for active work by @westnordost  to overcome that limitation).

Also, more important nearby quests may hide lower priority ones.

Can you go into settings, drag this bicycle quests to top and select "scan for nearby quests"? They should appear after doing this.

If this will not help - can you link specific missing bicycle parking without quest? Maybe it is marked as a private and unusuable by a general public?

**Comment by rouelibre1** [comment] 2020-10-21 18:31
You are right, dragging these quests to top and selecting "scan for nearby quests" made them appear on the map.

So it's not a bug.

From a UX perspective for a new user like me, a few details were not quite clear

1. The need to scan for nearby quests to refresh the map, despite the fact that I witnessed the scan happening when I launched the app for the first time, and how to perform this refresh action. The design of the button and the fact that it's nested/hidden in the burger menu confused me.

2. The fact that rearranging quests in the menu would impact their priority level. I now realize it's written at the top of the list, so it's a good example of a frequent user behavior to not read texts and then get confused.

3. While rearranging quests order, I ran into #893 and it added a little bit of confusion, I really thought the order of elements was for pure convenience in the menu and didn't notice there was such a thing as quest priority.

4. It is not possible to perform multiple actions in a row on one POI (ex. fill in both the "bicycle_parking" and "capacity" attribute). I understand from the "Atomic quests" rule (from the General guidelines for adding new quests) that it is by design in the app. I would love to have quests showing all POIs of a specific type (ex. "amenity=bicycle_parking") that are missing at least one of several attributes (ex. "bicycle_parking", "capacity", "covered"...), and to be able to answer a series of questions about it while in front of the POI. I'd be happy to open a new issue to discuss this.

**Comment by matkoniecz** [comment] 2020-10-21 18:47
ad1) see #1901 for an active work
ad2) not sure what can be done on StreetComplete side here
ad3) yeah, #893 is irritating but is stuck on "someone should debug it and implement a fix"
ad4) see #124 - or more specifically https://github.com/westnordost/StreetComplete/issues/124#issuecomment-294488942 (so it waits for someone to make a pull request)

**Comment by matkoniecz** [comment] 2020-10-21 18:50
> You are right, dragging these quests to top and selecting "scan for nearby quests" made them appear on the map.

And thanks for reporting back! I suspected this, but glad to have confirmation that there is no some new obnoxious bug lurking

**Comment by rouelibre1** [comment] 2020-10-21 23:36
Thank you for answering so quickly !

1. This is good news, and should definitely help with the general UX, and help serve some specific (existing and future) use cases.

2. There is nothing technical about this. Some thoughts :
- Maybe tweak the design a little to make it obvious to the user that elements can be dragged and dropped
- Introduce a visual hierarchy or numbered list style in the list of quests
- Change the style/design of the hint text message to make it stand out more

3. I would love to help, but unfortunately I am not a developer myself

4. I see similar behaviors have been asked for by different people to match more or less the same use case. And also that @westnordost warned that there is complexity behind it. I do hope that someday we'll see some kind of combined quests with series of questions about a single POI implemented in the app :)

**Comment by rouelibre1** [comment] 2020-10-22 01:26
Now that I've read a little more through previous issues, I believe there may be an alternative solution for number 4. 

How feasible would it be to merge some quests together ? My use case is about the bicycle parking type and capacity done together here, excluding in this example the covered=yes/no attribute because of the limitations explained here https://github.com/westnordost/StreetComplete/pull/315#pullrequestreview-43463769

Which would require some improvements, in order to include in the quest the nodes that are missing bicycle parking type OR capacity (not AND). Also the UI would be different based on what tag is actually missing (3 different cases). 

I believe this would have to be adapted from this form : 

> https://github.com/westnordost/StreetComplete/issues/1330#issuecomment-701650292 
 
>I created this multi-choice form for the blind-traffic-signals mainly because these are really two features on one thing (arrow and button).
> https://github.com/westnordost/StreetComplete/issues/2127#issuecomment-702671246

**Comment by westnordost** [comment] 2020-10-22 11:14
That properties are asked one at a time is by design. I shortly implemented something similar to what you cite here but for various reasons reverted to the old yes/no scheme.

Once the quest download is adapted so that all quests are downloaded at the same time, it will be no problem anymore that some quest types are missing.

**Closed by westnordost** 2020-10-22 11:14 UTC
Labels: question
