### ISSUE TITLE
amenity=recycling without recycling:*=yes tag

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#223] opened 2017-05-12 06:52 UTC
`amenity=recycling` without a knowledge which waste i can dump is not useful.

[Wiki](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Drecycling) has a list. [Taginfo](https://taginfo.openstreetmap.org/tags/recycling_type=container#combinations) has a list of most used values:

recycling:glass=* (but some should be glass_bottles)
recycling:paper=*
recycling:clothes=*
recycling:glass_bottles=*
recycling:cans=*
recycling:plastic=*

related to #222 (this here could be asked after adding the type)

**Comment by PanierAvide** [comment] 2017-05-15 06:17
This quest can probably use the same system as #180 with a multi image selector. The tricky thing will be to retrieve features without any `recycling:*` tag, as Overpass doesn't allow to combine a regex over key and negation on value.

**Comment by westnordost** [comment] 2017-05-15 08:16
Ah, I love these implementation synergies!

The query could retrieve all ♻ and then filter it out in Java code. This is possible since 0.9, see the housenumber quest.

Am 15. Mai 2017 08:17:35 MESZ schrieb Adrien Pavie <notifications@github.com>:
>This quest can probably use the same system as #180 with a multi image
>selector. The tricky thing will be to retrieve features without any
>`recycling:*` tag, as Overpass doesn't allow to combine a regex over
>key and negation on value.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/223#issuecomment-301385706

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by westnordost** [comment] 2017-05-15 08:26
Though, getting/creating all those icons will be the most work.

Am 15. Mai 2017 08:17:35 MESZ schrieb Adrien Pavie <notifications@github.com>:
>This quest can probably use the same system as #180 with a multi image
>selector. The tricky thing will be to retrieve features without any
>`recycling:*` tag, as Overpass doesn't allow to combine a regex over
>key and negation on value.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/223#issuecomment-301385706

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment] 2017-05-15 13:00
> The tricky thing will be to retrieve features without any recycling:* tag

Maybe just check documented ones? For extreme safety, include test that will check taginfo whatever new popular tag appeared that is not handled by this program.

**Comment by PanierAvide** [comment] 2017-06-12 14:49
As a first step, some icons extracted from Twemoji / Emojione sets + custom icons for cans and plastic bottles ([SVG file](https://github.com/westnordost/StreetComplete/files/1068549/recycling.svg.txt)).
![Recycling](https://user-images.githubusercontent.com/1349014/27039641-c28b0ebe-4f8e-11e7-8c77-740bd07e631d.png)

**Comment by westnordost** [comment] 2017-06-16 23:43
Some of these already look quite cool, I.e. the newspaper is really good.

**Comment by ServusWorld** [comment] 2017-08-28 15:02
I think this is a important quest, maybe even more important than the "Recycling type" quest (If I want to get rid of my wastepaper, I have to know where it is accepted, it's rather not important whether it's a container, underground container or recycling centre).

As an icon for this quest, how about that one:
![icon_sortofwaste](https://user-images.githubusercontent.com/31391499/29779334-8c0c8b54-8c12-11e7-9670-15d4cc030243.png)

**Comment by westnordost** [comment] 2017-08-28 15:32
I usually draw the icons myself. I would say, in this case, I'd either show a typical round glassbottle container, simply a glass bottle or a mashup of a glass bottle, paper and a can.

Note that all elements in the icon should still be easily distinguishable when the icon is displayed in a resolution of 24x24px (on a normal computer screen). The ♻ logo on the garbage bin would be so small that it is barely recognizable.
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by westnordost** [comment] 2019-01-27 17:59
Drew some icons. One that is still missing is the one for "plastic packaging" (that is not plastic bottles).

https://github.com/westnordost/StreetComplete/blob/master/res/recycling_icons.svg

**Comment by goldfndr** [comment] 2019-01-29 19:39
[recycling:newspaper is also somewhat common](https://taginfo.openstreetmap.org/keys/recycling%3Anewspaper), can the paper icon be different in case this key is added later? (I definitely know of one that accepts newspaper and cardboard but not other types of paper.)

How would the can look if it was lighter on the tops of the two rims? (When I first looked at it, I thought it looked inward sloped, I used a straight edge to determine that I was seeing an illusion.)

**Comment by westnordost** [comment] 2019-01-29 20:41
What kind of container accepts newspaper but not other paper?

**Comment by goldfndr** [comment] 2019-03-15 18:07
[Overpass Turbo shows hundreds.](http://overpass-turbo.eu/s/H1X) [There's one I know of personally](https://www.openstreetmap.org/node/2502632007); it's in a rural town.

**Comment by westnordost** [comment] 2019-09-08 19:55
https://github.com/westnordost/StreetComplete/blob/master/res/recycling_icons.svg

Felt like drawing some more today. I am now content with all the icons except electrical appliances:
- paper icon makes clear that all paper (inclusive: carton) is meant
- plastic icon makes clear that bottles, other plastic packaging and other platic (toys) is meant
- cans icon contains a bit more variation than before
- bottles icon shows another glass so it is clear that the color does not matter
- added rotten apple to the green waste icon to add some variation
- removed too thin lines from clothes and shoes icon
- added some gloss to the battery icon

For the electrical appliances, I think I will make an icon of a hair dryer + old phone + light bulb or something to show what it roughly covers. Maybe I should add a scrap-icon (screw + spring?) as well.

**Comment by matkoniecz** [comment] 2019-09-18 21:03
So now I will probably finish with the easy part.

Query: http://overpass-turbo.eu/s/Mpx

@PanierAvide 

> The tricky thing will be to retrieve features without any recycling:* tag, as Overpass doesn't allow to combine a regex over key and negation on value.

You can't do it (probably) in a single request, but thanks to an ability to combine requests it can be done without further local processing.

**Comment by matkoniecz** [comment] 2019-09-19 08:16
@HolgerJeromin Is there any current user of this data not listed at https://taginfo.openstreetmap.org/keys/recycling%3Aglass#projects ? It will influence quest priority (default position on the quest list).

Current status: waiting for reply at https://github.com/westnordost/StreetComplete/commit/c63059357ab837cfb4888b31c568b32100980e8f#r35141029

Initial code: https://github.com/westnordost/StreetComplete/compare/master...matkoniecz:recycling?expand=1 (unfinished, will not even compile as I interupted coding on discovering that many icon are currently unavailable)

**Comment by westnordost** [comment] 2019-09-19 09:53
I didn't convert it yet because it is not the final icon

**Comment by matkoniecz** [comment] 2019-09-19 09:59
OK, in that case I apparently started too early, I thought that icons are ready and only the final easy part remained. Thanks for already made icons!

**Comment by HolgerJeromin** [comment] 2019-09-19 10:25
> @HolgerJeromin Is there any current user of this data not listed at https://taginfo.openstreetmap.org/keys/recycling%3Aglass#projects ? It will influence quest priority (default position on the quest list).

OSMand poi info shows it after clicking the icon.

**Comment by westnordost** [comment] 2019-09-19 17:03
Added the icon

**Comment by matkoniecz** [comment] 2019-09-19 18:37
I reviewed tags and documented some results at Wiki page (numbers with links to queries) - see https://wiki.openstreetmap.org/w/index.php?title=Tag%3Aamenity%3Drecycling&type=revision&diff=1906046&oldid=1906025

For example `recycling:newspaper=yes` is quite popular but in most cases it duplicates `recycling:paper=yes`, in just 319 cases providing real info (and I suspect that most of this places simply miss `recycling:paper=yes`) so it is dubious is it really needed to be provided as an option. Though it can be added, just I would not consider it is a a blocker.

But there are thousands of `recycling:plastic_bottles` without `recycling:plastic` and it is case that I can confirm that sometimes happens - so icons for both `recycling:plastic_bottles` and `recycling:plastic` would be nice.

To my surprise similar thing happens with `recycling:plastic_packaging=yes` - often without `recycling:plastic=yes`. I am tempted to propose quest adding explicit `recycling:plastic=yes/no` to places with just `recycling:plastic_packaging=yes`, I am suspecting faulty tagging here.

I am unsure what should be done with `recycling:glass` vs `recycling:glass_bottles` - I run into it at https://github.com/osm-fr/osmose-backend/issues/549

`recycling:waste` sounds like mistagging. Is it actually popular that places accept mixed rubbish and actually recycle it?

All other values either have an icon already or seem to happen fairly rarely.

**Comment by westnordost** [comment] 2019-09-19 20:16
Your additions don't exactly make that page more clear. How about - like for the `Key:building`s page, you use your findings to organize them into categories? After all, it is pretty clear that paper is a category of etc.

I want to leave out as much as possble those "subcategories", because users will get confused (rightly so) whether if a container accepts plastic bottles and plastic, whether they have to check both, or what.

> But there are thousands of recycling:plastic_bottles without recycling:plastic and it is case that I can confirm that sometimes happens - so icons for both recycling:plastic_bottles and recycling:plastic would be nice.

Well, then it must be made very clear in the UI that this should only be selected if it is **only** plastic bottles, not other plastic packaging. But I guess, calling it "Only Plastic Bottles" in the UI is fine.

Yes, I also think that `recycling:glass` is a mistake. It stagnates since 2017, because I guess that many people made this mistake got public and people started to correct this mistake:
![index](https://user-images.githubusercontent.com/4661658/65277548-6e785500-db2a-11e9-8122-9db95e4af6e2.png)

Regarding plastic packaging, I am not sure if it is a mistake. In Hamburg, the places all accept any plastic, also toys. (And cans, even pots etc).

Cans are part of [Green Dot ](https://en.wikipedia.org/wiki/Green_Dot_(symbol)), so go into the same container as the plastic goes. In Germany. But I guess this can be different in other countries.

I could make another icon that includes a can and pot (and a screw?)...

**Comment by matkoniecz** [comment] 2019-11-05 09:01
> self-assigned this 12 days ago

Is it just covering icons? Or is there some unfinished code? I went back to finish coding of this PR and checked https://github.com/westnordost/StreetComplete/branches/all - is there maybe some offline unpushed branch?

I ask as I planned today to complete this (except icons) and it would be sad to duplicate the work.

-----

I checked now situation more thoroughly for `recycling:glass` and discovered, to my surprise, that this validator warning is mostly invalid (at least in Poland, but for reasons that are not local).

It turns out that you are supposed to put in glass recycling container only specific type of glass - one used to make bottles and jars. Glassware, pyrex, window glass, glass used to make lighting bulbs, glass from grave candles and more all are not supposed to go into glass container (not made from soda–lime–silica or at least there is significant risk of being made from other types of glass).

Fundamental problem here is that organizations responsible for recycling mislabel bins - do not label something "glass" if just one type of glass is supposed to go there!

Not sure what would be the best way to handle this - `recycling:glass` often matches what is signed on the ground, while `recycling:glass_bottles` is matching reality and regulations/recommendations.

See also https://github.com/osm-fr/osmose-backend/issues/691 https://github.com/osm-fr/osmose-backend/issues/549 https://wiki.openstreetmap.org/w/index.php?title=Tag%3Aamenity%3Drecycling&type=revision&diff=1919148&oldid=1908674

**Comment by westnordost** [comment] 2019-11-05 12:09
It's assigned to me because of the icons. I still need to do an icon for scrap metal or how it was called (pots, tools, screws,...).

Also, I wondered if I can really just include `recycling:plastic` instead of also `recycling:plastic_packaging` so I asked in the German forum.

Turns out: Whether or not they accept "any plastic" and not just "plastic packaging" in their containers is up to the individual company that was commissioned by the county / city to organize the plastic waste collection. (Cause legally they are only required to accept plastic packaging)

So, "only plastic packaging" and "only plastic bottles" must be included as options, and the three options `plastic`, `plastic_packaging` and `plastic_bottles` must be mutually exclusive in the UI. (Cause plastic includes all plastic, plastic packaging includes plastic bottles).
This needs to be reflected somehow in the UI, so I need to think of a custom UI for that. I don't think using the standard ImageSelectAdapter will suffice. The code part is really the smallest effort for this quest.

**Comment by westnordost** [comment] 2019-11-05 12:26
For the UI, there are two options:

Either show something that resembles a radio button group for "only plastic bottles", "only plastic packaging" (icon showing bottles + packaging), "any plastic" (icon showing bottles + packaging + lego), maybe frame the three options with a rounded rectangle labelled "plastic.

Or, show the "plastic bottles", "plastic packaging" and "other plastic" icons and ask the user for confirmation if he only selected "other plastic" but not the others or if he selected the latter two but not plastic bottles.

**Comment by westnordost** [comment] 2019-11-05 21:06
@matkoniecz So in other words, better leave it to me. It won't go into v15 though anymore anyhow.

But you may have noticed that I finished up the maxweight quest - single sign edition. If you like, you could continue on it, I already checked in the assets for maxaxleload, maxbogieweight and maxweightrating
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Zeichen_263_-_Verbot_f%C3%BCr_Fahrzeuge_%C3%BCber_angegebene_tats%C3%A4chliche_Achslast%2C_StVO_1992.svg/64px-Zeichen_263_-_Verbot_f%C3%BCr_Fahrzeuge_%C3%BCber_angegebene_tats%C3%A4chliche_Achslast%2C_StVO_1992.svg.png"/>, <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Denmark_road_sign_C36.svg/64px-Denmark_road_sign_C36.svg.png"/> and <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/UK_traffic_sign_622_1A_(2011).svg/64px-UK_traffic_sign_622_1A_(2011).svg.png"/>
assuming adding support for these might be your plan how to continue.

**Comment by westnordost** [comment] 2019-11-05 21:10
@matkoniecz ah but anyway, I am going to fork from your initial implementation, just saw it and no need to waste good code, you already added all those strings etc

**Closed** 2019-12-19 13:35 UTC
Labels: new quest
