### ISSUE TITLE
Unneeded metadata in svg files

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#1021] opened 2018-04-13 16:48 UTC
I noticed pretty useless metadata from inkscape embedded in the svg files, like in this one:

https://github.com/westnordost/StreetComplete/blob/master/res/building_levels_illustration.svg?short_path=20be839

`inkscape:export-filename="C:\Users\Newton\AndroidStudioProjects\streetcomplete\app\src\main\res\drawable-xxhdpi\building_levels_illustration.png"`

**Comment by rugk** [comment] 2018-04-13 18:31
This is expected.

And it is a duplicate of https://github.com/westnordost/StreetComplete/issues/814, BTW.

**Closed** 2018-04-13 18:40 UTC

**Comment by RubenKelevra** [comment] 2018-04-13 20:12
Alright, thanks :)
