### ISSUE TITLE
UI improvements for "levels of a building"

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#407] opened 2017-07-18 10:08 UTC
1. Currently I need to click into the first field to open the virtual keyboard. Is it possible to have the keyboard already visible when opening this quest?

2. Pressing "enter" on the virtual keyboard when entering "of these, levels in the roof" sould be the same as clicking "OK" to end a quest.

**Comment by westnordost** [comment] 2017-07-18 14:37
Short answer: won't do.

Long answer: the possible solution to this is a duplicate of point 1 of #393 if the author of the would reply that my suggested solution would indeed be adequate.

**Closed by westnordost** 2017-07-18 14:37 UTC

**Comment by rugk** [comment] 2017-07-21 13:43
IMHO the second point (2.) is a valid new issue. Maybe make it more general and say "better (hardware) keyboard support for solving quests" or at least for using enter to answer a quest.
