### ISSUE TITLE
Option to set language independently from system settings

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#52] opened 2017-03-29 17:57 UTC
My Android is set to English but I would like to have the object properties in my native language.

**Comment by westnordost** [comment] 2017-03-29 21:37
Sorry, I will definitely not implement that. This doesn't make sense to me and is highly unusual. I know no other app which does that.

**Comment by jmontane** [comment] 2017-03-30 06:42
Hi,
I support this feature request. Android and app language binding is good for dominant languages, but a lack for minoritized languages.

Android support few locales, even more, some vendors devices allow less locales than AOSP. For instance, Catalan is supported by AOSP, but all Motorola/Lenovo devices made Catalan unavailable. So, all apps without language selector can't use its Catalan translation.

Some known Android open-source apps within locale selector: Videolan VLC, OsmAnd, Firefox, "My Opening Hours", Wikipedia, FBReader, Omni Notes... These apps allow set "default" locale (default case), which use OS locale binding. So, everybody is happy.

**Comment by westnordost** [comment] 2017-03-30 18:34
So if you set your system language to Catalan and an app does not support that language, it falls back to English and not Spanish?

Well, this is actually an issue. But, as you mention, it is an OS issue. It should be fixed at an overall level. Bigger projects with more manpower worked around it, but a [short google search reveals](http://stackoverflow.com/questions/2900023/change-language-programmatically-in-android#2900144) that it seems to be problematic to maintain / creates regression bugs.

I will leave this bug open, because the issue definitely exists, but I will probably come around to this anytime soon.

**Comment by jmontane** [comment] 2017-04-03 07:51
> So if you set your system language to Catalan and an app does not support that language, it falls back to English and not Spanish?

Short answer: Fall-back language is English always. So, if no Catalan resource is available, then English resource is used.

Long answer: From Android 7.0, user can set a Language hierarchy. So user can define 1, 2, 3 or more language preference. For instance, a user can set Catalan, Spanish, French, and system will search for Catalan, Spanish, French resources in this preference, and fall back to English if no one is available.

In booth scenarios, languages/locales available to user on Android language system preferences dialog is managed by vendor. So, again, in some cases, few languages are available despite languages supported by AOSP.

**Comment by westnordost** [comment] 2017-04-03 20:25
Oh man, it's good to know that Google finally came up with a solution. Though, until 7.0 is used widely, a few years will pass...

**Comment by westnordost** [comment] 2017-07-04 18:49
By the way more than 50% of StreetComplete users use Android 7.0 or higher, so I will definitely not implement it because it is too much effort.

**Closed by westnordost** 2017-07-04 18:49 UTC
Labels: enhancement
