### ISSUE TITLE
add quest selection to the homepage

### ISSUE THREAD

**Issue by rza31** [westnordost/StreetComplete#788] opened 2018-01-22 16:05 UTC
Sometimes the desired tag doesn't appear, other tags are in foreground.
The quest selection on the homepage would be helpful for the user for easy selection of the needed tags.

Example: selection category filter in [https://github.com/sozialhelden/wheelmap/](url)-app.

**Comment by westnordost** [comment] 2018-01-22 18:22
I do not know what you are talking about.

**Comment by rugk** [comment] 2018-01-22 21:09
I think this is a dupe of https://github.com/westnordost/StreetComplete/issues/35. And it is already implemented, look at the bottom in the settings. There you can disable/enable quests and even sort them.

**Closed** 2018-01-22 21:50 UTC
Labels: feedback required
