### ISSUE TITLE
Quest: Identify valid/invalid almost junctions

### ISSUE THREAD

**Issue by SilentSpike** [westnordost/StreetComplete#1137] opened 2018-07-14 19:35 UTC
### General
Affected tag(s) to be modified/added: [noexit](https://wiki.openstreetmap.org/wiki/Key:noexit)
Question asked: **Does XY connect to YZ?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
  - Lets mappers and QA tools know the data is correct and not incomplete (as it may look). I often improve areas of the map based on QA results and almost junctions are a common false positive which take time to check (if even possible) and slow down mapping.
- [ ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
  - There wouldn't strictly be an equivalent tag to say that two ways do actually connect, but a comment (or `fixme`) could be added to indicate that they do and provide any further information for mappers to use
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
  - Survey necessary when imagery is obscured or unclear. Easily answerable provided the user understands the question (would need to be clear that a way which continues for any type of traffic still counts as a connection).
- [ ] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
  - Hard to say, this is also going to influenced by how well mapped the user's area is.
- [X] 🕓 Applies to a reasonable number of elements (Worth the effort)
  - If you check [Keep Right!](https://www.keepright.at/report_map.php?zoom=6&lat=57.88&lon=-4.57&lang=en&layers=B0T&db=osm_) (or Osmose) you can see this potential error all over

To be honest I'm unsure how feasible/worthwhile this quest is, but I had the thought and figure I'll post it here for discussion in any case. I think ensuring the user understands the exact question could be difficult (e.g. a road that connects to another via a footway counts as connected) and - though I'm unfamiliar with the api - also don't believe the necessary element selection process is trivial.

### Ideas for implementation

**Element selection:** 
You'd need to find highways (of appropriate type) which terminate on a node which isn't shared with any other highway; doesn't have a `noexit` tag (or barrier, etc.) ; and when projected forward by a given distance crosses another appropriate highway.

Probably worth looking at how Osmose [finds these locations](https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_highway_almost_junction.py)

**Metadata needed:** 
Don't believe so.

**Proposed GUI:**
Highlight both highways: "Does X connect to Y?"
Yes -> Ask user to describe how the ways connect -> Add comment or `fixme`
No -> `noexit` tag is added

**Comment by ENT8R** [comment] 2018-07-14 19:56
Basically this might be a good idea, but there are some other things which have to be considered in order to add a quest like this:
All quests are downloaded using the Overpass API and while it might work to retrieve ways which are located near other ways but not connected to them, I can think of some cases, e.g. two driveways which are exactly next to each other (parallel) but not connected, would it make sense to add noexit=yes to both driveways? I don't think so...

I'm also not convinced of your idea to add a new (automatically) note or add a fixme tag if the two ways should connect. There might be regions where a StreetComplete user is the only user contributing to OSM and nobody would take care of a new added fixme tag. Creating notes automatically does not work too, because notes should never be created automatically. So IMO we need to find a much better solution for what should be set if the user selects 'Yes'. (I can't think of any and I think this will be the reason why we can't add this quest :grimacing:)

**Comment by westnordost** [comment] 2018-07-14 23:04
Doesn't Vespucci show the Osmose issues by default? I think that is the better tool to concern oneself with possible but not definitee quality issues on the map like this.

**Comment by ENT8R** [comment] 2018-07-15 05:51
Yes, they are on the map be default:
![Vespucci screenshot](https://i.imgur.com/eFqT6NM.png)

**Comment by SilentSpike** [comment] 2018-07-29 09:36
Update on the tagging front: I noticed that on the [fixme](https://wiki.openstreetmap.org/wiki/Key:fixme) page it lists `noexit=no` as the way to tag cases where the way does continue. However, points made in the comments above still stand.

**Comment by westnordost** [comment] 2018-07-30 21:41
`noexit=no` is marked as deprecated. Also, setting this tag also does not solve the issue but only marks it as valid. This is not the concept of StreetComplete. So, this quest does not fit into the concept of this app.

What would be theoretically possible is a class of quest that does not actually upload the information to OSM but to another system, for example Osmose. However, that would require (Osmose) to be able to mark a warning either as invalid or **confirmed**. As far as I know, it is not possible to mark any warning as confirmed in Osmose and similar Q&A tools (because this is a use case they did not explore yet)

**Closed by westnordost** 2018-07-30 21:41 UTC
