### ISSUE TITLE
Cannot lock map to GPS location anymore (app crash)

### ISSUE THREAD

**Issue by TO-92** [westnordost/StreetComplete#950] opened 2018-03-05 21:15 UTC
Today I updated StreetComplete to version 4.0. Now unfortunately I can no longer keep the map automatically centered on the current position; whenever I tap the location button the app terminates.

Sony Xperia V (aka LT25i) running stock Android 4.3 – I used the "feedback" option from the crash dialog to send a report, does that end up where you can access it?

Everything else seems to be working fine, even the blue location marker is correctly shown on the map. It's just a bit annoying that I always have to scroll the map around manually, or even zoom out to see where I am.

**Comment by westnordost** [comment] 2018-03-05 22:01
Depends on from where you downloaded and installed the app.

**Comment by TO-92** [comment] 2018-03-05 22:24
Using the regular update function in the Google play store. I'm not aware of any other possible download locations.

**Comment by goldfndr** [comment] 2018-03-06 06:30
I'm able to reproduce the crash.

4.0-beta2 from [the releases page](https://github.com/westnordost/StreetComplete/releases) does not crash – I can toggle the lower-right icon at will.

Upgrading from that to the 4.0 release does crash. If the "map_following" preference (MainActivity.xml) is true, it crashes at startup. If false, it can work, but tapping the icon causes a crash.

By the way, with no data (App Info deletion), 4.0 can't start if Location Services are on. One must start it with Location off. If, after started with Location off and one hasn't scrolled, it crashes immediately when Location is turned on.

Moto G (2013 XT1028), rooted stock KitKat 4.4.4 with some Xposed modules.

**Comment by westnordost** [comment] 2018-03-06 14:42
@goldfndr , do you have Android Studio? If yes, could you test if it is solved on the current master? https://github.com/westnordost/StreetComplete/commit/ae1e39664e3edef64e9c799a6e2ae5ff897c1d86 might have solved the issue.

**Comment by goldfndr** [comment] 2018-03-06 20:22
It took a long time (1.5h per build, 2x on a 4 GB WinXP-32 with Android Studio 2.3.3) but I can confirm that that change (1.1.3 to 1.1.0) makes the difference.

**Comment by westnordost** [comment] 2018-03-06 21:25
Wow, thank you! What I find remarkable is:
* Windows XP?? :-O Shouldn't this be hugely unsafe by now? (eternal blue)
* 1.5 hours per build?! On my machine, it takes something below 5 minutes

**Comment by westnordost** [comment] 2018-03-06 21:25
So I close this because it has been fixed already. Perhaps tomorrow I create a new version. Perhaps I also downgrade tangram-es to 0.8.1 because of the crash bug.

**Closed by westnordost** 2018-03-06 21:25 UTC
Labels: bug, feedback required

**Comment by matkoniecz** [comment] 2018-03-06 21:34
Windows XP is a safety risk, but Eternal Blue is poor example - Microsoft released security updated even for an unsupported Windows XP.

**Comment by TO-92** [comment] 2018-03-12 17:22
It's back to normal operation with 4.1. Thanks!
