### ISSUE TITLE
Add dropdown to select street for buildings without one

### ISSUE THREAD

**Issue by RAVMN** [westnordost/StreetComplete#1136] opened 2018-07-14 16:12 UTC
It would make it easier to add house number to buildings without a street tag filled if one can fill it from within the app. Selecting one of the near streets would likely make it easier and without typos.

**Comment by ENT8R** [comment] 2018-07-14 16:35
If it is about the street name of a house it would be a duplicate of #213...

**Comment by RAVMN** [comment] 2018-07-14 16:40
Yes, it is about addr:street didn't find that bug earlier

**Closed** 2018-07-14 16:39 UTC
