### ISSUE TITLE
Jump to next quest

### ISSUE THREAD

**Issue by rindlerblabla** [westnordost/StreetComplete#256] opened 2017-05-21 20:11 UTC
When you have answered, or don't know the answer, it would be nice to just click 'Next quest' without having to click the map again. Google maps has this function for their suggestion feature and you directly jump to the next closest quest. A really smooth way to answer next quest.
![20170521_220905](https://cloud.githubusercontent.com/assets/28257974/26287006/368bfdf6-3e72-11e7-952e-dedcb087779c.png)

**Comment by westnordost** [comment] 2017-07-04 18:41
Duplicate of #164

**Closed by westnordost** 2017-07-04 18:41 UTC
Labels: enhancement
