### ISSUE TITLE
Photos in note response give 404

### ISSUE THREAD

**Issue by ltog** [westnordost/StreetComplete#1588] opened 2019-09-30 19:06 UTC
I answered to a note (created by myself) with an answer and two photos: https://www.openstreetmap.org/note/1702676 The photos both give a HTTP 404 error.

**How to Reproduce**
Open the links given in https://www.openstreetmap.org/note/1702676 :
- https://westnordost.de/p/6083.jpg
- https://westnordost.de/p/6084.jpg

Unfortunately I'm not sure what exactly I did to get this behaviour. I had auto-sync on, maybe I did an undo after uploading. 

**Versions affected**
Android version 7.1.2.

Not sure about StreetComplete version, probably the predecessor of 14.1.

**Comment by westnordost** [comment] 2019-10-19 17:45
Ping

**Comment by westnordost** [comment] 2019-10-19 18:26
Turned out to be a duplicate of #1569

**Closed** 2019-10-19 18:28 UTC
Labels: duplicate
