### ISSUE TITLE
No more map!

### ISSUE THREAD

**Issue by Toover** [westnordost/StreetComplete#244] opened 2017-05-16 20:51 UTC
It has been few weeks now that StreetComplete cannot show the map anymore, and is therefore unusable.
I can have location and track it, I can see the quests around me, but I cannot see the map (streets, buildings, etc...).
I am running StreetComplete 0.10 (last update did not solve the issue) on an Android 4.4.4 (CyanogenMod). It used to work, and since it stopped working, I tried to clear the cache and the application data, but nothing changed.

**Comment by westnordost** [comment] 2017-05-16 21:37
Hmm, this is a duplicate of #175

Apparently there is a https-issue with Android 4. I revert back to http for the next version.

**Closed by westnordost** 2017-05-16 21:37 UTC

**Comment by hjanetzek** [comment] 2017-05-17 15:27
@westnordost tangram-es 0.6.3 should work with https on Android 4 (We are enabling TLS 1.2 manually for okhttp client) It also adds some logging with which we could track down the https issue with Android 7
