### ISSUE TITLE
Quest "What is the topic of this information board?" – double option

### ISSUE THREAD

**Issue by legofahrrad** [westnordost/StreetComplete#3415] opened 2021-10-20 13:04 UTC
Quest: "What is the topic of this information board?"
The option public transport is twice there but the second option sets it to sports. One of the labels is wrong.

**How to Reproduce**

**Versions affected**
StreetComplete v36.0
My Android Version v11

**Comment by matkoniecz** [comment] 2021-10-20 13:37
Thanks for reporting! This problem is fixed in code (see #3365) but may is not yet released. (confirmed by `git tag --contain bfca558236fcd2e7f79cdf593fcd1cfe95ceab43`)

Though maybe it would be worth mentioning in https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/res/raw/changelog.yml

**Comment by matkoniecz** [comment] 2021-10-20 13:38
@westnordost Do you prefer to update changelog on your own or would be helpful to add stuff there?

**Comment by westnordost** [comment] 2021-10-20 13:41
This was fixed by @kmpoppe 10 days ago. However, it looks like I forgot to cherry-pick this into the changes for v36.1.

So it will be fixed only in v37.0 as a v36.2 is unlikely.

**Closed as completed** 2021-10-20 13:46 UTC
Labels: bug
