### ISSUE TITLE
Idea : Tracking based quests 

### ISSUE THREAD

**Issue by EpicKiwi** [westnordost/StreetComplete#1193] opened 2018-09-10 23:01 UTC
The idea is to send push notification to the user when a quest is available at his position. The position is sent to the user if he's not moving for a long time (>5min).

The quest is a simple quest that can be answered in a shop queue or at the bus stop. Quests like the type of the building, the address, the type of shop, the type of sport, etc.

This functionality require to create a background tracking service and a user position history of the last hours. 

This functionality can be valuable to encourage the user to come back on the application to contribute during his free time.

Finally, like the Google Maps contribution tools. We can imagine to ask simple quests about visited places of the user during the lasts hours or days.

What do you think ?

Of cours this functionality need to be disablable in the settings.

**Comment by axre** [comment] 2018-09-11 09:13
Personally I hate applications disturbing me in my free time, mostly for irrelevant reasons. If I want something to do in SC I just open the application - yeah, I even do this while I wait at the bus stop. Takes rarely a few seconds.

Can't decide for other people whether they find a feature like this annoying or useful.

**Comment by rugk** [comment] 2018-09-11 09:32
duplicate of https://github.com/westnordost/StreetComplete/issues/195

**Comment by ENT8R** [comment] 2018-09-11 13:09
Is not this also related to #48?
And @Teester created a app which is similar to StreetComplete but AFAIK it only shows quests and notifications for nodes you stayed at for some time... (This would be like the Google Maps contribution tools)
Teester/Whats-Nearby#6

**Comment by EpicKiwi** [comment] 2018-09-11 18:07
I understand your position Axre.
 
Yeah google made this very well in the gmaps contribution tool and sometimes I take 10 min to aswer some question on Gmap. 10 min that often transform in an hour of contribution. I'd love to have the same gamifyed experience on SC.

Personnaly, I don't have the habit to open StreetComplete each time I have free time and I think this could be interesting that the app remind me sometimes to contribute. I didn't know about Wat's nearby and I think the two ideas are compatible to be joined in a single App.

If it's not in your roadmap or in the SC philosophy you can close the issue.

**Comment by rugk** [comment] 2018-09-11 18:59
So what you aim at is basically https://github.com/westnordost/StreetComplete/issues/195, judging from what you describe, i.e. "encourage users to come back", and as I've written there, I think this is a great idea and I also often "suffer" from the problem of not opening SC at the right time. :wink:

**Comment by westnordost** [comment] 2018-09-12 21:47
There is no server, thus, there are no push-notifications in StreetComplete. What you mean is probably just notifications (without the push). This would require StreetComplete to periodically run in the background, check the GPS position and look for quests. This is doable and is basically #48, I don't get what is the advantage to only enable this behavior when this the user is immobile.

Anyway, the way I would implement this it is an additional setting that is by default off and that this tracking is only done while the app is still in the background. I.e. if the user deliberately closes this app by swiping it off his recents view, the tracking will also stop even if that setting is on.

I am closing this as a duplicate of #48.

**Closed by westnordost** 2018-09-12 21:47 UTC
