### ISSUE TITLE
Bug: missing buildings

### ISSUE THREAD

**Issue by kabo** [westnordost/StreetComplete#1025] opened 2018-04-17 00:17 UTC
Hi,

It seems some buildings are missing on the map. I created a note that a building was missing, but it turns out I can see the building on the web.

https://www.openstreetmap.org/note/1361508#map=19/-37.80102/174.87013

![screenshot_20180417-115846](https://user-images.githubusercontent.com/357601/38841577-2c334c44-4239-11e8-97af-eed1940289d8.png)

**Comment by ENT8R** [comment] 2018-04-17 04:26
The building was added 14 hours ago. You should give the tile server a little bit more time before you raise an issue here :smile:
I fear that this building won't show up in the next 2-3 months because the tile server we use can't be updated daily.
For more information see #1011 or #747

**Comment by kabo** [comment] 2018-04-17 04:40
I'm so confused. So I added the note 22 hours ago. 14 hours ago someone added the building. Then constable commented "looks good to me" (implying "what are you talking about, the building is right there"). Then I checked the note and saw the building on the web map. So I thought there was a bug in the app and created this issue. Is this a correct guess at what happened?
How do you check when a building was added and by whom?

**Comment by matkoniecz** [comment] 2018-04-17 06:08
Sounds like duplicate of #1011

**Closed as completed** 2018-04-17 10:20 UTC
