### ISSUE TITLE
New Quest: For which sport is this guidepost intended? (information=guidepost/route_marker)

### ISSUE THREAD

**Issue by mcliquid** [westnordost/StreetComplete#4758] opened 2023-01-18 10:11 UTC
### General
Affected tag(s) to be modified/added: The common and established tags for sports (like `hiking`, `bicycle`, `ski`, ...
Question asked: **For which sport is this guidepost intended?**
The goal is to determine the particular sport(s) for a guidepost or routemarker.

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

Number of matched nodes in Austria: 14310
Number of matched nodes in Germany: 37408
Number of matched nodes in Switzerland: 7956
Number of matched nodes in United States: 10388

Overpass-Link: https://overpass-turbo.eu/s/1qhA

### Ideas for implementation

**Element selection:** 
```
nodes and 
["tourism"="information"] and
["information"="guidepost"] or ["information"="route_marker"] and
[!"hiking|bicycle|mtb|climbing|horse|nording_walking|ski|inline_skates|running"] and
[!"disused"][!"guidepost"]
```

There are certainly more sports to filter. Here are the ones that are known to me so far. Please comment if I've missed one!

**Concerns:** 

- It often happens that there are several signs for different sports hanging on a pole. Since the ref=* is usually also different, I have preferred to enter the nodes separately. This would not be possible in the Quest. A multiple selection would then have to be stored using a semicolon.
- There are different ways to tag the sport. Either with "hiking=yes" or "guidepost=hiking" or "guidepost:hiking=yes". Based on an evaluation of taginfo, the first one in the list is the most used.
- There is no "no" answer. But from my point of view, each signpost has a specific sport (at least from my regional experience). If the user can not say it it definitely needs a "can't say" answer option if it is not answerable to the user.
- If there is no specific sport displayed on the guidepost, there is `guidepost=simple` in the wiki: https://wiki.openstreetmap.org/wiki/Tag%3Aguidepost%3Dsimple

**Proposed UI:**

- Simple image selection or icon selection as in the recycling quest.
- You should be able to specify "This is a routemarker" as an alternative answer. This answer is more for experienced users, but it makes the usability easier and the effort is manageable.

I might even be able to implement it myself if the quest meets the criteria.

**Comment by matkoniecz** [comment] 2023-01-18 12:37
>  To be added tag is established and has a useful purpose

is this data used or potentially useful?

**Comment by eginhard** [comment] 2023-01-18 13:26
This is a duplicate of #1412

**Comment by mnalis** [comment] 2023-01-20 12:33
Only thing I see as problematic for regular SC was mentioned in previous ticket:

> However, I'd still close this as will not fix mainly because the average joe will not (always) be able to tell apart with certainty if a guidepost is meant for hikers, bicyclists or are generic ones (the ones you'd denote as city / diy).

Perhaps it would get in as disabled-by-default because of that reason; dunno.

However, I'm pretty sure that even if it ends up not being accepted here, [StreetComplete Expert Edition fork](https://github.com/Helium314/StreetComplete/) would be interested in your PR, so the effort wouldn't be wasted.

**Comment by matkoniecz** [comment] 2023-01-20 13:13
> However, I'd still close this as will not fix mainly because the average joe will not (always) be able to tell apart with certainty if a guidepost is meant for hikers, bicyclists or are generic ones (the ones you'd denote as city / diy).

So the question is how to deal with things like

![18265](https://user-images.githubusercontent.com/899988/213703037-d0dc83a5-d483-464c-8c61-630dfabef177.jpg)

or

![screen](https://user-images.githubusercontent.com/899988/213703109-8c78cdd7-6203-4c05-ac9a-47b94f8d83ff.png)

Is it solved or not?

**Comment by matkoniecz** [comment] 2023-01-20 16:10
>  it would also be reasonable to develop a clearly generic value for guidepost=* for this purpose with guidepost=generic or to capture the different generic types of guideposts.

in such case such new tagging should be proposed outside StreetComplete ( https://community.openstreetmap.org/ ? tagging mailing list? proposal process? ) - and if not rejected then it can be used by StreetComplete.

**Comment by rhhsm** [comment] 2023-01-20 16:49
I'd guess most guideposts are not dedicated to a particular sport/mode of transport and could be useful to several different or even all users. In that case, what should SC tag it with? There doesn't seem to be an established, well documented tag for these many cases. The wiki for guidepost states that "The tag guidepost=* is not clearly defined yet"...

**Comment by westnordost** [comment] 2023-01-21 01:08
`sport=no` is not in use and could be considered somewhat of a troll tag. (Like `shop=no` `building=no` etc)

**Closed as not planned** 2023-01-21 07:32 UTC
Labels: blocked

**Comment by westnordost** [comment] 2023-01-21 12:27
No

On January 21, 2023 8:25:46 AM GMT+01:00, mcliquid ***@***.***> wrote:
>> and could be considered somewhat of a troll tag. (Like `shop=no` `building=no` etc)
>
>According to this logic `sidewalk=no` and `cycleway=no` are troll tags too?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/4758#issuecomment-1399198552
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by gdabski** [comment] 2023-01-26 20:11
I don't like the assumption that a guidepost is primarily meant for sports. To me, it's the inverse. A guidepost may be devoted to a specific sport, but the default is a generic guidepost that is suitable for anyone not familiar with the area (cf. guidepost is in `tourist=*`, not `leisure=*` namespace), be it a tourist or someone doing a sport for recreation.
