### ISSUE TITLE
"No further quests" even when added new ones with another app

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#482] opened 2017-08-14 23:01 UTC
In the last few days I used JOSM and Vespucci to replace "building=yes" to the according building type. When I now press "Scan" it always says "No further quests available".

A "fix" for this is sometimes to zoom out to get a larger area to scan for new quests. Then they show up.

But in most cases this does not work. Is there any method to get those quests without "CLEAR DATA" for the app?

**Comment by dbdean** [comment] 2017-08-15 01:47
This happens for me too, a lot. I regularly clear data for the app, so that it can find quests properly. For example, this group of newly mapped residential buildings stubbornly refuse to show up even after scanning for quests multiple times in the area. Based on past, similar, experience, I'm sure they'll show up if I clear data for the StreetComplete.
![screenshot_20170815-114212](https://user-images.githubusercontent.com/12725310/29299016-1f59bc06-81af-11e7-90d9-123e3bf1f81f.png)

**Comment by westnordost** [comment] 2017-08-15 10:08
Currently only patience (though, exactly this does not seem to work well) or clearing data. There is a feature request to add a button to flush the quest cache which would be trivial to implement.

**Comment by westnordost** [comment] 2017-08-15 19:58
This is a duplicate of #480

**Closed by westnordost** 2017-08-15 19:58 UTC
