### ISSUE TITLE
OSM Note picture sometimes gets lost?

### ISSUE THREAD

**Issue by mnalis** [westnordost/StreetComplete#2313] opened 2020-11-21 22:25 UTC
**How to Reproduce**
When adding note in StreetComplete (by clicking on the map and selecting `Create new note`, and adding picture to the note, sometimes the note is submitted, but the URL for the picture returns `404 Not found` error.

It happens very rarely, but IIRC it did happen at least once or twice before to me.
Example note I found now is:
https://www.openstreetmap.org/note/2384545

Picture URL leads to https://westnordost.de/p/20283.jpg which gives 404 error:
"Not Found
The requested document was not found on this server.
Web Server at openclonk.org"

As I understand the docs, the pictures will be deleted some time after the note is closed, but this one has not been closed (only commented on). 

**Versions affected**
Android 10 (EMUI 10.1)
This one says it has been created with StreetComplete 24.0.

**Comment by westnordost** [comment] 2020-11-21 23:00
Yes, when the connection fails in the moment after uploading the photo but before activating it. Duplicate of #2102

**Closed** 2020-11-21 23:00 UTC
Labels: bug, duplicate
