### ISSUE TITLE
Font size of the counters sometimes increases, cropping the displayed number

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#1208] opened 2018-09-23 06:42 UTC
Hello,

since version 7.1 (or even 7.0, but I have never experienced this with earlier versions!) the font size of one of the counters sometimes changes. when solving quests and/or uploading the solved quests. If this size change affects the total number, it's getting clipped.

![screenshot_2018-09-12-21-17-04](https://user-images.githubusercontent.com/32601012/45924928-c4142480-bf0b-11e8-9396-8471173c185a.png)

(Android 5.1 on a bq M4.5 (4,5" display), StreetComplete 7.1)

Has anyone else experienced this? I will try to reproduce this behaviour and give more details as soon as I know more.

The cycling cat

**Comment by westnordost** [comment] 2018-09-23 12:04
Is this also the case with v8.0?

**Comment by rugk** [comment] 2018-09-23 19:15
Also saw this with v7.0. I also correlate it with the battery saving mode (i.e. I always only noticed it when this mode was on), but I currently could not reproduce it by turning it on. So I don't really know what causes it.

LineageOS 14.1

**Comment by cyclingcat** [comment] 2018-09-25 15:35
On my phone (still SC 7.1) it's reproducible the following way:

1. Solving at least one quest shows the size of the **second** counter in a bigger font size.
2. Uploading the solved quests shows the size of the **first** counter in a bigger font size.
3. Closing and reopening the app **resets** both font sizes to their original values.

So the screenshot above is reproducible with actions 1 - 3 - 2 (in this order).

The cycling cat

**Comment by westnordost** [comment] 2018-09-25 17:01
It should actually animate popping up, then returning to its original size. Do you have animations off in your system settings?

**Comment by rugk** [comment] 2018-09-25 18:44
No.

**Comment by cyclingcat** [comment] 2018-09-26 15:49
Indeed, I switched animations off. (One of the first things I regularly do after installing a new OS or piece of software if possible - I hate these kinds of distractions or artificial delays!)

**Comment by rugk** [comment] 2018-09-26 16:11
Oh yeah, also realized I had animations off when reproducing this issue, as this is one thing the energy save mode of Android does. 😄

**Comment by rugk** [comment] 2018-09-28 10:53
As my cause was the same, and I have not seen it now, I assume it works now.

So IMHO, we can close this issue.

**Closed** 2018-09-28 20:57 UTC
Labels: bug, feedback required
