### ISSUE TITLE
Interface for enabling/disabling quests

### ISSUE THREAD

**Issue by afmenez** [westnordost/StreetComplete#609] opened 2017-09-25 18:00 UTC
As more quests are added, it would be nice to have a way to enable/disable them.  There are already some quests that I am not interested in hiding quests that I want to participate.

**Comment by westnordost** [comment] 2017-09-25 18:34
Duplicate of #34

**Comment by westnordost** [comment] 2017-09-25 18:34
I mean #35!

**Closed by westnordost** 2017-09-25 18:34 UTC

**Comment by rugk** [comment] 2017-09-25 19:45
Yet gain… :smiley:
