### ISSUE TITLE
17.0beta2 crashes on vegetarian quest

### ISSUE THREAD

**Issue by peternewman** [westnordost/StreetComplete#1712] opened 2020-01-31 19:21 UTC
Trying to complete vegetarian quest closes app. 

**How to Reproduce**

**Versions affected**

17.0beta2
Android 9

**Comment by westnordost** [comment] 2020-01-31 21:53
Do you use the Google Play version? No crash report reached me so far. Also I cannot reproduce it.

Is it reproducible for you? And what about the vegan quest?

**Comment by peternewman** [comment] 2020-01-31 22:35
> Do you use the Google Play version? No crash report reached me so far. Also I cannot reproduce it. 

Yes I do. Telford Service station in the UK does it. 
> 
> Is it reproducible for you? And what about the vegan quest?

Yes, haven't tried vegan yet.

**Comment by westnordost** [comment] 2020-01-31 22:41
So you mean, you can reproduce it but only exactly at one place? Can you tell me the location of that place?

**Comment by peternewman** [comment] 2020-01-31 22:51
https://www.openstreetmap.org/node/4849911834#map=18/52.67701/-2.39945

**Comment by peternewman** [comment] 2020-01-31 23:11
I can't get a vegan quest up there to test it and I'm struggling to find another to check that.

**Comment by westnordost** [comment] 2020-01-31 23:22
Hmm, I also can't reproduce it there.

Do you have auto-sync on or off? Does it happen immediately after you tapped the answer?

**Comment by peternewman** [comment] 2020-01-31 23:23
It's just that node, vegan and vegetarian work elsewhere for me. This feels like the crossing thing I had before which was only cleared by clearing my cache.

**Comment by peternewman** [comment] 2020-01-31 23:25
> Hmm, I also can't reproduce it there.
> 
> Do you have auto-sync on or off? Does it happen immediately after you tapped the answer?

WiFi only. 

Sooner, the moment I tap the quest icon it bombs out before I even get a chance to answer.

**Comment by westnordost** [comment] 2020-01-31 23:26
Oh, that's different! What language do you use on your phone, en-GB?

**Comment by peternewman** [comment] 2020-01-31 23:29
> Oh, that's different! What language do you use on your phone, en-GB?

Yes

**Comment by westnordost** [comment] 2020-01-31 23:39
Hmm, even still can't reproduce it.
Well tomorrow latest I should see the crash report in the developer area in Google Play, we'll see.

**Comment by westnordost** [comment] 2020-02-02 11:24
No related crash report turned up. Can you reproduce this bug still with the beta3?

**Comment by westnordost** [comment] 2020-02-02 11:25
If yes, could you please download the APK from here https://github.com/westnordost/StreetComplete/releases/download/v17.0-beta3/StreetComplete-v17.0-beta3.apk ? When this APK crashes, it will prompt you to send the crash report directly to me via Email.

**Comment by HolgerJeromin** [comment] 2020-02-02 13:37
I installed the apk (over play store 16.x) and got this:
![rps20200202_143547_347](https://user-images.githubusercontent.com/2410353/73608984-5846cf00-45c9-11ea-9671-3a24135d1d71.jpg)

No way to open the app

**Comment by westnordost** [comment] 2020-02-02 13:47
What, with beta3??

**Comment by HolgerJeromin** [comment] 2020-02-02 15:23
With the linked apk

**Comment by westnordost** [comment] 2020-02-02 15:32
Phew. I also downloaded the linked APK but could not reproduce any crash. If it crashes right on start-up, of course it is not possible for you to send me any email through this app.

But anyway, this is a different problem as the one discussed here. @HolgerJeromin , could we either continue tracking this problem via email or via a new ticket please? My email is osm@westnordost.de.
The next thing I would be asking you is to uninstall the app and reinstall it, see if it still crashes then. This way I know at least if the crash happens due to some configuration made.

**Comment by peternewman** [comment] 2020-02-02 21:41
> No related crash report turned up. Can you reproduce this bug still with the beta3?

No it doesn't seem to any more. Do you think you found the cause of it, or is it likely to have just been some cache thing that got chased away?

**Comment by westnordost** [comment] 2020-02-02 23:35
No idea. You said that it always happened for this one quest, exactly when opening it. No bug that I fixed (or for that matter, nothing that I changed for v17) had anything to do the the veg quest or any quest form being displayed. So,... no idea, but if it is gone now, let's close it and we will see if the bug occurs later on.

**Closed by westnordost** 2020-02-02 23:35 UTC
Labels: bug, feedback required
