### ISSUE TITLE
undo does not allow to reanswer quest

### ISSUE THREAD

**Issue by codingcatgirl** [westnordost/StreetComplete#849] opened 2018-02-09 15:26 UTC
If i answer a quest incorrectly and undo it, the quest does not allow me to reanswer it correctly. But most times when i know that i answered it wrong, i also know the correct answer and want to give the correct answer. however, after undoing my last answer, the quest dies not appear again. 

This behaviour is present for me in version 3.6. I don't know whether this is a bug or intended, but i would wish very much that it was possible anyway. This is propably related to and possibly even a duplicate of #681, but that issue is closed and sounds like it was resolved. Still, undone quests do not reappear on the map for me.

**Comment by westnordost** [comment] 2018-02-09 16:04
Do you have this problem with cycleway or housenumber quests?

Because for certain quest types, this feature is disabled. Namely, for cycleway and housenumber quests, otherwise it should work. This is a technical limitation as some quests are too complex for the app to  determine if they should be shown now or not without making another overpass query (= downloading the area anew). So this would be a will-not-fix.

**Comment by westnordost** [comment] 2018-02-09 16:06
Also, if I remember correctly, if you turn off the automatic sync in the options and always manually upload your changes, then, not-yet-uploaded changes that you undo will always reappear on the map, as the underlying mechanism is different. (It is just a local undo, not revert of the committed change)

**Comment by codingcatgirl** [comment] 2018-02-09 17:05
No, i had that issue it with number of hose levels, speed limit, and opening times. I never undid something and had the quest reappear again. Not even after clearing the cache :/

**Comment by codingcatgirl** [comment] 2018-02-09 17:10
I now disabled auto-sync and will see if the issue persists even there. But if i understand you correctly, it should not happen with auto-sync either way :)

**Comment by westnordost** [comment] 2018-02-09 17:53
Okay, can reproduce

**Comment by westnordost** [comment] 2018-02-09 19:59
Oh damn, this is a critical bug. It also exists since v3.3

**Comment by westnordost** [comment] 2018-02-09 23:57
😓

**Closed by westnordost** 2018-02-09 23:57 UTC
Labels: bug

**Comment by codingcatgirl** [comment] 2018-02-10 11:10
Whoah, that was unexpected! all my smpathies to you, this is certainly the kind of bug you never want to have ^^

it would be soo nice if there at least was a way to find out which edits i tried to revert… but skimming the source code it doesnt seem to be possible… but if it was possible you propably would have noted that anyway.

Nevertheless: Thanks for your work!

**Comment by westnordost** [comment] 2018-02-10 15:14
Yeah, changes that failed to apply due to conflicts are dropped from the database, so no trace is left.
