### ISSUE TITLE
Search for more than 10 quest types at once

### ISSUE THREAD

**Issue by NotSoImportant** [westnordost/StreetComplete#1985] opened 2020-07-28 22:02 UTC
_First of all: cheers. SC is an easy way to improve_ **some** _map data :-)_

Clicking the search button currently only checks the first 10 types of the configured ones.
So to the user it looks like there is no more quests to answer.

**Use case**
This is a problem
- if the user would have been able (and willing) to answer other quests than the ones shown
_(Configuring different [less] types does not help, as I might want to answer from all types, but only be able to answer one or the other concrete quest at a time)_

Multiple clicks on the search button are needed to finally show all open quests (of the all configured types).

I understand it was designed like this to not overwhelme the user and have reasonable performance, but it limits the benefit a lot.
See https://github.com/westnordost/StreetComplete/issues/1874#issuecomment-645441710

**Proposed Solution**
1. Show a banner to indicate what types have currently been searched for (e.g. "6/20 configured types")
1. Add option to search for all quests at once (of a certain area) = #1418 
    - Choose to download all quests, but only for a list of streets = #473 (Closed)
1. Better visualize which area quests have been loaded for (or if there are no such open quests maybe)
    - Does the zoom level make a difference on number of quests loaded?
       If yes: visualize this in the app.
1. In the the quest type configuration give a (green/yellow/red) hint on how long it could probably take to query information for this quest type
1. Is there a priority and are quests shown / search for based on it?
    - If yes: Please mention / visualize this in the app
1. Have #1874 implemented (related to #122)

version: 21.0
additional keywords: details, levels, query

**Comment by NotSoImportant** [comment] 2020-07-28 23:08
Just found this is partially a similar request as https://github.com/westnordost/StreetComplete/issues/1418

**Comment by smichel17** [comment] 2020-07-28 23:25
…and would be solved by the rather-difficult-to-find-by-searching-due-to-its-name https://github.com/westnordost/StreetComplete/issues/1874

**Comment by westnordost** [comment] 2020-07-30 13:29
Yes, basically this is a duplicate of #1418 / #1874. Which will definitely be implemented (draft implementation already exists), but not soon.

**Closed by westnordost** 2020-07-30 13:29 UTC
