### ISSUE TITLE
Fuel pump for adblue?

### ISSUE THREAD

**Issue by davidbaumann** [westnordost/StreetComplete#2151] opened 2020-10-09 19:46 UTC
### General
Affected tag(s) to be modified/added: [fuel:adblue](https://wiki.openstreetmap.org/wiki/Key:fuel:adblue)
Question asked: **Does this gas station offer a pump for adblue?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

I was driving around looking for a pump for adblue for my car, as I need over 10 liters. OsmAnd allows me to filter for that, but actually it's almost never tagged in Germany where I live.
In Hungary, there are many gas stations tagged, also with fuel:adblue=no, where there is no pump. 

### Ideas for implementation

All amenity=fuel will be asked for, with a simle yes/no field, where fuel:adblue does not exist (or better is not yes or no?).

**Comment by westnordost** [comment] 2020-10-09 20:06
Basically, this is a duplicate of #121 and/or would have the same reasons why this cannot be implemented in StreetComplete.

**Comment by westnordost** [comment] 2020-10-13 15:54
(no feedback)

**Comment by davidbaumann** [comment] 2020-10-13 16:10
Hello,
what kind of feedback? From me?

**Comment by westnordost** [comment] 2020-10-13 16:13
Yes. I explained why it cannot be implemented, but maybe you have some arguments why you think those arguments do not apply here or can be worked around in one way or the other. This is why I waited and did not close it immediately.

**Comment by davidbaumann** [comment] 2020-10-13 16:17
Hm, I guess it would make sense so write fuel:ablue=no, so the quest won't appear anymore.
But I have no arguments why adblue would be more important than CNG or LPG, though adblue might be some more important.

Maybe it would even make sense for all 3 fuels.

In fact, at least adblue pump stations can be found tagged really rarely in germany.

**Comment by westnordost** [comment] 2020-10-13 16:35
Okay, let's go a bit more into detail. Most problematic is actually this point I made:

> in principle, this tagging scheme has the same problem as the `recycling:*` tagging scheme: Is a certain fuel not available or has it just not been tagged (yet)? This is problematic because as soon as there is **any** `fuel:*` tag, we have to assume that it **only** sells the given fuel(s). So, even asking "Does this fuel station sell LPG?", which would be an important thing to ask (if it wasn't spam) is not possible because then we'd have to tag the fuel station in a way that implicitly suggests that it only sells LPG.

Which is also true for adblue.

If that wasn't a problem, a slight problem that remains would be that adblue is a brand name. So, it should actually be something like `fuel:diesel_exhaust_fluid` or better something that suggests that there necessarily has to be a fuel pump (there are? adblue is not a fuel) but that it is simply sold, for example in canisters.
Clearing this up would need to be made in the wiki / community, not here.

**Closed** 2020-10-16 12:53 UTC
Labels: feedback required, wontfix
