### ISSUE TITLE
Quest download problems

### ISSUE THREAD

**Issue by kuba-orlik** [westnordost/StreetComplete#1429] opened 2019-06-17 10:28 UTC
Every time I download new quests they either don't appear at all (download error), or only partially (street name quests, no Opening Hours quests etc - even thou I enabled them in settings). I suspect it might be a server-side issue? But other OSM-editing apps on my phone do not seem to have any hiccups when connecting to the backend

**How to Reproduce**
Open the app and try to download new quests

**Versions affected**
Android 8.1.0, StreetComplete 12.1

**Comment by westnordost** [comment] 2019-06-19 22:40
Duplicate of #1418 / #1428

tldr: It is not a bug, the app works this way that it only downloads a few most important quest types first and only loads more later after some have been solved.

**Closed by westnordost** 2019-06-19 22:40 UTC

**Comment by rugk** [comment] 2019-06-21 13:22
see https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Why_does_StreetComplete_show_so_few_quests_when_I_first_start_the_app.3F
