### ISSUE TITLE
Automatically open adjacent quests of the same type

### ISSUE THREAD

**Issue by ludwigbald** [westnordost/StreetComplete#2360] opened 2020-12-09 00:08 UTC
**Use case**

Let's say the user has opened the app and wants to get some quests done.

After finishing a quest, for example inputting the street material for a street, I expect to be able to easily input the material for other streets i can see. Instead, i have to manually find and select a new quest. It's preferable to do a few quests of the same type at a time, to avoid context switching and in turn improve speed.

**Proposed Solution**

If there is a nearby quest of the same time, directly open that dialog instead of having to close and open the next one.

**Comment by ludwigbald** [comment] 2020-12-09 00:11
Note that this is different from #2354 :
I propose a way to speed up quest completion of similar quests, #2354 proposes adding context for completing a quest.

**Comment by smichel17** [comment] 2020-12-09 00:14
Duplicate of #124, though :laughing:

**Closed by smichel17** 2020-12-09 00:14 UTC

**Comment by smichel17** [comment] 2020-12-09 00:25
Actually https://github.com/westnordost/StreetComplete/issues/1969#issuecomment-723457563 Although @westnordost, still interested in hearing more about why it didn't work out
