### ISSUE TITLE
Opening hours for disused shop

### ISSUE THREAD

**Issue by bbastin** [westnordost/StreetComplete#1046] opened 2018-05-03 20:48 UTC
It seems like the quest for opening hours (maybe also other ones) is ignoring the disused tag for shops.

Example: https://www.openstreetmap.org/note/1381967#map=18/50.73701/7.10388

**Comment by westnordost** [comment] 2018-05-03 22:07
Hmm, shouldn't it be `shop=vacant` then? I thought `disused` is for railways and stuff like that.

**Comment by bbastin** [comment] 2018-05-03 22:42
I wasn't sure so I did the research. According to the wiki:

> Use the disused: lifecycle prefix on tags that relate to features that are in a reasonable state of repair but which are currently unused. Examples include vacant or boarded-up dusty shop buildings or unused parking lots. [1](https://wiki.openstreetmap.org/wiki/Key:disused)

It seems that vacant is an alternative, though the wiki states that some mappers advice against it. [2](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dvacant)

So I guess the best way right now would be to support both alternatives, though I tend towards disused as it seems more versatile and widespread.

This probably should also apply to quests like vegetarian or vegan food, accessibility and probably a whole bunch more not connected to shops at all; I'll keep my eyes open :-)

**Comment by padan** [comment] 2018-05-06 13:28
Yes, I am using the disused: lifecycle tag for temporarily closed restaurants too, another example with disused:amenity:

https://www.openstreetmap.org/node/3665738131

This one already has opening_hours attached, so StreetComplete doesn't ask.

**Comment by westnordost** [comment] 2018-05-06 14:00
Hmm, actually, I looked at taginfo, taginfo just lists 210 elements worldwide with `shop=disused` (as opposed to 14882 for `shop=vacant`). 

`disused:shop=*` is something else because it does not use `shop` as the key.

**Comment by matkoniecz** [comment] 2018-05-06 14:07
From looking at https://www.openstreetmap.org/note/1381967#map=18/50.73701/7.10388 and https://www.openstreetmap.org/node/1319475752/history it seems that opening hours query matched disused:shop=florist or solved quest that was downloaded over 5 moths age.

https://www.openstreetmap.org/node/1319475752/history was never tagged shop=disused

**Comment by padan** [comment] 2018-05-06 14:10
Both examples (from the submitter and mine) are about prefixed disused:shop=* key, not about shop=*. Will StreetComplete display quests for key "disused:shop", or for key "shop"? If quests are displayed for shop=* and amenity=* only, but not for disused:shop=* and not for disused:amenity=* this rather like looks a missing feature (adding disused: lifecycle prefix to unused entities where quests cannot be answered) than a bug.

**Comment by westnordost** [comment] 2018-05-06 14:25
Hmm, actually, if @bbastin would have attempted to answer the question with something, his answer would have been dropped due to that
1. a version conflict arises on upload
2. on automatically resolving the conflict, the app notices that the quest does not apply to the element anymore (since there is no `shop` key)

Leaving notes is independent of that. I **could** implement that on leaving a note, the app always first checks if the quest still applies to this element and **drop the note otherwise**. But I am not sure if this would be a good idea.

**Comment by matkoniecz** [comment] 2018-05-06 14:49
Maybe drop note if both

- conflict appears
- quest was based on data downloaded long time ago (over 1 month?)

notes about data changed months ago are confusing and are less likely to be useful

**Comment by westnordost** [comment] 2018-05-06 15:00
Then maybe it would be better to instead automatically drop quests (not just invalidate) that were downloaded more that X months ago (even solved ones?).
There might even be a ticket for that here somewhere.

**Comment by matkoniecz** [comment] 2018-05-06 15:15
>  There might even be a ticket for that here somewhere.

In #766 I proposed to silently delete quests older than 1 month.

**Comment by westnordost** [comment] 2018-05-06 15:16
Jo, that's it. So I will close this issue because this here would be not or very much less of an issue if #766 was implemented.

**Closed by westnordost** 2018-05-06 15:16 UTC
Labels: feedback required

**Comment by matkoniecz** [comment] 2018-05-28 10:37
The problem is that deleting shop is gone is tricky.

Sometimes entire node/way/relation should be deleted (shop in a mall), sometimes only shop tag should be deleted (shop tagged on outline of a building), sometimes shop tag and some additional tags like opening_hours should be deleted.

Sometimes address tags should be deleted (shop duplicates stress for a building), sometimes address tags should be not deleted (shop on sole adress node for a building).

Sometimes both shop and building should be deleted (demolished kiosk).

Etc etc

I planned to implement this to eliminate spamming several "this does not exists" notes on each walk but I discarded this idea due to significant complexity of the issue.
