### ISSUE TITLE
improve multiple quest answer

### ISSUE THREAD

**Issue by Jibec** [westnordost/StreetComplete#1303] opened 2018-12-28 20:10 UTC
Hello, 

I've read other issues about multiple quest, without finding the place to discuss this.

Here is my example:
![screenshot_20181228-195042](https://user-images.githubusercontent.com/474883/50524974-72b69b00-0ae1-11e9-95e5-ad6fd6d9c66d.png)

While I notice many appreciable improvements in the application over time, it still make me loose a lot of time to select again and again the same answer to multiple side by side objects.

As you created a button for buildings levels, that's remember last value, I'm wondering if we can have something similar to either say:

* say OK with this value and apply it to the next quest (can be repeated multiple times)
* select other quests with the same answers

Thanks for this great application

**Comment by rugk** [comment] 2018-12-30 12:37
Duplicate of https://github.com/westnordost/StreetComplete/issues/73 (?)

**Comment by Jibec** [comment] 2019-01-02 10:00
Well, for multiples quests, according how the neighborhood was built or the OSM objects are structured, you just turn our to validate multiple times the same value.

Maybe a generic "Repeat" button would solve the issue (only displayed if the quest is the same as before), with automatic validation, and a short popup writing 'previous responses repeated with the following value : %%%".

**Comment by westnordost** [comment] 2019-01-06 15:17
I'd rather not have this in the app. I can understand that this would be more convenient, absolutely. But, while important, user convenience is not the only factor that I need to keep in mind here. Better convenience is good as long as it does not possibly affect the quality of the collected data negatively.

With a repeat button that does not even show the quest form, I think that there is definitely that possibility (as noted in a previous comment). A repeat button within the form practically exists already for image selection quests such as the building type quest because the last selected values are sorted up in the list.

(Also, a comment on the technical side: You suggest to show a popup that notes the last chosen value. To show not the OSM tag but a picture+test for every quest type there is is not trivial, because there is no generic mapping from OSM tags to human-readable text+picture in the app, only the other way round)

**Closed by westnordost** 2019-01-06 15:17 UTC

**Comment by ludwigbald** [comment] 2020-12-09 00:26
Maybe this should be reopened.

We can save precious interactions here, without sacrificing data quality.
Since we already put the last value at the top, why not (instead or additionally) preselect it, so all the user has to do is click "ok"? Reordering the list without explaining the new order means the user has to reorient themselves, which might actually take longer.
