### ISSUE TITLE
Request: is this feature still under construction?

### ISSUE THREAD

**Issue by gappleto97** [westnordost/StreetComplete#685] opened 2017-11-10 18:12 UTC
It should be pretty easy to do. If `building=construction` or `highway=construction`, and `construction=*`.

When the user says its finished, take the content of construction, put it to building or highway, then remove construction.

**Comment by matkoniecz** [comment] 2017-11-11 15:09
On creating new issue it is prefilled with text including

> If you are not suggesting a new quest, ignore this issue template. Otherwise we kindly ask you to fill it out.

It has checklist including

> Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)

> When the user says its finished

And when the user says it is not finished what is supposed to happen?

**Comment by gappleto97** [comment] 2017-11-12 16:01
Check_date could be updated, and a condition added so that it does not appear if check_date is less than a week ago. 

Also, sorry for not filling out the template, but it did not appear on FastHub, where I filed this.

**Comment by westnordost** [comment] 2017-11-12 18:24
So far, I have been avoiding check_date and the like. See #657 

Is there perhaps a key for construction sites that record the estimated date of completion? The app could ask for that (Is this building construction completed? -> No -> When should it be completed (earliest)?), then put it into the DB and check only those quests whose ETA date has been reached already.

**Comment by rugk** [comment] 2017-11-12 19:46
[`opening_date`](https://wiki.openstreetmap.org/wiki/Key:opening_date)

**Comment by gappleto97** [comment] 2017-11-14 06:54
That seems like a reasonable compromise

**Comment by westnordost** [comment] 2017-11-14 08:35
The problem is that the wiki defines this tag as the finished date, not as "probably done then, at least not earlier than that". But this is how the app will have to ask this:
"it's not done yet" -> "Please input the date when it should be checked again / estimate when it will done"

Redefining the meaning of existing tags is quite problematic.

So if this tag is used, the question must be "When will it be done?" - with an answer option of "I don't know / can only estimate". And then, the question is, what to do tag then?

Perhaps we could also ask in the wiki discussion if it would still fall under the Def of this tag to specify an ETA instead of a 100% correct date.

Am 14. November 2017 07:54:23 MEZ schrieb Gabe Appleton <notifications@github.com>:
>That seems like a reasonable compromise
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/685#issuecomment-344163281

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by westnordost** [comment] 2017-11-14 09:24
Do you understand what I meant?

**Comment by gappleto97** [comment] 2017-11-14 15:49
I feel like this is going to be an acceptable use of check_date, but I'll forward this issue on to the tagging list when I get to a computer.

**Comment by rugk** [comment] 2017-11-14 17:52
Yeah, but the wiki also says:
> It is recommended to additionally add check_date=*, which describes the date in the past, when the value of opening_date=* was actually checked.

So here this "check_date" is actually recommend (maybe it is the only real use/originally intended use of this tag). So combine these tags, and you may get a "we checked at XY, it may be finished at XZ"…

**Comment by PanierAvide** [comment] 2017-11-15 07:15
You should consider instead `survey:date`, which is already used by some applications like Geocropping, and soon in OSM Contributor/Jungle Bus. It is used ~390000 times already in OSM.

**Comment by gappleto97** [comment] 2017-12-29 09:20
I asked for feedback on the tagging list some time ago, and received none. I think that the best bet would be to use survey:date and have a timeout of two weeks between asking.

**Comment by westnordost** [comment] 2018-01-09 21:04
Ah yes, I read it right now. Well, I would not take a non-reply as a free ticket to use that. There are other things to do for me right now, so I'd postpone involving myself in this now.

**Comment by matkoniecz** [comment] 2018-01-30 08:16
> You should consider survey:date, which is already used by some applications like Geocropping, and soon in OSM Contributor/Jungle Bus. It is used ~390000 times already in OSM

Note that this usage numbers are useless as it was added by import to Antarctica shoreline - see https://taginfo.openstreetmap.org/keys/survey%3Adate#map

![selection_009](https://user-images.githubusercontent.com/899988/35555004-03abc99a-059e-11e8-81bd-b4556a73730f.png)

Overall, https://taginfo.openstreetmap.org/keys/survey%3Adate#overview and https://taginfo.openstreetmap.org/keys/check_date#overview seem to be used on similar scale after discounting imports and check_date seems to be nicer tag value (without :, easier to remember) and is recommended by https://wiki.openstreetmap.org/wiki/Key:construction so I would use rather `check_date`.

**Comment by matkoniecz** [comment] 2018-01-30 08:17
Also, maybe allow to tag opening_date? Some long-term projects have information signs about planned construction end.

**Comment by althio** [comment] 2018-01-30 08:58
> @matkoniecz maybe allow to tag opening_date? Some long-term projects have information signs about planned construction end.

`start_date` is much more used than `opening_date`. Is there any significant differences in meaning?

**Comment by matkoniecz** [comment] 2018-01-30 09:10
Yes.

See https://wiki.openstreetmap.org/wiki/Key:start_date and https://wiki.openstreetmap.org/wiki/Key:opening_date

> An approximated date in the future when a construction will be finished

and

> start_date=* can be used to indicate the date the feature opened or construction of the feature finished (i.e. started to exist as feature).

**Comment by matkoniecz** [comment] 2018-02-06 08:40
I prepared overpass query that

- fetches highway=construction with construction tag
- throws away recently edited (including edits that added/updated check_date or equivalent)
- throws away entries with opening_date in future

http://overpass-turbo.eu/s/vT3

**Comment by matkoniecz** [comment] 2018-02-06 08:42
BTW, I think that it would be a good idea to support highway=construction without construction tag. Such entries after finished construction may be tagged as highway=road - there is no loss of data and fact that construction is finished is marked, and I think that no sensible router/other data consumer will not route through highway=road anyway.

Also, I think that people are more likely to fix highway=road that highway=construction without construction tag.

**Comment by rugk** [comment] 2018-02-06 13:15
Ah, thanks for the http://overpass-turbo.eu link, BTW. This makes it easier to add the link to the wiki, when this quest may be merged.

**Comment by matkoniecz** [comment] 2018-02-06 16:51
Note to self: construction values must include some defined list to avoid problems with things like [highway=construction, construction=parking-aisle]

**Comment by matkoniecz** [comment] 2018-02-10 07:51
I updated overpass query with futureproofing syntax and adding date validity check thanks to https://gis.stackexchange.com/questions/270491/use-current-date-in-overpass-turbo-querries/270492?noredirect=1#comment430999_270492

query: http://overpass-turbo.eu/s/w4c

- fetches highway=construction with construction tag
- throws away recently edited (including edits that added/updated check_date or equivalent)
- throws away entries with opening_date in future (invalid opening_date entries are ignored)

Note: construction values in a real quest must include some defined list to avoid problems with things like [highway=construction, construction=parking-aisle]. (so ways without construction tag may be added as highway=road, with valid construction tag as highway=<value of construction tag> and others should be ignored).

Note: objects with opening_date in past but recently edited are ignored by this query.

**Comment by matkoniecz** [comment] 2018-02-10 08:04
We should exclude also highway=construction with access tags, as it is unclear whatever say vehicle=no or bicycle=no or foot=no applies temporarily to road under construction or is it generally true.

But maybe in this case we can add fixme with note that road is completed but meaning of access tags in unclear?

**Comment by matkoniecz** [comment] 2018-02-10 08:30
@westnordost Can you consider making icon for this quest?

**Comment by ENT8R** [comment] 2018-02-10 08:51
What about this?
![crane-5](https://user-images.githubusercontent.com/25306497/36060342-fbdc8ac6-0e47-11e8-9a19-3b3bfbfa02e8.png)

**Comment by matkoniecz** [comment] 2018-02-10 09:25
Works quite well, though cranes are rather unusual for road construction (except bridge construction).

Is it already available as icon (what is its name?) or is it a new one (can you make a PR adding it?)?

**Comment by westnordost** [comment] 2018-02-10 14:51
@ENT8R If it is a road construction, the background should be yellow or otherwise grey. Did you create this yourself or did you copy it from somewhere?
If you just copied it, I would rather prefer something along the lines of https://emojipedia.org/construction-sign/ or https://cdn4.iconfinder.com/data/icons/under-construction-1/512/under-512.png because it is a simpler icon that can be used for any construction.

**Comment by matkoniecz** [comment] 2018-02-10 17:06
https://github.com/matkoniecz/Zazolc/commit/1ff1cbe37b1c42f92c3e6fd95d2745bccf7ec72c is what I plan to submit as PR after review + additional testing.

Any comments are welcomed now.

**Comment by ENT8R** [comment] 2018-02-10 22:18
@westnordost should I create the icon or do you want to do that?

**Comment by westnordost** [comment] 2018-02-11 01:15
Mh, I can

**Comment by rugk** [comment] 2018-02-11 13:00
@matkoniecz As for the diff you linked (BTW, you can always already submit such things when there is still work in progress, commenting on Pull Requests is far nicer.), I'd say don't ask "Is construction of […] completed?". First I'd say "Is _the_ construction … completed" and secondly I am not sure whether "completed" is the best term here (maybe "finished"?). But, generally, why not just ask "Is … still under construction?"? That sounds far better.
And I doubt you need to overwrite `getDefaultDisabledMessage` to return `0`. That is already the default. Same with `getEnabledForCountries`?

**Comment by rugk** [comment] 2018-02-11 13:04
Also the PR is limited to roads and so on… But the quest may be useful for much more things like shops or so.

**Comment by ENT8R** [comment] 2018-02-11 13:08
> And I doubt you need to overwrite getDefaultDisabledMessage to return 0. That is already the default. Same with getEnabledForCountries?

If he is not extending the `SimpleOverpassQuestType` he has to add those methods...

**Comment by matkoniecz** [comment] 2018-02-11 15:41
> But the quest may be useful for much more things like shops or so.

I looked through taginfo and I found https://taginfo.openstreetmap.org/tags/building=construction and https://taginfo.openstreetmap.org/tags/railway=construction as other candidates for quest of this type. 

Is there any other relatively popular construction tag worth supporting (so not construction=yes that is horrible tagging scheme that should be ignored)?

> "Is … still under construction?"? That sounds far better.

Sounds like a good idea

> why not 

I am not a native speaker and my English is far from perfect so such comments are welcomed :)

**Comment by gappleto97** [comment] 2018-02-12 05:30
@matkoniecz, your English reads fine to me there.

Also, building construction is one of the things I originally openned this ticket for, so itd be nice to see that covered too. Super useful in my area, since there's a dozen or so buildings under construction right now.

**Comment by rugk** [comment] 2018-02-12 07:33
Generally why limit it to the type if construction anyway? This question can be asked for every construction.

**Comment by rugk** [comment] 2018-02-12 07:33
Generally why limit it to the type if construction anyway? This question can be asked for every construction.

**Comment by rugk** [comment] 2018-02-12 07:34
Generally why limit it to the type if construction anyway? This question can be asked for every construction.

**Comment by rugk** [comment] 2018-02-12 07:35
Generally why limit it to the type if construction anyway? This question can be asked for every construction.

**Comment by gappleto97** [comment] 2018-02-12 07:42
Because there could be some sort of weirdness. You might have a system where for known `*=construction` tags it does the correct things, and for unknown variants it leaves a fixme tag.

**Comment by gappleto97** [comment] 2018-02-12 07:42
Because there could be some sort of weirdness. You might have a system where for known `*=construction` tags it does the correct things, and for unknown variants it leaves a fixme tag.

**Comment by matkoniecz** [comment] 2018-02-24 14:31
@westnordost Would you prefer to support both railway=construction and highway=construction or only highway=construction for #685?

I am asking as it depends on how I should proceed with #859

**Comment by westnordost** [comment] 2018-02-24 14:43
Only highway is fine.

**Comment by gappleto97** [comment] 2018-02-25 01:49
To be clear, does that mean we arent doing it for buildings, and only roads?

**Comment by matkoniecz** [comment] 2018-02-25 06:42
Currently I have implementation ( https://github.com/westnordost/StreetComplete/compare/master...matkoniecz:construction_PR?expand=1 ) for buildings and highways with easy adding of new subquests.

I prefer to test what I have before opening a PR.

**Comment by matkoniecz** [comment] 2018-02-25 13:06
> "Is … still under construction?"? That sounds far better.

Unfortunately it fails in cases where construction stopped or was abandoned, I need to find a better one.

**Closed** 2018-04-09 21:57 UTC
Labels: new quest
