### ISSUE TITLE
Quests disappear after some time 

### ISSUE THREAD

**Issue by cperrier** [westnordost/StreetComplete#1698] opened 2020-01-12 15:40 UTC
**How to Reproduce**

**Versions affected**

After some time using the app, all quests domeyime disappear . none is shown. 

it generally happens after completing a quest : all other icons disappear from the screen and no quest can be looked for. requesting more quests doesn't help.

most often quests reappear after a random time (sometimes over 15 minutes). it's indeed very frustrating as nothing can be done until quests reappear more or less magically

**Comment by HolgerJeromin** [comment] 2020-01-13 21:19
Had this two days (saturday) ago after splitting a way, too.

**Comment by Biepa** [comment] 2020-01-14 16:34
I can confirm this.
Also after scanning there is nothing show and I have to restart the app to see all the icons.
Android 9 with app from fdroid

**Comment by westnordost** [comment] 2020-01-14 20:01
hmm I thought there is already a bug for that. I am working on this, I will redo the complete part of the app that concerns itself with the map. One part of it is to rework the quest pin display.

**Comment by matkoniecz** [comment] 2020-01-15 14:36
#1675 (and its earlier version, seemingly fixed #1415)  are very similar or maybe even exactly the same.

**Comment by cperrier** [comment] 2020-01-16 18:38
#1675 is about losing map's pin after locking the phone which is slightly different from the bug I experienced. What I had (which doesn't happen anymore!) is that after some time fixing quests, all pins suddenly disappeared everywhere on the map after completing one. And then, no action was able to make them reappear.....for some time (about 15 minutes or so, or even more). Then suddenly they reappeared for a while....then disappeared again after some more work.

It actually happened 4 days ago and, since then, I can't reproduce the bug : indeed StreetComplete is now working really well and I completed many man,y quests in my area. So, indeed that seems to be one of those weird bugs that happen "randomly" (indeed not....but without any clue about the conditions that trigger the bug). Dunno what to do with that as, well, I can't reproduce the problem anymore;..:-)

**Comment by cperrier** [comment] 2020-01-16 18:40
@westnordost : so feel free to close this bug report if you feel like it's not really useful to you, in the future (or if you rewrite the pin display code), I won't be annoyed by this (as FLOSS contributor in the past, I know about the pain of having tons of bugs you have no idea how to reproduce them).

**Comment by westnordost** [comment] 2020-01-24 13:27
So, this should be fixed for the next version

**Comment by HolgerJeromin** [comment] 2020-02-05 15:45
Not solved in v17!

**Comment by westnordost** [comment] 2020-02-05 16:49
Okay, can you tell more about how to reproduce it?

**Comment by smichel17** [comment] 2020-02-06 12:41
Since this bug is vague, I can't be sure it is the same. However, I have repro on disappearing quests.

**Steps:**

- Open SC
- Press the back button until SC "closes" (return to home screen)
- Reopen SC (via launcher or app switcher)

**Expected:** SC reopens as normal

**Actual:** SC reopens with map showing, but no quests

**Workaround:** Open the app switcher and swipe SC away to close it fully, then reopen

**Comment by westnordost** [comment] 2020-02-09 22:47
Can reproduce! Thanks!

**Comment by natrius** [comment] 2020-02-25 08:07
FYI: Same problem, Xiaomi Mi 9 with Android 10, Streetcomplete F-Droid 17.0

Solved around 1.7k Quests these days and its really annoying. Open App, nothing shows, scan quests, nothing shows up, closing, opening, nothing changes. 
I will try if i can reproduce the workaround @smichel17 told us. From memory, it works not all the time, but i will try it.

**Comment by westnordost** [comment] 2020-02-25 11:25
Hm actually, I solved the bug @smichel17 reported and forgot to close this bug

**Comment by westnordost** [comment] 2020-02-25 11:26
Ah, but I fixed it in 17.1 and you use 17.0. So there we have it, you should update.

**Closed by westnordost** 2020-02-25 11:26 UTC
Labels: bug
