### ISSUE TITLE
Overview of all types of quests

### ISSUE THREAD

**Issue by PanderMusubi** [westnordost/StreetComplete#607] opened 2017-09-25 09:13 UTC
Please add an overview of all current quest types. This could be generated in a file in MarkDown format for GitHub, and/of in a generated wikipage on GitHub ( https://github.com/westnordost/StreetComplete/wiki ) and/or in the app available in the menu. the overview wold simply consist of the icon of a quest and the name or a short description of the quest. Perhaps even a date or version number from when this quest was made available. This would serve as a legend and as a sort of changelog for users.

**Comment by rugk** [comment] 2017-09-25 10:18
Basically what you ask for is already done in [the wiki](https://wiki.openstreetmap.org/wiki/StreetComplete/Quests). See https://github.com/westnordost/StreetComplete/issues/477 for previous discussion. (and if have comments, comment there or on the discussion page in the wiki)

Also see https://github.com/westnordost/StreetComplete/issues/142, but this is about the actual quests, not the quest *types*.

**Comment by PanderMusubi** [comment] 2017-09-25 10:25
Super! Than the issue would be to add that URL to the README.md, to https://github.com/westnordost/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete and perhaps also to the app.

**Comment by westnordost** [comment] 2017-09-25 13:07
Duplicate of/solved with #34

**Closed by westnordost** 2017-09-25 13:07 UTC

**Comment by rugk** [comment] 2017-09-25 13:09
No certainly not #34, but #477.

**Comment by westnordost** [comment] 2017-09-25 13:10
Whoops I meant #35

On 25 September 2017 16:09:28 EEST, rugk <notifications@github.com> wrote:
>No certainly not #34, but #477.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/607#issuecomment-331875622

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by rugk** [comment] 2017-09-25 13:11
Oh yeah, https://github.com/westnordost/StreetComplete/issues/35 has some connections to this issue too. That would have an in-app list of quest types.

**Comment by rugk** [comment] 2017-09-29 19:07
Finally the wiki page is complete. Sent a PR for adding a link: https://github.com/westnordost/StreetComplete/issues/194
