### ISSUE TITLE
GPS button vanishes

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#1896] opened 2020-06-13 06:20 UTC
Hi there,

yesterday I updated to v20.1 (previous version was v18.0) and used it the first time while riding my bike through a part of my home town I rarely visit. This version was hardly useable because the GPS button was almost never visible! See for example this screenshot:
![gps-button](https://user-images.githubusercontent.com/32601012/84561567-c48ec780-ad4d-11ea-9f35-4baf7ab97eb5.png)

I was able to make the button visible again for about one second (!) by sending the app to the background and back to the foreground, then I had to hurry to press it until it vanished again. This behaviour was reproducible and of course very annoying. Did I miss something or is this a bug (perhaps with my old Android version)?

(StreetComplete v20.1 on Android 5.1)

The cycling cat

**Comment by HolgerJeromin** [comment] 2020-06-13 06:45
This is not a bug, but a feature:
#1843

**Comment by cyclingcat** [comment] 2020-06-13 07:27
Hm... so whenever I pan the map in order to see some surrounding items I don't have the chance to bring my position back to the screen center if my position is still visible on the map? (If my current position is outside of the visible map, I have at least the possibility to tap on the location pin which is always on different positions though so I have to search it first on the screen.)

Yesterday I had to pan the map manually VERY often! Issue https://github.com/westnordost/StreetComplete/issues/636 makes it even worse for me, especially if I ride towards western or eastern directions, because I have to use StreetComplete always in "north on top" mode to circumvent the aforementioned issue. (My phone is mounted at the handlebar or the stem, always in portrait position.)

So at least for me the missing location button is an enormous decrease in useability. I will give it a second try today, but I fear that I will decide to revert to v18.0 this evening.

(A suggestion: Give the user the choice in the settings if he wants to see this button or not. You can leave the default to the current behaviour, of course.)

The cycling cat

**Comment by westnordost** [comment] 2020-06-13 09:42
You can tap on your position on the map

Am 13. Juni 2020 09:27:14 MESZ schrieb cyclingcat <notifications@github.com>:
>Hm... so whenever I pan the map in order to see some surrounding items
>I don't have the chance to bring my position back to the screen center
>if my position is still visible on the map? (If my current position is
>outside of the visible map, I have at least the possibility to tap on
>the location pin which is always on different positions though so I
>have to search it first on the screen.)
>
>Yesterday I had to pan the map manually VERY often! Issue
>https://github.com/westnordost/StreetComplete/issues/636 makes it even
>worse for me, especially if I ride towards western or eastern
>directions, because I have to use StreetComplete always in "north on
>top" mode to circumvent the aforementioned issue. (My phone is mounted
>at the handlebar or the stem, always in portrait position.)
>
>So at least for me the missing location button is an enormous decrease
>in useability. I will give it a second try today, but I fear that I
>will decide to revert to v18.0 this evening.
>
>(A suggestion: Give the user the choice in the settings if he wants to
>see this button or not. You can leave the default to the current
>behaviour, of course.)
>
>The cycling cat

**Comment by Atrate** [comment] 2020-06-13 12:27
> (A suggestion: Give the user the choice in the settings if he wants to see this button or not. You can leave the default to the current behaviour, of course.)

I'd be very for that, as IMHO the new behaviour is very confusing

**Comment by westnordost** [comment] 2020-06-13 22:34
Well, as said, you can tap on your position on the map to get exactly the behavior you want, @cyclingcat . So, I am closing this.

**Closed by westnordost** 2020-06-13 22:34 UTC
Labels: bug

**Comment by cyclingcat** [comment] 2020-06-14 06:22
I tried it out yesterday: Indeed, this is a mitigation, but still inferior compared to the former clear and easy-to-tap button in the lower right corner, at least IMHO. Now you have to point to the much smaller position indicator very precisely (I often needed 2-3 tries on my 4,5" display) - and in addition to it it's a moving target.

The cycling cat

**Comment by Atrate** [comment] 2020-08-02 20:54
Discussion continued in #1996, @cyclingcat
