### ISSUE TITLE
developer mode: load "profiles" and "custom zone"

### ISSUE THREAD

**Issue by yopaseopor** [westnordost/StreetComplete#132] opened 2017-04-21 21:43 UTC
Hi, at OSM Spanish Community some people we are thinking to develope some mapathon with your fantastic app, because it is an easy way to complete a zone. To do this we think we need some important features:

-Feature to be able to add a profile with keys and values suggested to introduce.So then we can tell people to use this "profile" to do specifics mapathons like accesibility keys and values. To make the things easier in this feature an idea is that  you can able this profile/form a simple asking question with only the key and the values...like a suggestion for Vespucci/JOSM.

-Feature to be able to load some custom zone or custom points to make an intervention in a specific zone with a specific target, people told me examples like about opening hours in specific shops.

**Comment by westnordost** [comment] 2017-04-21 22:11
Hmm I do not understand what exactly you mean with profiles and custom zones.

**Comment by msevilla00** [comment] 2017-04-23 07:33
Hello,

I'm from Spanish OSM Community too and I was thinking to add accessibility tags to streets, pedestrian crossings and related features. 

For example: if there is a pedestrian crossing in OSM [1] it would be great to add if there is a traffic signal [2] and if there is a sound for blind people... or it would be great if add wheelchair tags to shops or business (as it does wheelmap [3]). All thees improvements to the add it would be great to helps us in the fieldwork/streets. 

[1] https://wiki.openstreetmap.org/wiki/Key:crossing
[2] https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtraffic_signals
[3] https://wheelmap.org/map

If you add an other "layer" of complexity if could be nice if you can select different levels of work withing the app.

I hope you can understand better our ideas for your great app.

Cheers

**Comment by westnordost** [comment] 2017-04-23 10:23
Hey Miguel, please add an own ticket for each different quest suggestion.

**Comment by yopaseopor** [comment] 2017-04-23 17:09
I think it is the "same issue".
We are talking about the possibility of "load our customs quests or challenges". This is not a feature for the big public, is an advanced feature done by developers to a specific audience.

For the first feature: 

-Imagine I want to do an accesibility mapathon. My interest is that Streetcomplete searches in the zone of the mapathon some specific quests with the keys crossing, traffic_signals and wheelmap (and the three o four most common values for these keys in the zone of the mapathon) . I know it is hard to do every quest organizers of a specific mapathon wish so the idea is this "quest" would be prepared by the mapathon organizers and loaded to StreetComplete by the mappers of the mapathon (like a customized "level"). This behaviour is similar like some JOSM custom presets.

For the second feature:

-Imagine I work as a volunteer for an shop association . They want to put all the opening hours in their shops of their brand. If they were using "normal" Streetcomplete quest, shops of other brands will spot inside their job, making the use of Streetcomplete an inadequate thing. But if a person can "load" specific nodes and then Streetcomplete suggest the desired keys and possibilities to add the values Streetcomplete would be a swiss knife tool to these mappers.

**Comment by matkoniecz** [comment] 2017-04-26 05:59
It sounds like duplicate of #98

**Comment by matkoniecz** [comment] 2017-04-26 06:00
Overall if a quest is a good idea it probably may be added to the main app (though properly preparing it may require significant effort).

**Comment by msevilla00** [comment] 2017-04-26 10:49
Great! We will prepare some quest to improve the app accordingly through separate issues.

**Comment by westnordost** [comment] 2017-04-26 11:36
@matkoniecz : This is absolutely my opinion :-)

@msvilla00 brought up some nice possible quest types as an example for "plugins" to make sense. But actually, they also make sense to be added generally to the app, no need to hide this in a plugin.

Anyhow, perhaps such plugins will make sense in the future for very localized/specialized things to map, but this is - for me - very low priority right now (just to give you a heads up). @matkoniecz is right, this is basically the same as #98, so I will close this one as duplicate. You can continue discussion there.

**Closed by westnordost** 2017-04-26 11:36 UTC
