### ISSUE TITLE
House numbers are missing on the map since v21.0!

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#1939] opened 2020-07-06 11:43 UTC
Hi there,

today the new version 21.0 came in through F-Droid and since this update the house numbers are missing on the map for nearly every house. Occasionally a house number is visible but 99% of them are not. This makes it difficult in some situations to determine which way/node a quest is actually referring to (for example if you're standing in front of a row of similar looking houses and your sat reception is bad).

I get this behaviour on two phones (Android 5.1 and 9.0). SC v21.0 from F-Droid.

The cycling cat

**Comment by westnordost** [comment] 2020-07-06 11:47
Duplicate of https://github.com/ENT8R/streetcomplete-mapstyle/issues/82

**Closed by westnordost** 2020-07-06 11:47 UTC
Labels: bug
