### ISSUE TITLE
Unable to reach the authorization server

### ISSUE THREAD

**Issue by Quix0r** [westnordost/StreetComplete#2282] opened 2020-11-15 14:57 UTC
Related to #44 as the change from external browser (Firefox did work) to web view caused this.

Android 4.1 (old, I know)
SC 26.1 from F-Droid

If you need more storage for images, let me know. :-) I have some spare GBs left.

**Comment by westnordost** [comment] 2020-11-15 15:16
duplicate of #2258

**Closed by westnordost** 2020-11-15 15:16 UTC
Labels: bug

**Comment by Quix0r** [comment] 2020-11-15 15:48
I was not seeing it anymore and forgot I posted it.
