### ISSUE TITLE
[New quest] Car parking capacity

### ISSUE THREAD

**Issue by margin-auto** [westnordost/StreetComplete#1748] opened 2020-03-01 07:57 UTC
### General
Affected tag(s) to be modified/added: [capacity](https://wiki.openstreetmap.org/wiki/Key:capacity:)
Question asked: **How many cars can be parked here?**
Additional questions could be: **How many parking spaces are reserved for women/disabled people/parents?**

Beside the existing quests for bike and motorcycle parking capacities, Car parking capacities should  also be a quest, because in many examples they can't be spotted clearly from background satellite images (trees, shadows, covered or multi-level amenities) and on-the-ground survey is needed. For reserved spaces for women etc. on-the-ground survey is needed anyway.

### Checklist
Checklist for quest suggestions (see guidelines):
- [ ] 🚧 To be added tag is established and has a useful purpose
- [ ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ ] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [ ] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [ ] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation/GUI
Based on the existing quests for bike and motorcycle parking capacities.

**Comment by HolgerJeromin** [comment] 2020-03-01 10:33
I dont want to count capacity for car parkings with more than 20 cars even for surface parking. Counting multi storage is even more difficult to count.

**Comment by Atrate** [comment] 2020-03-01 11:27
Could be applied only for parkings with an area less than X because IMHO it's more useful to know the capacity of little parking lits than of gigantic ones

**Comment by margin-auto** [comment] 2020-03-01 13:09
> I dont want to count capacity for car parkings with more than 20 cars even for surface parking. Counting multi storage is even more difficult.

Well, no one said that mapping would be easy ;-) Of course it's up to every one what he/she maps and how much effort is put into OSM. And I know many bike parking amenities for more than 20 bikes, which are not easier to count but anyway covered by a quest in StreetComplete.

**Comment by margin-auto** [comment] 2020-03-01 13:10
> Could be applied only for parkings with an area less than X because IMHO it's more useful to know the capacity of little parking lits than of gigantic ones

Could be an approach. But what about nodes?

**Comment by margin-auto** [comment] 2020-03-01 13:12
In addition here some examples of areal images in JOSM from some parking amenities. The quality of the images is quite good but I wouldn't rely on them for counting parking spaces.
![Bildschirmfoto von 2020-03-01 13-15-20](https://user-images.githubusercontent.com/17515478/75626295-ab12a700-5bc6-11ea-8f10-8acad11be0d1.png)
![Bildschirmfoto von 2020-03-01 13-15-58](https://user-images.githubusercontent.com/17515478/75626296-ad750100-5bc6-11ea-919f-f70018978531.png)

**Comment by westnordost** [comment] 2020-03-01 13:53
I see, the screenshots show that even with high-resolution imagery, the capacity can sometimes only be estimated.
Though, this partly holds true for a survey as well. In your last screenshot, there seem to be no markings for the northwestern part of the parking lot. So even if you survey there, you can only estimate that there is space for more or less 5 cars there, if they park properly. The same applies in a larger scale to informal parking lots - just some areas that are used as car parks, with no markings at all.

![image](https://user-images.githubusercontent.com/4661658/75626895-a56b9000-5bcb-11ea-8266-a4367c393047.png)

Speaking of estimation, and @Atrate mentioned that only smaller car parks could be considered, there is another way the capacity of a parking lot can be estimated: By size. 
In the light of that the capacity by survey is also often just an estimation, the information value for a capacity collected on a survey is really low, because it seldomly deviates substantially from the estimation based on the size of the parking while on the other hand being an unreasonable undertaking for cases like in the screenshot I showed.

**Comment by westnordost** [comment] 2020-03-24 18:29
Closing because of no feedback / no arguments brought forth.

**Comment by peternewman** [comment] 2020-04-10 11:49
@westnordost , something that occurred to me (well I noticed during government approved exercise), there is another way to answer this quest, in the UK at least. The signage often either shows the total capacity, see the sign at an angle on the right here:
https://www.thenorthernecho.co.uk/resources/images/3683976.jpg

Or perhaps more controversially it would show a minimum capacity, which could be added and flagged in some way (for example we know Park Street has at least 191 spaces):
https://i2-prod.cambridge-news.co.uk/incoming/article12276811.ece/ALTERNATES/s615b/Car-parks.jpg

I don't know if OSM has any sensible way to tag the latter currently, I suspect not unfortunately. But the former could still be useful data gathering, otherwise there is no choice but to add a note to the map and update it retrospectively.

Personally I find that far less ambiguous than tagging cycling capacity; does a stand or bollard have the capacity for one bike total, or one either side, or more?

**Comment by westnordost** [comment] 2020-04-10 11:58
> The signage often [...] shows the total capacity [...]

Well, the problem is with the word "often". What to tag in cases where it is not signed?
At least where I live, I never saw the capacity printed on the sign, so it must be a UK thing, or perhaps even only a thing in the region or city you live in.

**Comment by peternewman** [comment] 2020-04-10 12:18
> > The signage often [...] shows the total capacity [...]
> 
> Well, the problem is with the word "often". What to tag in cases where it is not signed?

Can't say, like is offered for a number of other quests?

> At least where I live, I never saw the capacity printed on the sign, so it must be a UK thing, or perhaps even only a thing in the region or city you live in.

That photo is stolen from somewhere in the North of England and I'm in the South on the outskirts of London, but agreed, perhaps it's a country based thing. As mentioned, the cycling thing seems more ambiguous to me, but that's been merged, what does that offer when you can't tell?

**Closed** 2020-04-20 15:57 UTC
Labels: feedback required
