### ISSUE TITLE
Roof shape and height for garage and multiple garages

### ISSUE THREAD

**Issue by arne182** [westnordost/StreetComplete#1955] opened 2020-07-14 10:04 UTC
Some garages have a roof so levels and roof shape would be useful to include in the quest as well.

**Comment by matkoniecz** [comment] 2020-07-14 10:09
Sounds like #1929

**Comment by HolgerJeromin** [comment] 2020-07-14 10:11
> Not an overwhelming percentage of elements have the same answer (No spam)

At least in Germany the quest would be >99% flat roof.

IMO related but not a clear dupe of 1929

**Comment by matkoniecz** [comment] 2020-07-14 10:57
Yes, it is similar to #1929 but about building levels.

@arne182 I know that some very rare garages have more than one level, but still, 99%+ of them will have single roof and one level. Or is it different in your region?

**Comment by arne182** [comment] 2020-07-14 11:47
In my 300 garage town. There are about 300 garages with about  100 flat roof 100 gabled and 100 skilon with about 50 of them having multiple levels

**Comment by westnordost** [comment] 2020-07-14 11:55
Yeah but exceptions can only be made on a nation-wide level, so this'd be a will not fix

**Closed by westnordost** 2020-07-14 11:55 UTC

**Comment by arne182** [comment] 2020-07-14 13:55
How about an option to click on a building and then a roof type and then you could also see which one was applied. The UI does not seem to render the roof types.

**Comment by westnordost** [comment] 2020-07-14 14:47
Yes, the UI does not render the roof types. Nothing I can do about that though, it is the rendering library (tangram-es) that lacks this feature.

**Comment by peternewman** [comment] 2020-07-18 03:28
> In my 300 garage town. There are about 300 garages with about 100 flat roof 100 gabled and 100 skilon with about 50 of them having multiple levels

I'd say the UK is probably similar. Flat roofs often in blocks of garages, but gabled common for individual garages attached to or near to houses.

**Comment by natrius** [comment] 2020-12-04 08:20
What about an option if someone wants to add levels and roof types to garages? I think levels would be good for rendering (osmbuildings renders weird high default garages, there is an issue about that) but still a building:levels=1 is not wrong and it should be possible to tag that. Same with roof:levels=1 if the garage has a gabled or half-hipped roof. As far as i was able to see that, thats in austria quite often the possibility. Now i have to take a lot of pictures so i can tag these tags later at home (same for the colours, but we talked about that :p ).

Anyway, a option would be nice. "Add levels and roof to garage/sheds/... - YES/NO" So you would not need to make regional exceptions and everybody can choose themself. Opt-In maybe.

**Comment by matkoniecz** [comment] 2020-12-04 11:31
> osmbuildings renders weird high default garages

That is clearly an osmbuildings bug, better solved there rather that by adding obvious to millions of garage buildings (over 4 millions are mapped already)

> building:levels=1 is not wrong and it should be possible to tag that

It is possible, but not with SC as it by design excludes pointless questions.

> option

Main problem with options is that increases complexity for users and vastly increases testing complexity. Every option is something that needs to be tested and retested. And if there are multiple options interacting with each other, then every yes/no option doubles testing effort.
