### ISSUE TITLE
Adjust the 6 types of road surface shown in the "quick select" based on usage

### ISSUE THREAD

**Issue by jancborchardt** [westnordost/StreetComplete#1072] opened 2018-05-15 19:25 UTC
If you are in a city with a lot of sett or cobblestone, it can quickly get cumbersome to always need to press "Show more" and then "Paved", and only _then_ the relevant surface every time.

It would be great if the list of these 6 first shown surfaces is adjusted based on how recently you used them. That way if you have an area with a lot of cobblestone you only need to go through the ordeal once, and as soon as you are back on asphalt it's still simple. :)

**Comment by ENT8R** [comment] 2018-05-15 19:36
Related or even a duplicate of #73 and #826

**Comment by rugk** [comment] 2018-05-15 19:38
…but actually a different (and IMHO superior) solution to the ones suggested before, as it is intuitive as the user is unlikely to even notice the change. (and it is no "advanced [edit]" feature)

But, yeah, if done, it may be done for all picture quests like these, of course.

**Comment by jancborchardt** [comment] 2018-05-15 19:41
They are related, but not duplicates, as it was stated that automatic batch editing should not be possible.

My proposal isn't batch editing but just helping with repetitive inputs. (Same could be used for the bike paths, where the recently used ones are sorted up top.)

**Comment by westnordost** [comment] 2018-06-09 00:32
This would open a can of worms though, because basically this kind of "favorite" ordering would be expected to work for any quest with an image-based selection.

**Comment by rugk** [comment] 2018-08-13 06:39
I'd still like that feature though. It's basically like the "Recent Emojis" you have in keyboards and other Emoji pickers. The same principle.

Also there new images (emojis) may actually be added over time. AFAIK all these handle it by just ignoring, 

> forget it after a while?

Not needed IMHO. A simple implementation without forgetting may be enough - unless users really travel a lot. In such a case, maybe justsave everything per country? (as you already determinante this for other cases).

Also an automatic cache purge may be done for old unused items, so they do not waste space if you e.g. was in a country once and then moved away.

**Comment by jancborchardt** [comment] 2018-08-13 09:04
@rugk yep, as I said above too ;)

> Basically it's how emoji pickers on most platforms also work. 😉 

Thanks for reopening @westnordost!

**Comment by westnordost** [comment] 2018-08-16 11:29
Okay, done. (For any quest where there is a selection of images)

**Comment by westnordost** [comment] 2018-08-16 11:31
So the last user's choice is remembered and that item is always placed in the first place (upper left corner). The app remembers the user's choice "forever", there is no reset-logic.

**Closed** 2018-08-16 11:31 UTC

**Comment by rugk** [comment] 2018-08-16 11:50
Ah, so it is only one image (item) per quest, that is remembered?

**Comment by westnordost** [comment] 2018-08-16 12:03
yes

**Comment by jancborchardt** [comment] 2018-08-17 21:27
Thanks a lot @westnordost! :) This will really help with repetitive inputs!
