### ISSUE TITLE
Declutter quests

### ISSUE THREAD

**Issue by ludwigbald** [westnordost/StreetComplete#2358] opened 2020-12-08 23:48 UTC
**Use case**

When I open the app as a new user, I am overwhelmed with quests to solve. I don't know where to start, which does not motivate me.

**Proposed Solution**

I think all of the following would be a good idea independently, but also combined:
- add an option to filter quest types (or categories). Maybe it's really easy for me to do quests of one type, or I'm really motivated to solve one type of quest. I don't want to see all the other quests that only get in the way of the ones I care about. At the very least give me an option to hide specific quest types.
- be more opinionated about which quests have priority. Some quests are just less important than others, so which quests should I tackle first? Hide the less important ones.

**Comment by ludwigbald** [comment] 2020-12-09 00:10
Note that this is different from #2354 :
I propose a way to speed up quest completion of similar quests, #2354 proposes adding context for completing a quest.

**Comment by ludwigbald** [comment] 2020-12-09 00:36
Okay I'm apparently just lazy, all those settings already exist right there in the settings.

But: the defaults are set for maximum clutter. Maybe we should set a filter by default, so new users focus on more important tasks, and then power users can figure out that there are all these other quests available.

**Comment by smichel17** [comment] 2020-12-09 00:42
You may be interested in some of the issues linked from here https://github.com/westnordost/StreetComplete/issues/1914 and also with the [`feature: quest display`](https://github.com/westnordost/StreetComplete/issues?q=is%3Aissue+label%3A%22feature%3A+quest+display%22+) label

**Comment by peternewman** [comment] 2020-12-09 01:57
> But: the defaults are set for maximum clutter. Maybe we should set a filter by default, so new users focus on more important tasks, and then power users can figure out that there are all these other quests available.

Then anyone that wants to answer further quests needs to know how to enable them, whereas the current method means you see the most important/highest priority one on each pin (and in general if zoomed out further), but can answer further quests as they appear.

**Comment by matkoniecz** [comment] 2020-12-09 08:25
Sounds like something related to #1654

See also

> Your actual issue seems to be that you find you are overwhelmed by quest types that are unimportant. It is true, many are unimportant. I plan to do something here to make it easier for users to have only those quest types enabled that are interesting for them.

from https://github.com/westnordost/StreetComplete/issues/2295#issuecomment-729691822

**Comment by westnordost** [comment] 2020-12-09 11:10
Yes, I'd close this as duplicate of #1654 .
However, I am still unsure about what would be the best UX for that, i.e. by what to group quests, how the dialog(s) should look etc. Some input and suggestions are welcome (in #1654)

**Closed by westnordost** 2020-12-09 11:10 UTC
