### ISSUE TITLE
Different buildings sharing same housenumber

### ISSUE THREAD

**Issue by Rexelpitlum** [westnordost/StreetComplete#712] opened 2017-11-28 09:04 UTC
I now repeatedly stumbled upon multiple reopened house number quests that I had already solved before.

When I took a closer look into it, I realized that house numbers without an associated streetname seem to be routinely deleted at certain intervals (at least in the area where I live).

This results in them showing up as quests in StreetComplete again and again and again....

Fast fix: don't show housenumber quests when there is no street already set for this house.

Possible long term fix: Allow also entering the streetname that the house belongs to if it is not set.

**Comment by rugk** [comment] 2017-11-28 09:43
> (at least in the area where I live).

Eh, where is this? (at least the country…)

**Comment by Rexelpitlum** [comment] 2017-11-28 10:27
Germany, Northern Bavaria, "Mittelfranken".




Am 28. November 2017 10:43:59 MEZ schrieb rugk <notifications@github.com>:

**Comment by westnordost** [comment] 2017-11-28 11:00
You'll want to read #205 .

> When I took a closer look into it, I realized that house numbers without an associated streetname seem to be routinely deleted at certain intervals (at least in the area where I live).

Well, whoever individual is doing that, should stop that. You entered valid and valuable data there. The fact that it is incomplete from the perspective of usability for routing is no excuse to delete it. But this is only assuming that someone really is deleting this information over and over. If this is the case, you need to deal with that person (and this report be closed).

Let's  assume that it is a bug in the app, that it is somehow not applying your changes. Can you give a link to a building for which the problem occured?

**Comment by Rexelpitlum** [comment] 2017-11-28 11:39
It*s definitely not an application bug, the changes can be seen in the OSM database.

I had a closer look at the changesets. I noticed that for some buildings streetnames were just added, whereas for others the housenumbers have been deleted instead.

Difference between the two: Deleted ones were buildings that have the same number as neighbouring buildings, as for example on a school or university campus or on a smaller scale several houses around a courtyard sharing the same number.

So this seems to be an general OSM tagging/attribute issue when several buildings with the same housenumber are concerned.
Perhaps there is a way to tag a building as "doesn't have its own number" or something similar?

**Comment by westnordost** [comment] 2017-11-28 11:52
Can you show an example of buildings that have no own housenumber? Do they not have entrances? Or are they not buildings from which it could be expected that they have? Or what?

**Comment by westnordost** [comment] 2017-11-28 12:43
Also, this is probably a duplicate of https://github.com/westnordost/StreetComplete/issues/351#issuecomment-312393221 then

**Comment by Rexelpitlum** [comment] 2017-11-29 06:38
> Can you show an example of buildings that have no own housenumber? Do they not have entrances? Or are they not buildings from which it could be expected that they have? Or what?

Each one is a building which shares its housenumber with other buildings, but is a physically separate entity.

Examples:

https://www.openstreetmap.org/way/264577185
https://www.openstreetmap.org/way/300026755
This residential buildings are located on the same premises as other residential buildings. There are no housenumbers attached to any of the buildings, but instead at a wall or fence bordering the street. Thus they share this number. (Number 8 in the first example, number 49 in the second)
I know of several similar occurences, so this seems to be quite common.

https://www.openstreetmap.org/way/81093316
https://www.openstreetmap.org/way/81093318
These are builduings of the TH Nürnberg, a university. They have both the same housenumber "12" attached to their respective entrances (and share this number with at least one other building in this area).
This is not a closed areal with a single entry, but an open campus with distributed buildings which can each be reached directly from the street.

https://www.openstreetmap.org/way/32520201
This building belongs to a school which consists of several separate buildings but has only one housenumber (11)

**Comment by HolgerJeromin** [comment] 2017-11-29 07:45
Some buildings could be building:part

Willstätter-Gymnasium should have the housenumber on the school outline, too. Than this app would not ask for the number

**Comment by Rexelpitlum** [comment] 2017-11-29 08:14
> Willstätter-Gymnasium should have the housenumber on the school outline, too. Than this app would not ask for the number

I am trying that, just added the housenumber there. Is there a way to get Streetcomplete to reload quests to test if this is working?

> Some buildings could be building:part
I don't quite understand that suggestion.
Building:part seems to be a way to indicate that certain parts of the same building have different attributes.
But I am having the exact opposite issue: Different buildings sharing the same attribute.

**Comment by HolgerJeromin** [comment] 2017-11-29 09:14
> Is there a way to get Streetcomplete to reload quests to test if this is working?

Not now #706

> I don't quite understand that suggestion.
>Building:part seems to be a way to indicate that certain parts of the same building have different attributes.
> But I am having the exact opposite issue: Different buildings sharing the same attribute.

The current ways could be building:parts and a new outline with building=* could be around the old ways and holds the address.

**Comment by Rexelpitlum** [comment] 2017-11-30 06:49
>>     Is there a way to get Streetcomplete to reload quests?
>Not now #706

Ok, so I had to do it the hard way. :-)
I deleted *all* application data and so did completely new quest searches for the respective areas.

Before that I assigned the address to the [School](https://www.openstreetmap.org/way/32520201) outline as suggested.
And for one [of the house groups](https://www.openstreetmap.org/way/300026755) standing on the same premises I draw an address polygon around this premises instead of assigning the address to one of the buildings.

Both approaches seem to work ok for now.
So for the issue of several buildings standing on the same grounds and sharing a common address there is a solution which should both satisfy StreetComplete's quest find algorithm and the OSM community approach that seems not to not allow the same addresses for different buildings

This leaves the university. There also exist buildings that share addresses, but these addresses are *not* the same all over the university campus
This rules out setting the address to the whole area as have been done e.g. for the school.
I am not yet sure how to handle such a case.

**Comment by westnordost** [comment] 2017-12-26 15:20
> And for one of the house groups standing on the same premises I draw an address polygon around this premises instead of assigning the address to one of the buildings.

Hmm, speaking of OSM community approach, are you sure that this is an acceptable solution?

So to be able to handle all cases, the app must allow its users to specify that a building has in fact no own address. This is planned for the next major release already, which makes this ticket a duplicate then. #351

**Comment by Rexelpitlum** [comment] 2017-12-26 20:04
> Hmm, speaking of OSM community approach, are you sure that this is an acceptable solution?

I am not quite sure about the community, but I checked the housenumbering regulations of the city where I live (Nuremberg). It states:

> Mehrere zur gemeinsamen Nutzung bestimmte Gebäude und Baulichkeiten werden zu einem Anwesen zusammengefasst und erhalten eine gemeinsame Hausnummer, auch wenn sie sich auf verschiedenen Grundstücken befinden.

Rough translation:
> Several jointly used buildings and constructions are combined to an "estate" and get assigned a common house number, even if they are located on different land parcels.

So a house number that is assigned to an arbitrary area is occurring and quite normal where I live and has to be somehow represented within OSM.

This also means that the planned "has no address" selection is actually not solving this particular problem. (As the buildings in question *do* have a house number, but share it with several others on the same "estate")

But the ticket should be closed nonetheless, as this specific situation can probably not be handled by this application (except perhaps by posting a note, which is ok.).

**Closed** 2017-12-27 00:19 UTC
