### ISSUE TITLE
Double undo has unexpected results

### ISSUE THREAD

**Issue by hmartink** [westnordost/StreetComplete#1966] opened 2020-07-19 18:55 UTC
If I enter information A and then B and then undo B and then A, then I can enter A again, but I'm not asked for B anymore. This is not nice, as B is correct but to undo A I have to undo B first.

The version is the one prior to todays update.

**Comment by westnordost** [comment] 2020-07-19 21:39
Which quests exactly?

If B depends on A being solved, the answer to A must be uploaded first. Also, that B immediately appears after upload of A does not work for all quests.

**Comment by hmartink** [comment] 2020-07-20 06:26
If I remember correctly I was asked about the number of stories of the house ("A"). Then the roof type ("B"). Then I looked at the next building and realized I made a mistake with the number of stories, so I undid the roof type ("B") and the number of stories ("A"). I could enter the number of stories again ("A"), but I was not asked for the roof type. 
If this appears again I can note down the details, maybe I can try out in the next mapping rounds (however, I'm back from vacation and in my vicinity there are not too many quests left ...)

**Comment by westnordost** [comment] 2020-07-20 10:07
Do you have auto-sync on?

**Comment by hmartink** [comment] 2020-07-20 10:24
Yes. 

(I cannot remember having looked at this option, what does it do?)

**Comment by westnordost** [comment] 2020-07-20 10:50
If it is off, upload and download is manual

**Comment by smichel17** [comment] 2020-07-21 12:07
> I could enter the number of stories again ("A"), but I was not asked for the roof type.

When you entered the number of stories the second time, did you set roof levels to 0? If so, this is probably a duplicate of https://github.com/westnordost/StreetComplete/issues/1929

**Comment by westnordost** [comment] 2020-07-21 13:52
Also, wasn't able to reproduce. Can you try again and say for which quests exactly this is reproducible?

**Comment by Saijin-Naib** [comment] 2020-07-29 18:56
I also experienced this for a survey of a road segment.

Question A was pavement type, Question B was lighting.

I undid both, but only was able to re-survey one of them, I believe Question A.

**Comment by westnordost** [comment] 2020-07-30 13:24
Auto-sync on or off? Also, can you reliably reproduce it? Random accounts of people who could also reproduce it once are not so helpful.

**Comment by Saijin-Naib** [comment] 2020-07-30 14:52
Auto-Sync on.

I've consciously avoided using undo since the first time I used it and experienced the bug, so I've not reproduced it again.

I can try later to see if it is indeed repeatable.

**Comment by westnordost** [comment] 2020-09-07 22:07
Closing this because there was no feedback/further info on reproducibility.

**Closed by westnordost** 2020-09-07 22:07 UTC
Labels: bug, feedback required
