### ISSUE TITLE
Cache invalidation does not work and duplicate quest solving is possible

### ISSUE THREAD

**Issue by Strubbl** [westnordost/StreetComplete#2266] opened 2020-11-12 13:40 UTC
If i click on cache invalidation, all tasks are refetched. But the tasks are the same as before although i know they have been solved in the meantime.

**How to Reproduce**
Use two devices for mapping. Download current location's quests with both devices. Solve a task with device A. It got uploaded and everything is fine.
Because i know, some tasks are solved, i am invalidating the cache on device B so that i can continue mapping. But on device B the quest is displayed which i have already solved on device A.
So ok, the cache invalidation popup said, it will invalidate the cache if it sees a task is already solved. But this is currently wrong, here's the bug. I can solve the quest again and this gets uploaded to OSM producing a changeset with no real change, e.g. see version 4 and 5 of https://www.openstreetmap.org/way/67901996/history

Note: okay to be precise, the app says it will invalidate the cache if another user already solved the quest. But here it is me on another device who has solved the quest

**Versions affected**
26.1 or 26.0-beta3

**Comment by cyclingcat** [comment] 2020-11-12 19:18
Duplicate of #2255?

The cycling cat

**Comment by smichel17** [comment] 2020-11-12 19:29
>  I can solve the quest again and this gets uploaded to OSM producing a changeset with no real change, e.g. see version 4 and 5 of https://www.openstreetmap.org/way/67901996/history

This part at least does not seem like a duplicate.

**Comment by westnordost** [comment] 2020-11-12 21:45
> If i click on cache invalidation, all tasks are refetched. But the tasks are the same as before although i know they have been solved in the meantime.

Yes, it is a duplicate of the bug that caused #2255

**Closed by westnordost** 2020-11-12 21:45 UTC
Labels: bug

**Comment by Strubbl** [comment] 2020-11-13 17:25
But what is with the check which should catch that the task has already been solved? Doesn't it check the data OSM before updating the object's tags, in my example the building type? I thought something like this existed due to the cache invalidation popup's text:

> The quest cache is invalidated automatically after one week and immediately when a quest you solved turns out to be already answered by someone else.
