### ISSUE TITLE
Quests that only appear on some levels of zoom

### ISSUE THREAD

**Issue by aracnus** [westnordost/StreetComplete#126] opened 2017-04-17 19:01 UTC
I'm having a problem with version 0.7 from F-Droid. Some quests only appear if I do a pinch zoom to a specific level. And it isn't a specific level. Different levels show different quests. This is bad because sometimes I'm on movement, with GPS following active and lose some quests because they don't appear on that level of zoom.

**Comment by westnordost** [comment] 2017-04-17 20:37
Duplicate of #50

**Closed by westnordost** 2017-04-17 20:37 UTC
