### ISSUE TITLE
Requirement: Rotate On-screen map orientation

### ISSUE THREAD

**Issue by CarlosBrys** [westnordost/StreetComplete#319] opened 2017-06-12 20:01 UTC
The map on the screen is always oriented to north.
That is a complication if one walks in the opposite direction or in an east-west direction.
Can you add an option to manually rotate the map to facilitate user orientation and better upload data?

**Comment by matkoniecz** [comment] 2017-06-12 20:05
duplicate of #69

**Closed** 2017-06-12 22:20 UTC
