### ISSUE TITLE
More surfaces available for paths

### ISSUE THREAD

**Issue by rhhsm** [westnordost/StreetComplete#2000] opened 2020-08-06 13:21 UTC
I noticed that for (foot)paths, not many surfaces are available to choose from. I especially miss "gravel" (instead "pebblestones" is available which looks similar on the photo). When selecting "show more", it shows choices that I think are only used for tracks. I would like the options for path surfaces to be more similar to those available for roads...

By the way, speaking of available reply options, I once has a quest for what was grown in an orchard, with "tomatoes" and "paprikas" available. By definition, what's grown in orchards is grown on trees, so if tomatoes were grown there, it wouldn't be called an orchard :) I was also surprised by some exotic options available for sports areas, such as Canadian & Australian football. Would be nice if these were not offered in Europe. The option "table tennis" that I needed wasn't available.

Ideally, the available answer options could be made dependent on the frequency of answers already present in that (wide) area, but that's probably not easy to code?

**Comment by westnordost** [comment] 2020-08-06 13:26
There should be both gravel and fine gravel. Though I think I have never seen a footway with gravel. Gravel would be the kind of surface on which the [railroad ties](https://en.wikipedia.org/wiki/Railroad_tie) are laid down on for a railway.

<img src="https://raw.githubusercontent.com/westnordost/StreetComplete/master/app/src/main/res/drawable-xxhdpi/surface_fine_gravel.jpg"/>
Fine gravel

<img src="https://raw.githubusercontent.com/westnordost/StreetComplete/master/app/src/main/res/drawable-xxhdpi/surface_gravel.jpg"/>
Gravel

---

In which country are you contributing?

**Comment by Atrate** [comment] 2020-08-06 13:49
@rhhsm 
> By definition, what's grown in orchards is grown on trees

https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dorchard 
OSM considers plantations and other fruit/vegetable cultivation techniques (ex. for stuff that would comprise a *farmland*) collectively as "orchards"

**Comment by rhhsm** [comment] 2020-08-06 15:23
> There should be both gravel and fine gravel. 

I see asphalt, paving stones, dirt, pebblestones, concrete and compacted, and as secondary options paved, unpaved and ground.

> Though I think I have never seen a footway with gravel.

There are a few in my area. Unpleasant to walk on, but cheaper than fine gravel.

> In which country are you contributing?

Bulgaria, with Dutch language. Are the answer options location or language dependent?

**Comment by smichel17** [comment] 2020-08-06 17:28
Duplicate of #1952

**Comment by Atrate** [comment] 2020-08-06 19:00
> as secondary options paved, unpaved and ground
As smitchel17 pointed out, you can press on the secondary categories to reveal more surfaces.

**Comment by rhhsm** [comment] 2020-08-07 04:45
> 
> 
> > as secondary options paved, unpaved and ground
> 
> As smichel17 pointed out, you can press on the secondary categories to reveal more surfaces.

I never guessed there were more options to be found there. I think the structure of answer options should be simplified. As long as the most common options are on the first page, I don't think anyone will mind scrolling through more pages with options for less frequent ones.

**Comment by westnordost** [comment] 2020-08-07 10:54
Maybe the original surface-quest could be changed to not offer the generic choices (ground, unpaved, paved) at all anymore but only the concrete values. Basically, use @matkoniecz implementation of the "what specific surface does this road have?"

**Comment by westnordost** [comment] 2020-10-13 12:35
I am closing this

**Closed by westnordost** 2020-10-13 12:35 UTC
