### ISSUE TITLE
Wheelchair quests for bus stations

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#346] opened 2017-06-23 16:33 UTC
In the current version from git master there is now a new quest for every bus station.

All bus stations that I have seen in my life are a "part" of the footway and so are always accessible for wheelchairs. So I could simply answer all quests with "yes". But that wouldn't make sense.

So the question should be related to the bus line/type of bus instead of the bus station, shouldn't it?

**Comment by HolgerJeromin** [comment] 2017-06-23 20:37
I know a few places where you can not leave the (short) sidewalk.

**Comment by westnordost** [comment] 2017-06-24 10:02
You have a point there. This adds far too many quests with far to little information value. The quest should be changed to ask for **bus stations**, not bus stops and single platforms.

**Comment by Etua** [comment] 2017-06-25 09:31
How many bus stations not avaible by wheelchair in general are there? How such obstacle look like?

**Comment by matkoniecz** [comment] 2017-06-27 12:28
Note https://taginfo.openstreetmap.org/tags/highway=bus_stop#combinations

17k with wheelchair=no, 56k with wheelchair=yes. None are tagged as wheelchair=no in my city according to overpass turbo.

**Comment by Etua** [comment] 2017-06-27 13:10
@matkoniecz Actually there are some. Just look at https://www.google.pl/maps/@52.2179299,21.0198944,3a,75y,342.49h,90t/data=!3m7!1e1!3m5!1s6cfR-yDgLpd7PGisEjmNZg!2e0!6s%2F%2Fgeo0.ggpht.com%2Fcbk%3Fpanoid%3D6cfR-yDgLpd7PGisEjmNZg%26output%3Dthumbnail%26cb_client%3Dmaps_sv.tactile.gps%26thumb%3D2%26w%3D203%26h%3D100%26yaw%3D349.0601%26pitch%3D0%26thumbfov%3D100!7i13312!8i6656

**Comment by callis** [comment] 2017-06-27 15:40
and here:
https://www.google.pl/maps/@51.2178283,6.7683066,3a,75y,219.78h,82.33t/data=!3m6!1e1!3m4!1su6Atwdwn8DeoHBs12vcC2g!2e0!7i13312!8i6656

**Comment by westnordost** [comment] 2017-06-27 23:30
> 17k with wheelchair=no, 56k with wheelchair=yes

Hmm this would mean about a quarter of all bus stops are not wheelchair usable. Somehow this sounds extremely unlikely.

So, on the assumption that the examples from callis and Etua are really exceptions, my plan is to remove bus stops from the quest and add instead bus stations. If you think this assumption is wrong, I would appreciate if you would crosscheck the wheelchair=no data (random sampling only) with streetview and see how much % of the tags are rightfully wheelchair=no and how much % are really just misunderstandings.

**Comment by matkoniecz** [comment] 2017-06-28 04:53
> Hmm this would mean about a quarter of all bus stops are not wheelchair usable

Note that 1878k highway=bus_stop are tagged and ones that are not wheelchair usable are more likely to be taggged with wheelchair tag - so true proportion is certainly lower than 25% and probably higher than 0,7%,

> random sampling only

Hm, I wonder is there a way to get random sample of overpass entries without downloading all of them and only later sampling.

**Comment by matkoniecz** [comment] 2017-06-28 07:00
new type of access limitation - https://www.openstreetmap.org/node/1468085718#map=19/41.89486/12.48499&layers=N https://www.google.com/maps/@41.8950309,12.4840822,3a,18.6y,184.53h,90.75t/data=!3m6!1e1!3m4!1shl1xG8ojvFn6BXpdTSnUGw!2e0!7i13312!8i6656 - bus stop table itself is inaccessible (blocked by steps)

**Comment by matkoniecz** [comment] 2017-06-28 11:05
> f you think this assumption is wrong, I would appreciate if you would crosscheck the wheelchair=no data (random sampling only) with streetview and see how much % of the tags are rightfully wheelchair=no and how much % are really just misunderstandings.

I did this and I recommend dropping highway=bus_stop. I now suspect that wheelchair=no on highway=bus_stop was used to mark that no suitable buses are used on lines that use given bus stop what seems to be understandable mistagging and/or tagging for renderer.

bus stop inaccessible for wheelchair - 16 randomly selected from 16k mapped

* https://www.openstreetmap.org/node/451174437#map=15/51.6101505/7.0576593layers=N - Germany, stretvieew not present
* https://www.openstreetmap.org/node/2592676383#map=15/48.3302641/17.3049598layers=N - not present in streetview, nearby bus stop seems to be mapped as wheelchair=no incorrectly https://www.openstreetmap.org/note/1045903
* https://www.openstreetmap.org/node/3899208561#map=15/51.8323299/7.9694925layers=N - Germany
* https://www.openstreetmap.org/node/1289231708#map=15/59.5781231/11.1710981layers=N - streetview unavailable (minor road without coverage)
* https://www.openstreetmap.org/node/890361606#map=15/51.17752/9.3713423layers=N - Germany
* https://www.openstreetmap.org/node/2351484630#map=15/45.3828485/5.578535layers=N - https://www.openstreetmap.org/note/1045899
* https://www.openstreetmap.org/node/2513116552#map=15/48.8608029/2.5093542layers=N - https://www.google.com/maps/@48.8608156,2.5094272,3a,75y,245.75h,83.01t/data=!3m7!1e1!3m5!1skhXOYG9JU85vpMZLl4gLeA!2e0!6s%2F%2Fgeo0.ggpht.com%2Fcbk%3Fpanoid%3DkhXOYG9JU85vpMZLl4gLeA%26output%3Dthumbnail%26cb_client%3Dmaps_sv.tactile.gps%26thumb%3D2%26w%3D203%26h%3D100%26yaw%3D291.65256%26pitch%3D0%26thumbfov%3D100!7i13312!8i6656 https://www.openstreetmap.org/note/1045911

Following were not checked.

* https://www.openstreetmap.org/node/2530434458#map=15/47.4439363/0.9904264layers=N
* https://www.openstreetmap.org/node/4569872064#map=15/52.029126/7.9540962layers=N
* https://www.openstreetmap.org/node/3335064481#map=15/49.1210262/18.4584796layers=N
* https://www.openstreetmap.org/node/3259939889#map=15/51.5878997/9.1504778layers=N
* https://www.openstreetmap.org/node/364819160#map=15/54.4605586/9.8279787layers=N
* https://www.openstreetmap.org/node/1792432230#map=15/48.3670325/14.5178703layers=N
* https://www.openstreetmap.org/node/4263400372#map=15/47.8417711/16.2456116layers=N
* https://www.openstreetmap.org/node/4510156572#map=15/52.0342816/7.781179layers=N
* https://www.openstreetmap.org/node/4566146925#map=15/49.8926887/1.0744746layers=N

**Comment by HolgerJeromin** [comment] 2017-06-28 12:38
I found some bus stops with wheelchair=no in my old hometown. I am pretty sure that the stops itself are wrong tagged.
I am not sure if is not the same with bus_stations.

**Comment by westnordost** [comment] 2017-06-28 14:42
@HolgerJeromin might be, but at least there are much less bus stations, so users are not spammed that much.

A bus stations layout I know has many platforms as islands on a bigger asphalted area. So you always need to cross the street to get to one of these islands. If these islands are not accessible via wheelchair (no "ramp"), it would be wheelchair=no.

**Comment by HolgerJeromin** [comment] 2017-06-28 17:40
> If these islands are not accessible via wheelchair (no "ramp"), it would be wheelchair=no.

If there are some which are and some not? The [platforms of Aachen Bushof](https://www.openstreetmap.org/relation/156174) are not all the same.
Even wheelchair=limited does not really help here.

**Comment by akudzo** [comment] 2017-06-30 12:52
According to https://wiki.openstreetmap.org/wiki/Key:wheelchair#Bus_stop : 
_"wheelchair=yes (if there is a high level kerb or all bus routes at all times have a ramp or lift.)"_
So it's not (just) about the bus stop being accessible by wheelchair, but about the bus itself being accessible.

**Comment by Natenom** [comment] 2017-06-30 13:17
So should I really begin to solve all those bus station quests with yes because all bus lines here have such busses with ramps? There are hundreds of bus stations in this area...

**Comment by chrisdebian** [comment] 2017-06-30 14:01
It looks like the high level curb is the main point, as I guess it would be difficult to confirm that all buses have ramps or lifts.

Chris.

**Comment by matkoniecz** [comment] 2017-06-30 14:06
> or all bus routes at all times have a ramp or lift

So you can answer yes to this quests or wait till #360 or equivalent is merged and new version released.

**Comment by westnordost** [comment] 2017-06-30 14:38
This doesn't make sense so it is good that SC does not serve this kind of tagging. That would be a property of busses (or at least bus routes), not of bus stops.

On 30 June 2017 14:52:26 CEST, akudzo <notifications@github.com> wrote:
>According to
>https://wiki.openstreetmap.org/wiki/Key:wheelchair#Bus_stop : 
>_"wheelchair=yes (if there is a high level kerb or all bus routes at
>all times have a ramp or lift.)"_
>So it's not (just) about the bus stop being accessible by wheelchair,
>but about the bus itself being accessible. 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/346#issuecomment-312259165

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by PanierAvide** [comment] 2017-07-01 08:29
The problem is that some bus lines are only partly accessible to wheelchair (it is also the case on old subway stations like in London). So if you want to let user know on a line which bus stop is accessible or not over a bus line (by the presence of elevated kerb), it has to be a property of the bus stop itself, not the bus line.

**Closed** 2017-07-01 16:20 UTC
Labels: bug
