### ISSUE TITLE
AddPlaceName quest doesn't seem to work

### ISSUE THREAD

**Issue by dbdean** [westnordost/StreetComplete#653] opened 2017-10-18 12:29 UTC
I noticed that there seems to be an AddPlaceName question in the app that has never shown anything for me in app/src/main/java/de/westnordost/streetcomplete/quests/place_name/AddPlaceName.java.

For example, http://www.openstreetmap.org/node/5046237818 is a restaurant without a name, but StreetComplete has never asked me for its name.

Is there something wrong with the query string? Or is the quest not actually invoked? Is it country specific?

**Comment by dbdean** [comment] 2017-10-18 12:32
Ah, it's commented out in app/src/main/java/de/westnordost/streetcomplete/quests/QuestModule.java:

```
// ↓ 4. may be shown as possibly missing in QA tools
new AddHousenumber(o),
// new AddPlaceName(o), doesn't make sense as long as the app cannot tell the generic name of elements
new AddRecyclingType(o),
```

But I don't really understand the comment explaining why it's commented out?

**Comment by westnordost** [comment] 2017-10-18 12:49
Because the quest asks something like "What is the name of this place?"

But the user does not even know what is meant with this place because
* the own GPS location is often not precise
* the location of nodes in OSM are not always precise as well (probably for the same reason... )
* there might be several things at that location

What is needed for the user to identify this place is for the app to be able to name it. I.e.
"What is the name of this bakery?"

So, what is missing for that is some kind of localized dictionary from tags to primary features for each language. This kind of dictionary does not exist yet.

(This is actually the first thing I started with when I envisioned this project (SC) almost three years ago. However, I put that on hold to first start with this app. Now that the app is live, there is always something more important to do than finish (and maintain) that project as that dictionary would be just used for one quest. [ I once created a forum topic about reviving this, but there seemed to be no interest.](https://forum.openstreetmap.org/viewtopic.php?id=56889) )

P.S: This is basically a duplicate of #309, but I did not add a long explanation there why it is blocked yet.

**Comment by westnordost** [comment] 2017-10-18 13:05
You wouldn't be interested in creating such a dictionary, would you? :-P
The cool thing about if such a project existed within the OSM ecosystem is that any app and tool would be able to very easily gain the ability to name an arbitrary element by using this dictionary and of course, translations only need to take place in one place instead of for every OSM related project.
It also enables the use cases of that 
- in Nomatim etc., users could (when implemented) search for "supermarket, [some town]" instead of "Aldi, [some town]"
- surveyors using (apps like maps.me) that want to add new nodes could simply search for a thing in their language to get the right tag combination.

**Comment by westnordost** [comment] 2017-10-18 13:15
In any case, I will close this as duplicate of #309

**Closed** 2017-10-18 13:15 UTC
Labels: blocked, duplicate

**Comment by dbdean** [comment] 2017-10-18 13:57
I reckon that the iD project already has a lot of that in place, but I'm not sure how easy it might be too get it out. 

For example, all the text for their presets is defined in https://github.com/openstreetmap/iD/blob/master/data/presets.yaml and translations are available.

**Comment by matkoniecz** [comment] 2017-10-18 19:45
> surveyors using (apps like maps.me) that want to add new nodes could simply search for a thing in their language to get the right tag combination. (I.e. they spot a "Lederhandel" and just want to add that node but neither have the patience nor the knowledge to look up what "Lederhandel" (leather shop) would be as an OSM tag)

maps.me keeps this data in https://github.com/mapsme/omim/blob/master/data/categories.txt
