### ISSUE TITLE
Improve the usability of street names for buildings

### ISSUE THREAD

**Issue by De-Luxis** [westnordost/StreetComplete#2160] opened 2020-10-13 03:59 UTC
**Use case**
When completing the quest to indicate the street, you have to enter the name manually. The entered name may not coincide with the one already on the map. Because of this, there may be several variations of the name of one street.

**Proposed Solution**
When specifying a street by default, offer to choose from the ones nearest to the building from those already available in the database. At the same time, leave the opportunity, if desired, to enter manually.
Sort the list by the street closest to the building or point.

**Comment by ei8fdb** [comment] 2020-10-13 07:54
Is it possible to add a usability to this issue?

**Comment by ei8fdb** [comment] 2020-10-13 08:03
@De-Luxis have you seen the option of the white caret which reveals a street name the RHS in this screenshot:

![Screenshot_20201013-100124__01](https://user-images.githubusercontent.com/1899506/95832936-44985e80-0d3b-11eb-9161-5995c83c89dd.jpg)

Would that achieve what you've suggested above?

**Comment by matkoniecz** [comment] 2020-10-13 08:08
> Is it possible to add a usability label to this issue?

Currently there is no such label

**Comment by ei8fdb** [comment] 2020-10-13 08:14
@westnordost Is it possible to add a usability label to issues filed in this repo?

**Comment by cyclingcat** [comment] 2020-10-13 08:19
@ei8fdb: The "road name" quest indeed shows this white caret, but the "street name for building" quest doesn't. 

The cycling cat

**Comment by ei8fdb** [comment] 2020-10-13 08:28
> @ei8fdb: The "road name" quest indeed shows this white caret, but the "street name for building" quest doesn't.
> 
> The cycling cat

Could the same "road name" UI pattern be used for "street name for building"? I've not seen that quest. 

@De-Luxis could you post a screenshot of what you see currently? I've not seen that quest. Thanks.

**Comment by De-Luxis** [comment] 2020-10-13 08:43
> > @ei8fdb: The "road name" quest indeed shows this white caret, but the "street name for building" quest doesn't.
> > The cycling cat
> 
> Could the same "road name" UI pattern be used for "street name for building"? I've not seen that quest.
> 
> @De-Luxis could you post a screenshot of what you see currently? I've not seen that quest. Thanks.

![Screenshot_20201013-134250](https://user-images.githubusercontent.com/2688692/95837425-0b231b80-0d5a-11eb-8297-bc55e24cf10a.png)

**Comment by ei8fdb** [comment] 2020-10-13 08:46
@De-Luxis @cyclingcat From looking at that, I think the same UI pattern could be used. What do you think?

As long as the data is available to drive the options visible when the user taps the caret.

**Comment by westnordost** [comment] 2020-10-13 10:06
@De-Luxis okay, so this ticket is based on a misunderstanding? I don't understand what you want to be changed, basically what you suggested in your thread starter already exists.

@ei8fdb you mean additionally to the dropdown or in place of it? In any case, I hold the opinion that the UI as it is is perfect. For the "street name of address" quest, the user should just allocate the (closest) street to the address, so it makes sense to let him point and click. 
For the "street name" quest however, the user is supposed to look for a street sign. The difference is that in the first case, having to add an own name to the field is absolutely an exception, for the second case it is the other way around. It is an exception that the user determined that in fact this piece of road belongs to another already named piece of road.

**Comment by cyclingcat** [comment] 2020-10-13 10:28
But currently it's implemented just the other way round: The "street name of house number xxx" quest does _not_ show a dropdown menu (see second screenshot) while the "road name" quest shows it (see first screenshot).

Apart from this, I'd vote for showing the dropdown in _both_ quests. Especially in well-mapped regions there are just snippets of unnamed roads left, and in those cases the chance is very high that missing road name are the same as the ones of roads in their direct surroundings.

The cycling cat

**Comment by De-Luxis** [comment] 2020-10-13 10:29
@westnordost Thank you very much, I did not know that you can click on the street and the name will be substituted automatically. This is not obvious behavior.
You can close the task at your discretion, but the problem exists. You can add a hint.

**Comment by westnordost** [comment] 2020-10-13 10:36
@De-Luxis But there is a hint! It is just below the question

**Comment by westnordost** [comment] 2020-10-13 10:37
> But currently it's implemented just the other way round: The "street name of house number xxx" quest does not show a dropdown menu (see second screenshot) while the "road name" quest shows it (see first screenshot).

You misunderstood. It's not about the dropdown. There are two different methods of prefilling that road name box in use. Tapping on the map for the "address street" quest, and the dropdown for the "street name" quest.

**Comment by westnordost** [comment] 2020-10-13 10:39
@De-Luxis If you like, you can try to complete or contribute towards the completion of the Russian translation here: https://poeditor.com/join/project/IE4GC127Ki

**Comment by De-Luxis** [comment] 2020-10-13 10:46
@westnordost Really. I am blind and too lazy to translate the text above the field.
Thank you again. I will make a translation.

**Comment by ei8fdb** [comment] 2020-10-13 11:36
> you mean additionally to the dropdown or in place of it? In any case, I hold the opinion that the UI as it is is perfect. For the "street name of address" quest, the user should just allocate the (closest) street to the address, so it makes sense to let him point and click.

Clearly it's not perfect if this user has not successfully used it. 

The issue is the UI doesn't make it clear how users should complete the task - like the issue I opened, like the issue of road surfaces. There are some ways to improve it that won't take a lot of implementation. 

It seems I've made a mistake in thinking the project might welcome UX contributions, so I'll refrain from now on.

**Comment by De-Luxis** [comment] 2020-10-13 11:47
UX contribution is very important. Otherwise, the application will not be used by ordinary users.

**Comment by HolgerJeromin** [comment] 2020-10-13 12:34
I (using the app since a few years) was about raising the same issue here too.
This quest is the only quest which can be answered by clicking on the map. 
Perhaps we really need a popup before solving the quest the first time explaining it.

**Comment by De-Luxis** [comment] 2020-10-13 12:40
Ideally, bring the street indication to one view.

**Comment by westnordost** [comment] 2020-10-13 14:13
UX contributions are welcome, but as any other contribution, these need to be discussed, and usually I myself also hold an opinion on this as well. I will also state my opinion but that doesn't mean I won't change it given convincing arguments. I didn't mean to come across as rude. In my last post, I stated my opinion and brought up an argument as to why, that's all.

I'll reopen this ticket for now so that discussion happening here stays visible.

**Comment by smichel17** [comment] 2020-10-13 22:41
> I stated my opinion and brought up an argument as to why, that's all.

In my experience working in an international [team](https://community.snowdrift.coop/g/team), this is a common source of confusion between Germans and Americans. You tend to leave "that doesn't mean I won't change it given convincing arguments" implicit, whereas we tend to express it. In other words, Americans tend to interpret a statement of opinion with no clarification as more final than Germans intended it.

> It seems I've made a mistake in thinking the project might welcome UX contributions, so I'll refrain from now on.

To me this comes off as quite passive-aggressive and accusatory (although of course that may be another misinterpretation :upside_down_face:). Speaking this time as the maintainer of a [FLO](https://wiki.snowdrift.coop/about/free-libre-open) Android [app](https://github.com/LibreShift/red-moon), this kind of statement makes me feel defensive; a bit anxious / concerned about possible drama; and overall less interested in working on the project. Also, in this case, because it's apparent to me from watching the repo for a while that westnordost does care about UX, it seems like you've invested very little before assuming the worst.

So, even though I think your feedback was otherwise good, if this were my app I might decide not to respond, so that you'd leave me alone. Especially if there are already more open issues than I have time to work on, I don't need someone with an attitude giving me grief that I'm not interested in work they want me to do.

(At this point, I should re-iterate: This is how the comment comes off *to me,* which may not be how it's intended or how others interpret it.)

I appreciate your interest in UX — sorely lacking in many FLO applications — and only ask that you  consider your impact on maintainers. The UX of your comment, if you will :smile:. 

> Perhaps we really need a popup before solving the quest the first time explaining it.

I'd suggest highlighting the streets on the map that are clickable (like the road surface quest, but a different color). This gives an indication that you're intended to interact with the map and is also useful to users who already know how the interface works, in cases like this, where, as far as I can tell, no road is clickable (in this case it belongs to the loop on the left, but it changes names basically right where the neighborhood driveway/road pulls out; I'm not sure which of the two these houses use).

<img height="500" src="https://user-images.githubusercontent.com/6563664/95921632-26654980-0da1-11eb-91e7-d2ed5716f24a.png"/>

**Comment by De-Luxis** [comment] 2020-10-14 04:02
It should be given its due that this application is currently one of the best in terms of user interface among all applications related to OSM.

**Comment by MCMic** [comment] 2020-10-14 11:37
I think it should be made more obvious than clicking street is the main way while textfield is just in case, because I had the same problem and thought I HAD to type the street name, until I read this issue here.

Maybe only show the instruction to click the street, and a small button to access the textfield, which looks less like a main required field?

**Comment by westnordost** [comment] 2020-10-14 11:42
I don't understand, you went so far as to go to GitHub, search for issues, find this issue, read this issue _but you did not read the text right below the question_?

**Comment by MCMic** [comment] 2020-10-14 13:21
> I don't understand, you went so far as to go to GitHub, search for issues, find this issue, read this issue _but you did not read the text right below the question_? I mean, this hint text is apart from the question itself the only text on this screen at all. Why don't people read it?

Well, I did not come to github specifically for this issue, but it was one of the things bothering me with the app.
I think I did not read the text because of how it looks and how it’s placed, my brain automatically supposed this text was saying «please fill the name of the street in this field». The fact that it’s small and gray makes it look like a hint, not the main way of answering the quest. And quite frankly I was expecting a drop-down with street names, I never thought of clicking the map since I did not encounter this kind of user input in the rest of the app.

Oh. I just noticed the french translation for this is also less clear. It says something like «Select the street which this building belongs to, or enter the name without abbreviations in the field below». It does not say «Click on the map» or «Tap», just a generic «Select», so maybe I actually read the text quickly and did not understand it.

**Comment by westnordost** [comment] 2020-10-14 13:48
> Oh. I just noticed the french translation for this is also less clear. It says something like «Select the street which this building belongs to, or enter the name without abbreviations in the field below». It does not say «Click on the map» or «Tap», just a generic «Select», so maybe I actually read the text quickly and did not understand it.

Ah, would you like to correct it or suggest another wording?

Regarding your suggestion with the button - If the button was named "tap here to manually add a name" or similar, it would still be just as prominent as the edit text input. So I think users would equally just tap on that button, thinking it is a similar interface as for the opening hours where you also have to press that button first.
It could be a text link of course, like "Tap on the map to select the street it belongs to <u>[or write the name of the street manually](https://github.com/westnordost/StreetComplete/issues/2160)</u>", but text links are not really used anywhere else in the app and generally in apps I think it is not a good pattern.

**Comment by MCMic** [comment] 2020-10-14 19:08
Maybe a smaller «ABC» button like I think I’ve seen in other places?

**Comment by De-Luxis** [comment] 2020-10-15 05:15
Why not make a drop-down list like when specifying a street name on a road? There will be three options. The functionality is already there.

**Comment by westnordost** [comment] 2020-10-15 10:11
The ABC button in the housenumber form is just to switch the active keyboard between numbers only and all letters, not to open up the keyboard in the first place. I am going to improve this so that the ABC button is only shown while the keyboard is open.

**Comment by westnordost** [comment] 2020-10-16 12:51
Seems there is not going to be more discussion here. Closing this as the original issue has been dissolved (because it was a misunderstanding) and discussion reeled off into various directions from then on. If you have concrete suggestions how to make this or that UI better, you can open a new ticket.

**Comment by westnordost** [comment] 2020-10-16 12:51
Also, the new beta is out now with the improvements on the houseumber form

**Comment by mnalis** [comment] 2020-11-18 17:51
I must admit this quest confused me at first too as I'm too guilty of not noticing small print. Luckily I figured it out by pure luck and have been clicking on streets instead of typing happily everafter.

I this it is because of UI expectations: when I see something that look like regular input field, behaves like an input field and quacks like the input field, my brain will automatically assume it **is** a regular input field and disregard possible hints present around it suggesting that it is **more** tan a regular input field.

I think it might be worthwhile to add HTML5-alike "placeholder" functionality (grayed out text that disappears when you start typing, like the one we now have for housenumbers quest with last inputted value). Something like this:

![street-missing-ui-proposal1](https://user-images.githubusercontent.com/156656/99567645-b153e800-29ce-11eb-8038-ee9c9626d165.png)

I know it is duplicating what is said in the hint above, but I think it would be much less potential for confusion (missing very  useful functionality)!

**Comment by westnordost** [comment] 2020-11-18 17:55
That's a good idea. Maybe it can be done without duplication? I.e. also change the text above? Do you have a suggestion for that?

**Comment by westnordost** [comment] 2020-11-18 18:04
Wording for hint maybe "Tap on street to prefill"?

**Comment by matkoniecz** [comment] 2020-11-18 18:06
"Select street by tapping on map"

"Tap on street to fill" seems simpler and equivalent to "Tap on street to prefill"

**Comment by westnordost** [comment] 2020-11-18 18:09
> "Select street by tapping on map"

that's good. It's probably not necessary to hint that you can also edit that field.

**Comment by westnordost** [comment] 2020-11-18 18:16
Or "Tap road on map". It must be short, because the text scaling is not working for hints.

**Closed** 2020-11-18 18:18 UTC
Labels: usability

**Comment by Freso** [comment] 2020-11-30 15:28
I think I answered this type of quest the first time I did it by typing out the street name. I did notice the "click on map" text when I did it the second time. However, even then, I would really, really appreciate a dropdown option with nearby street names, since it can be quite finicky to wiggle around on the map on a small-ish phone screen that also has the option box open (esp. as the keyboard usually gets pulled up as well when opening the quest, taking up even more screenspace). It is easier for my thumb to hit the right name in the street name dropdown, than it is for it to 1) exit out of keyboard, 2) position the map so I know the right street is being clicked, 3) actually hit the (small, narrow) line that represents the street.

I’m not sure what the actual argument against the dropdown option was/is, even after having read https://github.com/westnordost/StreetComplete/issues/2160#issuecomment-707636379 multiple times. (Also, I do not want to get rid of the map click interface. I still think that’s a good idea, and would be great to implement that for other quests too, where it makes sense, but having the dropdown list _in addition_ would make it easier and less cumbersome to do this quest.)
