### ISSUE TITLE
Add an ability to record a track

### ISSUE THREAD

**Issue by nagisa** [westnordost/StreetComplete#2327] opened 2020-11-29 14:48 UTC
**Use case**

When I discover a missing road/path etc during my questing, I'm not able to add it immediately, for two reasons: it would take a ton of time to do so right, and StreetComplete does not appear to support adding roads or paths anyway.

**Proposed Solution**

I would love an ability to quickly record a GPS track so that I could add the missing road/path once I'm back home and have access to tools like JOSM. IMO it makes sense to add this functionality to StreetComplete because switching to a different app to record a track is inconvenient and further detracts from questing.

**Comment by westnordost** [comment] 2020-11-29 16:27
This is out of scope of this app / a duplicate of #2209

**Closed by westnordost** 2020-11-29 16:27 UTC
