### ISSUE TITLE
Bundle several quests that refer to one point

### ISSUE THREAD

**Issue by ServusWorld** [westnordost/StreetComplete#596] opened 2017-09-19 16:26 UTC
Sometimes several quests refer to the exactly same point (e.g. road surface/road maxspeed/road name).
These can be only answered in the order they are presented, so if I don't answer one of them, I can't answer the ones "below" it as well.

My ideas to make clear that more than one question is meant for one point:

# At the icon
## 1. Adding a "+1" (or "+2" or whatever) bubble on the map marker
which stands for the number of additional quests.
![sc_icon_1](https://user-images.githubusercontent.com/31391499/30602608-69033a9a-9d65-11e7-9069-8cd883067f71.png)

## 2. Making a "lineup" of all quest icons
where one is in the foreground and the other one(s) are layered behind it, a bit twisted.
![sc_icon_2](https://user-images.githubusercontent.com/31391499/30603257-3f9b38a4-9d67-11e7-8484-d1fde5de9b26.png)

# At the bottom sheet modal
## 1. Swiping right and left
and "swiping points"
![sc_bottom-sheet](https://user-images.githubusercontent.com/31391499/30603501-f894bd1c-9d67-11e7-9ddc-917cc29f84f7.png)

## 2. A menu
shows up when the user selects a map marker and then he can choose which quest to open

**Comment by westnordost** [comment] 2017-09-19 18:04
It is a good idea and a reasonable request.

Only the technical feasibility is the problem. The icon solution is pretty much not possible. The second or third solution should be possible with some effort, however, I think swiping between the different quest types makes less sense than to simply continue to the next quest when the first one has been answered (i.e. perhaps replacing "OK" with "OK, NEXT" in this case. For that, there is an issue somewhere already.

**Comment by rugk** [comment] 2017-09-19 22:49
> I think swiping between the different quest types makes less sense than to simply continue to the next quest 

It makes sense when you do not know the answer of one quest (and also don't want to leave a comment), but may answer other quests for the same object.

Tèchnically this is a dupe of https://github.com/westnordost/StreetComplete/issues/124, is not it?

**Comment by westnordost** [comment] 2017-09-20 18:22
Yes

**Closed by westnordost** 2017-09-20 18:22 UTC
