### ISSUE TITLE
Subway stations popup as housenumber-tasks

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#907] opened 2018-02-23 19:16 UTC
I'm currently not entirely sure how to fix this, but it feels wrong that SC create a task to add a house number to a subway station.

Do subway-stations have house numbers? 

Example:
https://www.openstreetmap.org/way/378955812

![screenshot_20180223-201059](https://user-images.githubusercontent.com/614929/36612268-6c34bb66-18d6-11e8-847e-60ecc77a6c64.jpg)

**Comment by ENT8R** [comment] 2018-02-23 20:01
IMO this is related or even a duplicate of #351...

**Comment by RubenKelevra** [comment] 2018-02-23 21:20
Well, this ticket mentions a tag called noaddress=yes, which SC sets if the user selects, that this building has no house number. But this option was obviously removed from SC.

So, maybe it's worth discussing how often buildings with layer=-2 and layer=-2 do have house numbers and if it's safe to assume that they do not need to popup as a task?

Currently, we show this task all users and each of them can hide this task once per subway station... this doesn't sound like the right solution here.

**Comment by ENT8R** [comment] 2018-02-23 21:41
> But this option was obviously removed from SC.

No. It was never added. But will be added if this issue is resolved...

**Comment by westnordost** [comment] 2018-02-24 00:29
Hmm, it is tagged as "train station". I wouldn't tag a building there at all, just the platform, but one could argue that it is correct correct to tag a building and maybe even correct to tag it as a "train station".

So, perhaps I can exclude buildings with negative layers from the quest? Though, a negative layer does not mean that something is underground.

**Comment by goldfndr** [comment] 2018-02-24 10:52
Reuben typed *layer=-2 and layer=-2* but one of those should be *level=-2* and negative level(s) would be a better exclusion than negative layer.

**Comment by matkoniecz** [comment] 2018-02-24 12:52
> So, perhaps I can exclude buildings with negative layers from the quest? Though, a negative layer does not mean that something is underground.

Yes, object in question is missing location=underground (it it really is underground). negative layer and level tag may appear on objects that are not underground (though while OK it happens really rarely).

**Comment by matkoniecz** [comment] 2018-02-24 12:59
I added location=underground per https://github.com/ENT8R/streetcomplete-mapstyle/issues/54#issuecomment-368226629

**Comment by RubenKelevra** [comment] 2018-02-24 15:41
So maybe we should make a quest from that? "Is this building underground? If underground-tag is not attached but level-tag is below 0? :)

**Comment by ENT8R** [comment] 2018-02-24 16:16
And setting `location=overground` if the building is over ground?

**Comment by matkoniecz** [comment] 2018-02-24 19:19
@RubenKelevra @ENT8R location=surface is not used and was not documented, so it would be impossible to tag anything for "normal" buildings - I added it on Wiki for now.

**Closed** 2018-02-24 20:22 UTC
Labels: feedback required

**Comment by RubenKelevra** [comment] 2018-02-25 17:58
@matkoniecz ah okay, I see the problem here.
