### ISSUE TITLE
Keybord overlaps with quest window

### ISSUE THREAD

**Issue by hmartink** [westnordost/StreetComplete#1967] opened 2020-07-19 18:55 UTC
I could not find a systematic behind this one. Somtimes the input keyboard is displayed *over* the quest itself (e.g. the window where I entere the number of stories of a building). Since the input window is hidden, I have to blindly type or try to move the quest window upwords, this often gives keypresses to the keyboard as well, which needs additional correction. Unfortunately I cannot provide a systematic to trigger this, but it happens frequently.

The version is the one prior to todays update.

**Comment by matkoniecz** [comment] 2020-07-19 19:18
What is your Android version and phone model?

**Comment by hmartink** [comment] 2020-07-19 19:43
It is a Nokia 3.1 (Android one) with the latest security level on Android 9.

**Comment by westnordost** [comment] 2020-07-19 21:39
Never seen such an issue.

Need more info on how to reproduce this..

**Comment by hmartink** [comment] 2020-07-20 06:23
What would you need? Next time this appears I can give you the exact details (spot, quest, answers etc.). Is this sufficient?

**Comment by westnordost** [comment] 2020-07-20 10:07
Well I'd need the steps to be able to reliably reproduce it at any time.

**Comment by hmartink** [comment] 2020-07-20 10:25
Next time it happens I'll see if I can make it reproducible and report.

**Comment by westnordost** [comment] 2020-09-04 09:30
Ok, I'll close this. Feel free to reopen in case you can make it reproducible.

Generally, such issues should actually be an issue of Android and not of the individual app because StreetComplete just declares "The activity's main window is always resized to make room for the soft keyboard on screen." in the manifest. If it still does that, that's basically a bug of your Android version.

**Closed by westnordost** 2020-09-04 09:30 UTC
Labels: bug, feedback required

**Comment by Helium314** [comment] 2020-09-04 10:35
Didn't notice this issue before... I sometimes see the same problem. Pressing back to dismiss the keyboard and tapping the text area usually leads to correct behaviour.
And it most likely is an Android issue, as I sometimes see the same in other apps.

**Comment by matkoniecz** [comment] 2020-09-04 13:26
>  And it most likely is an Android issue, as I sometimes see the same in other apps.

Given that it appears also in other apps it is even more certain that it is systemwide issue, sadly unfixable by SC.
