### ISSUE TITLE
Search for new quests does not work

### ISSUE THREAD

**Issue by Giant3** [westnordost/StreetComplete#1105] opened 2018-06-16 10:39 UTC
I cannot search for new quests, it always says: try it later. So I reinstalled the app, but still it does not work. I installed a older version of the app too, but still this issue. It can load the map and upload quests, which I downloaded before I had this issue.

**Comment by westnordost** [comment] 2018-06-16 12:38
Its not an issue of the app, that's why it says tp try it later. Probably, the Overpass api server had (or has) some problems

**Comment by matkoniecz** [comment] 2018-06-17 04:13
Is it still not working for you? Are other apps requiring internet  working correctly?

**Comment by Giant3** [comment] 2018-06-17 09:12
Yeah, it is still not working. All other apps are working correctly.

**Comment by stefannagy** [comment] 2018-06-17 15:08
I'm affected by the same issue for several days now. After reading this I deleted the cache, all app data, deinstalled and then reinstalled the app. Now I just lost the quests I downloaded weeks ago… I still get the error message mentioned above. I'm using StreetComplete 5.2 installed via F-Droid.

**Comment by Giant3** [comment] 2018-06-17 17:03
@westnordost works, like stefannagy.

**Comment by westnordost** [comment] 2018-06-17 21:18
We will find the problem. So, I understand that
- it started a a few days ago
- it's independent of the version of StreetComplete
- making a query on Overpass API from your device via browser works fine

I built this version for you: http://www.westnordost.de/misc/streetcomplete-v6.0-beta1-debug.apk . It is a modified Version 6.0-beta1 that always asks you to send an email to me if there was any kind of error during downloading the quests. Would you please install and execute it and send me the email when the dialog about the error pops up? This way, I will get more details about what status code the Overpass server returned

**Comment by stefannagy** [comment] 2018-06-18 07:43
I sent you an email.

I can't really confirm that it started only a few days ago. I didn't use StreetComplete for a few weeks, some days ago I startend using it again and since then I'm affected by this issue.

**Comment by westnordost** [comment] 2018-06-18 08:38
The source of this problem might be this merged PR: https://github.com/openstreetmap/openstreetmap-website/pull/1576

A note (comment?) can have an additional action/status but the osmapi library does not understand this. It is also not documented, hm.

**Comment by stefannagy** [comment] 2018-06-18 08:41
I just tried to search for new quests in the 10th district oft Vienna and couldn't repruduce this bug. So you're right, it has sonething to do with the location for which you're searching quests.

**Comment by westnordost** [comment] 2018-06-18 09:05
All notes in Vienna: https://api.openstreetmap.org/api/0.6/notes?bbox=16.2,48.1,16.5,48.3

**Comment by stefannagy** [comment] 2018-06-18 09:15
Please tryin this area to reproduce this issue: https://osm.org/go/0JrISxMZ--

**Comment by JeanFred** [comment] 2018-06-18 10:51
Interesting − I also had repeatedly issues recently when trying to fetch quests in Vienna − can’t recall all insatnces, but at least for sure in the 20th district.

**Comment by stefannagy** [comment] 2018-06-18 11:56
> All notes in Vienna: https://api.openstreetmap.org/api/0.6/notes?bbox=16.2,48.1,16.5,48.3

Should i try something with this link?

**Comment by westnordost** [comment] 2018-06-18 17:39
No, I found the cause.

**Closed** 2018-06-18 18:53 UTC
Labels: bug
