### ISSUE TITLE
Sort opening hours

### ISSUE THREAD

**Issue by Helium314** [westnordost/StreetComplete#1371] opened 2019-04-11 14:28 UTC
When adding opening hours, I try to avoid as much as possible of the tedious entering of times. For one place there were different opening hours for different days, which resulted in this:

Tu,Th,Fr 08:00-12:30, Mo,We,Th 13:30-17:00, Tu,Fr 13:30-16:00; Mo,We 09:00-12:30

While it is correct, this looks quite ugly. Would it be possible to (automatically) sort the list of times before submitting?

**Comment by westnordost** [comment] 2019-04-11 19:44
It would be technically possible of course, with some effort, but I do not want to do it because this opening hours form should be WYSIWYG. Specifically, the surveyor should be able to copy the opening hours just as they are given on the opening hours sign, without any automatism of the app interfering there. The opening hours string, due to it's (possible) complexity, is usually not shown to end users anyway.

But actually, the opening hours string you wrote would be wrong. The Mo,We rule at the end overwrites the previous rules.  This shouldn't happen. Did you mistype or did StreetComplete actually tag it like this?

**Comment by Helium314** [comment] 2019-04-12 05:17
This is copy/pasted from openstreetmap.

The reason for not copying the opening hours from the sign line by line is that it just takes unnecessarily long.
A more simple expamle: same opening hours every day, except We. I tag Mo, Tu, Th, Fr together, and then We separately. When entering like this, I simply did not expect the resulting list to show up in exactly this order.

**Comment by westnordost** [comment] 2019-04-12 06:59
Can you point me to the element? Because this looks like a bug

Am 12. April 2019 07:17:20 MESZ schrieb Helium314 <notifications@github.com>:
>This is copy/pasted from openstreetmap.
>
>The reason for not copying the opening hours from the sign line by line
>is that it just takes unnecessarily long.
>A more simple expamle: same opening hours every day, except We. I tag
>Mo, Tu, Th, Fr together, and then We separately. When entering like
>this, I simply did not expect the resulting list to show up in exactly
>this order.

**Comment by Helium314** [comment] 2019-04-12 09:10
https://www.openstreetmap.org/node/3151609868#map=18/49.20910/16.59032

**Comment by westnordost** [comment] 2019-04-12 14:05
Hmm, maybe this is not a bug.

So, should the opening hours have been [like this](https://openingh.openstreetmap.de/evaluation_tool/?EXP=Tu%2CTh%2CFr%2008%3A30-12%3A30%2C%20Mo%2CWe%2CTh%2013%3A30-17%3A00%2C%20Mo%2CWe%2009%3A00-12%3A30%3B%20Th%2CFr%2013%3A30-16%3A00)?
Or rather [like this](https://openingh.openstreetmap.de/evaluation_tool/?EXP=Tu%2CTh%2CFr%2008%3A30-12%3A30%2C%20Mo%2CWe%2CTh%2013%3A30-17%3A00%2C%20Mo%2CWe%2009%3A00-12%3A30%2C%20Fr%2013%3A30-16%3A00)?

I suspect the latter, which makes this an input mistake, you put the `Th` in the last rule. If on the other hand, this is really what was on the sign, it is simply ambiguous and StreetComplete must decide how to interpret this.
StreetComplete puts the `;` there because `Do, Fr 13:30-16:00` overlaps in times with the previous rules, so it assumes it is meant as an overwriting rule. E.g. as if someone writes on the sign "[open weekdays 8:00-16:00, We 8:00-12:00](https://openingh.openstreetmap.de/evaluation_tool/?EXP=weekdays%208-16%3B%20We%208-12)".

**Comment by Helium314** [comment] 2019-04-15 07:58
In your first link you have Th,Fr 13:30-16:00 instead of Tu,Fr 13:30-16:00. With Tu,Fr 13:30-16:00 (as it is in the link I provided) I fail to see any overlap.

**Comment by westnordost** [comment] 2019-04-15 09:13
The last rule overlaps with the second rule.

**Comment by westnordost** [comment] 2019-04-15 09:20
Hm you are right, it looks like copied the OH wrong from your link. There is no overlap for the OH in your link. I will check this again.

**Comment by westnordost** [comment] 2019-04-15 12:35
The place was tagged with StreetComplete v9. I tried to reproduce this now with StreetComplete v11 and it tagged this:
`Tu,Th,Fr 08:00-12:30, Mo,We,Th 13:30-17:00, Tu,Fr 13:30-16:00, Mo,We 09:00-12:30`
So with the current version, it is not a problem anymore. 

Apparently there was a bug in that version, I don't remember fixing anything there though and I can also not find anything relevant in the changelogs.

**Comment by westnordost** [comment] 2019-04-15 18:45
It is also quite difficult to find what the original bug was exactly that got solved, because every single line of the opening hours quest changed since then, as I converted all the code from Kotlin.

So, anyway, since this bug is fixed now, I will close this ticket as the original issue you created would be a _won't fix_ for me.

**Closed by westnordost** 2019-04-15 18:45 UTC
