### ISSUE TITLE
Move from poeditor.com to a better translation platform

### ISSUE THREAD

**Issue by osoitz** [westnordost/StreetComplete#1099] opened 2018-06-08 09:34 UTC
Poeditor has never been particularly comfortable for translators and now the original strings are hidden, instead it shows the name of the variable, which makes it worse.

I suggest considering:

HOSTED:
- hosted.weblate.org
- crowdin.com (Closed source but free as in beer for FLOSS projects)
- transifex.com (Closed source but free as in beer for FLOSS projects)

SELF-HOSTED:
- Weblate
- Pootle

**Comment by ENT8R** [comment] 2018-06-08 14:32
I can also confirm this:
![unbenannt](https://user-images.githubusercontent.com/25306497/41163591-658adcea-6b39-11e8-9424-93df18f886e5.PNG)

I have no idea at all what they thought when they introduced this feature 😄

**Comment by rugk** [comment] 2018-06-08 14:33
Maybe they thought "YOLO" – let's ruin our company? 

But seriously, maybe it is somehow configurable? I doubt they don't allow a fallback to the old behaviour.

**Comment by osoitz** [comment] 2018-06-08 14:41
OK, found it, you can set now any language as reference (dark grey menu at the right), so if you set English US as the reference language you see the original strings.

Anyway, please consider a better option.

**Comment by westnordost** [comment] 2018-06-08 18:54
> Maybe they thought "YOLO – let's ruin our company"?

:-D

Okay I think the reason why there was no default reference language set is because I changed the _English_ translations into another language, namely _English (US)_ which I guess led to _English_ being removed and thus also removed as default language. So the problem was caused by me, even though I'd argue that it is not very smart behavior by the application. 

In any case, it is fixed now, and personally I still like POEditor best of the options I have looked at. I also looked at the links you provided. So, I considered moving, but for now: no.

I will close this as solved as the original reason for this post has been solved.

**Closed by westnordost** 2018-06-08 18:54 UTC
