### ISSUE TITLE
After answering Question all question disappear

### ISSUE THREAD

**Issue by Mannshoch** [westnordost/StreetComplete#1224] opened 2018-10-05 17:24 UTC
After disappearing i wait for around 7s until de Question come back. 
I have Streetcompleete 8.0 from f-droid but i get after every question a message that says my app is to old for the country detection. It's the same time where the questions disappear. I don't know if that is the cause of this effect.

**Comment by HolgerJeromin** [comment] 2018-10-05 17:30
8.0 had a bug which resulted in wrong osm data. Thats why it is blocked. 
An update for f-droid is being prepared.

**Comment by rugk** [comment] 2018-10-05 19:31
Dupe of https://github.com/westnordost/StreetComplete/issues/1065, https://github.com/westnordost/StreetComplete/issues/724, https://github.com/westnordost/StreetComplete/issues/1159.

Basically most important link is the one to the upstream bug of the map lib: https://github.com/tangrams/tangram-es/issues/1565

**Comment by westnordost** [comment] 2018-10-05 20:01
It's not a bug, @rugk

**Comment by westnordost** [comment] 2018-10-05 20:10
@Mannshoch , the more quests are displayed on the map, the longer it takes for the questions to come back. 7s is extremely unusual, even with a lot of quests around, it should be around 0-2s. What you can do to make it faster on your phone is to disable certain quests (that pop up a lot) temporarily and focus first on others. There is nothing I can do right now to make this faster.

**Closed by westnordost** 2018-10-05 20:10 UTC
