### ISSUE TITLE
roof:levels 0

### ISSUE THREAD

**Issue by peternewman** [westnordost/StreetComplete#1778] opened 2020-04-11 17:34 UTC
I noticed in:
https://github.com/westnordost/StreetComplete/issues/582#issuecomment-326911598

> * I want to add roofs even for cases where roof:levels = 0 (some roof levels are too small to be considered a level)

Sorry TBC shortly.

**How to Reproduce**

**Versions affected**

**Comment by westnordost** [comment] 2020-04-11 18:03
duplicate of a closed bug

**Closed by westnordost** 2020-04-11 18:03 UTC
Labels: bug
