### ISSUE TITLE
Maybe some intodruction for this app?

### ISSUE THREAD

**Issue by hsimpson00** [westnordost/StreetComplete#517] opened 2017-08-20 17:38 UTC
Hi,

when testing this app, I got a bit confused about the functionallity:

-It isn't clear to me, if this app uploads every change just in time or only after hitting the button "upload answers". In fact, there is no warning message while closing the app without hitting this button, so I guess, there is a live upload?

-I wasn't aware of the fact, that you cannot review an already answered question. Maybe you could include an overwiev of all answered questions before uploading? That would be nice!

The best thing would be a welcome screen which shows up on the first time you start the app after installing (like many other apps use right now). On this screen you could give an overwiev on how this app works. And maybe it could also mention the responsibility of the user for his changes to the OSM-Database, because it's so easy to change the data.

But on the other hand, I really like your app. It is very easy to use and a great help for the OSM community! So keep on going!

Regards

**Comment by rugk** [comment] 2017-08-20 17:53
Dupe of https://github.com/westnordost/StreetComplete/issues/178

**Comment by rugk** [comment] 2017-08-20 18:23
To answer the questions:
> It isn't clear to me, if this app uploads every change just in time or only after hitting the button "upload answers". In fact, there is no warning message while closing the app without hitting this button, so I guess, there is a live upload?

There is a setting, whcih should give you a clue. "auto sync". AFAIK it is by default set to "only wifi", but you can change it. Also there is an "upload changes" button, if you want to upload the changes instantly.
When you close the app, no changes get lost, as 

> I wasn't aware of the fact, that you cannot review an already answered question.

Do you mean "revert" or "edit" by "review? If so https://github.com/westnordost/StreetComplete/issues/116 might be for you. Also see https://github.com/westnordost/StreetComplete/issues/67 for a different, rejected way to solve this.

> Maybe you could include an overwiev of all answered questions before uploading?

That rather sounds like a list of all quests. This was also proposed in on issue, but I cannot find it right now…

**Comment by hsimpson00** [comment] 2017-08-20 19:04
It's more like I know it from other editors, for example JOSM:
-After you think you are done with an are, you hit the upload button.
-Then (after a valitity check) the program gives you an overview of the changed objects (that would be the asked questions here).
-At this point you still have the option to go back and overwork your changes.
-Then you have to press send to load up your changes. From this point on you cannot change this changeset anymore.

This would be a two-step-check to prevent mistakes caused by mapping too fast (or accidentally hit the "ok" button). I think this is important for the general quality of the StreetComplete changes.

Regards

**Comment by hsimpson00** [comment] 2017-08-20 19:24
Hi, I yust read the thead #116. I think this is a very good tool, but the problem is, that you cannot overwork your changes **before** they got their way into the OSM-Database. As I give my name for every change made with this app, I would like to check the quality before the data goes online :)

Regards

**Comment by westnordost** [comment] 2017-08-20 19:28
Perhaps such a list will be added (much) later in an expert-mode, but for now, you just have to trust the app and/or check your changes after the upload.

**Closed by westnordost** 2017-08-20 19:28 UTC

**Comment by rugk** [comment] 2017-08-20 19:31
_(reply to @hsimpson00 only)_
As you correctly noticed, StreetComplete is different. And IMHO, that difference is a real key point of it.

the quests are so easy, so that you have to try very hard to make a mistake (which is not "I tapped on the wrong button.") accidentally, so there is no need for a second check. However, I already linked some issues, which are trying to help to care about the "I tapped on the wrong button."-case.

> I think this is a very good tool, but the problem is, that you cannot overwork your changes before they got their way into the OSM-Database.

I think this does not matter. And it is actually also possible to revert things before they get committed. You can control this with the "auto-upload" seting. Only (auto-)upload if you think your changes are fine, then everything is fine.

> As I give my name for every change made with this app, I would like to check the quality before the data goes online :)

I understand that, but these changes are really minimal. As I said, you cannot break many things with StreetComplete. And when I had to correct a thing, I always just pressed a wrong button or so and that is a thing you immediately notice after solving a quest. So when https://github.com/westnordost/StreetComplete/issues/116 is merged, you can fix that.
And I never had the case where I thought: Let's check whether I made everything correctly. Actualy this also makes less sense, because the idea is that with StreetComplete you walk around (or drive, or whatever…) and solve the quests. You won't have the chance to go back to the place, where you solved some quests and re-check them… and as I said, that is also not necessary.
