### ISSUE TITLE
Add the option to change the language in the settings

### ISSUE THREAD

**Issue by IVAN-RSM** [westnordost/StreetComplete#1246] opened 2018-10-28 19:25 UTC
It's very useful, because there are people like me who speak several languages ​​and want to have some applications with the language different from the system...

Thanks!

**Comment by rugk** [comment] 2018-10-28 19:34
Could also imagine this being useful for travelers/tourists, who might want to check out a term/question or so in the local language or so… :thinking:

**Comment by ENT8R** [comment] 2018-10-28 20:00
There were already at least 3 issues which wanted to propose the same: #29, #52, #1064 
And a setting like this would really make no sense IMO. Why should there be an option inside of the app if you can easily change this in your phones settings? This just adds over-complexity to the settings screen...
And I also don't think that a lot of users would even use this setting...

**Comment by IVAN-RSM** [comment] 2018-10-28 20:04
> Ya había al menos 3 temas que querían proponer lo mismo: [# 29](https://github.com/westnordost/StreetComplete/issues/29) , [# 52](https://github.com/westnordost/StreetComplete/issues/52) , [# 1064](https://github.com/westnordost/StreetComplete/issues/1064)
> Y una configuración como esta realmente no tendría sentido IMO. ¿Por qué debería haber una opción dentro de la aplicación si puede cambiar esto fácilmente en la configuración de su teléfono? Esto solo agrega una complejidad excesiva a la pantalla de configuración ... 
> Y tampoco creo que muchos usuarios usen esta configuración ...

The problem is that Android does not have some languages ​​that this and many of the applications have. Apart from the utility it supposes for people who speak several languages, as I mentioned.

**Comment by westnordost** [comment] 2018-10-29 22:57
As @ENT8R pointed out, this is a duplicate of already closed issues. Sorry, I won't do this.

**Closed by westnordost** 2018-10-29 22:57 UTC
