### ISSUE TITLE
Vegetarian/vegan quests have too condensed layout in German

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#1284] opened 2018-12-02 21:11 UTC
The "yes" and "no" is literally mostly one character per line.

![grafik](https://user-images.githubusercontent.com/11966684/49344874-134da280-f67d-11e8-8615-9201859035e5.png)

**How to Reproduce**

0. Set language to German.
1. Open a vegan/vegetarian quest.

**Versions affected**
SC v8.3
LineageOS 14.1
portrait layout
Full HD screen AFAIK
5 inch screen

**Potential solution**
* What I would really suggest is to use the [capital ẞ](https://de.wikipedia.org/wiki/Gro%C3%9Fes_%C3%9F) ([English Wikipedia](https://en.wikipedia.org/wiki/Capital_%E1%BA%9E)). This looks nicer (When I looked at it closely right now, I just thought it was written wrongly and only then noticed that it is of course written in capital letters and the "SS" workaround is used.) and also saves a little space.
* As for the Yes/No – these replies are so short, and you loose so much whitespace in the width as there needs to be this big padding around the separator line.
  Maybe you can put these, and only these two short items, on top of each other, so they are on top and have enough width (if you take the two columns together, I think, l they have). And the height has certainly enough space.
  Generally a more flexible layout could benefit it. Maaybe it could e.g. already right now just break the way too long "Nicht beantwortbar" on three lines and then there is enough space for "Nein" and "Ja" to be written as proper words.
* An awesome thing would of course be, if it could automatically add hyphens and break the words at the correct positions, just as the [hyphens CSS property would do it](https://developer.mozilla.org/docs/Web/CSS/hyphens), if it is set to "auto".
  A way to make this work without a big hyphenation engine (or whatever this is called – if something like this is needed?) may be to ask translators to define [soft breaking chars](https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens#Suggesting_line_break_opportunities).

**Comment by westnordost** [comment] 2018-12-02 21:52
Android Lollipop and upwards understands `&#173;` (soft hyphen). However, as long as StreetComplete still supports versions below 5.1, I do not want to litter POEditor with `&#173;` because it will look like a bug in Android 4.x and maintaining translations with and without soft hyphens parallel to each other is too much effort. When Android 4.x is dropped (some time next year probably), we can do it.

The soft hyphens do not solve the problem though, only make the words be broken up at perhaps better positions:
![device-2018-12-02-224929](https://user-images.githubusercontent.com/4661658/49345398-8dcdf080-f684-11e8-9b72-97faae350430.png)

**Comment by westnordost** [comment] 2018-12-02 23:14
> Can't you just do a "string replace" on platforms that do not support it?

I always could do "something", the question is whether it is worth the effort.

**Comment by rugk** [comment] 2018-12-03 08:51
Well… I just guess that a string replace would be very simple thing in contrast to "maintaining translations with and without soft hyphens parallel to each other". :smile:

**Comment by westnordost** [comment] 2019-08-28 15:03
I am closing this report as a duplicate of #1372 because that report describes the issue more generally.

**Closed** 2019-08-28 15:03 UTC
Labels: duplicate
