### ISSUE TITLE
minor bug: animation of solved quests is cropped while uploading

### ISSUE THREAD

**Issue by Norwi** [westnordost/StreetComplete#1910] opened 2020-06-21 21:15 UTC
The counter of solved quests is cropped while uploading changes.

![0001-0250](https://user-images.githubusercontent.com/18899671/85235415-f15d7180-b414-11ea-9a49-9ac35bdda1e4.gif)

**How to Reproduce**
- press upload button

**Versions affected**
- Android 10
- StreetComplete v20.2

**Comment by m-rey** [comment] 2020-06-21 22:33
Can confirm. It's not limited to the latest version, but also existed in many previous releases.

**Comment by peternewman** [comment] 2020-06-22 11:24
This is a duplicate of https://github.com/westnordost/StreetComplete/issues/1635 (although I see that didn't get re-opened when I confirmed it was still broken. However @Norwi has a nicer demo of the fault.

**Comment by westnordost** [comment] 2020-06-28 17:35
Is this groundhog day? :-(

I'll try to fix it

**Closed** 2020-06-28 17:56 UTC
Labels: bug

**Comment by peternewman** [comment] 2020-06-29 21:51
Looks like you found Punxsutawney Phil @westnordost , this is finally gone for me! :partying_face:

**Comment by Norwi** [comment] 2020-06-29 22:31
Thank you! It's gone for me as well.
