### ISSUE TITLE
How fast are map updates?

### ISSUE THREAD

**Issue by TobiasMie** [westnordost/StreetComplete#692] opened 2017-11-16 18:26 UTC
More than a week ago I added some streets to osm using Bing images and plan to complete this streets with StreetComplete. After a few hours the quests appear but the map of the streets isn't displayed yet. I set the cachesize to 1 MB and clear the cache but the map does not update. Is it just me or how long will it takes until the new streets are displayed?
I use Version 3

**Comment by cyclingcat** [comment] 2017-11-16 19:25
I noticed the same some weeks ago and just double-checked it: StreetComplete v2.3 quests for the opening times of a (branch) bank in a village nearby. However, the bank doesn't exist anymore, there's a hairdresser in this building now.

This was corrected in OSM about six weeks ago, but SC still quests for the opening time of this "Kreissparkasse". I just deleted the cache but the quest remains the same.

The cycling cat

**Comment by TobiasMie** [comment] 2017-11-16 21:44
![](https://i.imgur.com/ZZbaiG8.png)

**Comment by HolgerJeromin** [comment] 2017-11-16 21:57
The quest and the map are complete different things.
#562 is an issue about old quests. 
The map is imo updated in a few days.

**Comment by TobiasMie** [comment] 2017-11-16 22:04
Another interesting point is, that a street I added several weeks ago is displayed in some zoomlevels, in other not.
![](https://i.imgur.com/Du3FSH8.jpg)
![](https://i.imgur.com/JpqKOlf.png)

**Comment by westnordost** [comment] 2017-11-17 19:53
The app has no control over the map in respect of how often the map is updated with current OSM data. You might influence this by clearing the cache.

Downloaded quests are not held in the cache (as much as if you clone a repository on github, it's also not a "cache"), thus clearing the cache does not clear the downloaded quests. The other part of this issue is a duplicate of #562

**Closed** 2017-11-17 19:53 UTC
Labels: duplicate

**Comment by claudiush** [comment] 2018-03-18 06:49
@westnordost Can you clarify what you mean by "clearing the cache"? Are we talking about the app's cache via the Android settings? Wouldn't that also reset my issue counter?

I just ran into the same issue as TobiasMie: Was mapping with StreetComplete in a new area I'm vacationing in. Found streets and buildings missing and added them via JOSM. Updating quests in SC I get them to show on a very outdated map. also tried reducing map cache to 1MB but that seems to have zero effect even when deliberately scrolling across the map to pull new map data.

Would it be possible to add a "Clear map cache" button into the settings (with a clear warning about side effects of increased data usage to re-download)?

**Comment by ENT8R** [comment] 2018-03-18 07:13
> Are we talking about the app's cache via the Android settings? Wouldn't that also reset my issue counter?

Yes, it's the normal cache of the app which can be deleted via the android settings. Your quest counter won't be reset if you just clear the cache. This is saved somewhere else.

---

The reason why the solution above might not work for you is that we switched the mapserver back in January because the old (Mapzen) sadly shut down (#747). This means that we use now a different server which is not a commercial server but a voluntary project by @Akasch 👍 so the map is not that up-to-date like the old Mapzen server. (see also #835)
