### ISSUE TITLE
rotating the phone unsets current selection of surface type

### ISSUE THREAD

**Issue by waldyrious** [westnordost/StreetComplete#219] opened 2017-05-11 08:51 UTC
I recently noticed that if I start a street surface selection (e.g. I pick "paved (generic)" but not one of the sub-types yet) and rotate the phone before clicking OK, the selection I had made disappears and I have to pick the generic type again. The same happens if I had already picked a subtype, but not clicked OK yet.

This is mostly just inconvenient for users, but hopefully the fix is simple :)

**Comment by matkoniecz** [comment] 2017-05-11 13:35
Duplicate of #197

**Comment by waldyrious** [comment] 2017-05-12 09:26
Ah yes, I did search before opening this issue, but somehow missed that one. Thanks for the pointer. I would close this as a duplicate, but since that one is closed as wontfix, I'd rather leave this open, as a signal that I consider this worth fixing (or replacing with a different mechanism that avoids this problem, as described in #197).

**Comment by westnordost** [comment] 2017-05-13 21:15
See @matkoniecz

**Closed by westnordost** 2017-05-13 21:15 UTC
Labels: duplicate
