### ISSUE TITLE
Display complete tag info

### ISSUE THREAD

**Issue by Rudloff** [westnordost/StreetComplete#1513] opened 2019-08-01 12:36 UTC
**Use case**

When completing quests in a dense urban area, it can sometimes be hard to guess which exact feature StreetComplete is asking about.
One recent example is when it asked about parking fees in a place where there was both a surface parking spot and a very close underground parking entrance, so I was not sure which one it was asking about.

**Proposed Solution**

Being able to display the OSM data about the node could help differentiate them (by seeing what other info we already have).

I guess another solution could be to have more details on the map, to see where the node is placed compared to other surrounding nodes (but it would also make the map heavier and harder to read).

**Comment by ENT8R** [comment] 2019-08-01 12:49
Duplicate of #471

**Comment by rugk** [comment] 2019-08-01 16:35
> Duplicate of #471

Displaying != editing, though.

**Comment by westnordost** [comment] 2019-08-01 17:24
Yes, but still. If/when there is such a mode where one can see the raw tags, then it will also be possible to edit them.

**Closed by westnordost** 2019-08-01 17:24 UTC
