### ISSUE TITLE
17.0beta3 Creating note offline makes entire map vanish

### ISSUE THREAD

**Issue by peternewman** [westnordost/StreetComplete#1719] opened 2020-02-02 22:01 UTC
**How to Reproduce**
When you're offline and it's showing a part of the map, clicking the (!) to add a note makes that all vanish. It doesn't come back closing and reopening the app, or zooming or doing a force stop even.

It only returns when you get an Internet connection again

**Versions affected**
17.0beta3
Android 9

**Comment by Atrate** [comment] 2020-02-02 22:06
Can reproduce on beta2 as well, Android 10

**Comment by peternewman** [comment] 2020-02-02 22:06
Ah, I couldn't remember if I had it on beta2 or not.

**Comment by westnordost** [comment] 2020-02-02 22:34
Can reproduce. This can not be fixed in StreetComplete but must be fixed in tangram-es, if they acknowledge it is a bug. Apparently if the displayed scene is reloaded, which is done in this case, tangram-es tries to fetch the tiles anew even if they are already in cache.

In any case, as it is not critical, I do not expect a fix soon. So, in the meantime, what is the lesser evil?:
- disable #1589 (@ltog)?
- or live with this (#1719)?

@peternewman Do you often use the app completely offline? Does it even work out properly? Are you sure that v16.x and earlier versions did *not* have the same problem, that it is a new problem?

**Comment by peternewman** [comment] 2020-02-02 22:56
> Can reproduce. This can not be fixed in StreetComplete but must be fixed in tangram-es, if they acknowledge it is a bug. Apparently if the displayed scene is reloaded, which is done in this case, tangram-es tries to fetch the tiles anew even if they are already in cache.

That sounds fairly clearly like a bug to me personally, I can understand wanting the latest data, but if there's no connection or the tile server is down and there in the cache already it seems daft not to serve up the cached ones.

> In any case, as it is not critical, I do not expect a fix soon. So, in the meantime, what is the lesser evil?:
> 
>     * disable #1589 (@ltog)?
> 
>     * or live with this (#1719)?

Option three, disable #1589 when there is no network connection (i.e. work around the bug)? Or make it a config option, but the former seems neater and more seamless to me.

> @peternewman Do you often use the app completely offline? Does it even work out properly? Are you sure that v16.x and earlier versions did _not_ have the same problem, that it is a new problem?

Exclusively, or more accurately I use StreetComplete almost exclusively via WiFi, so often caching offline, but sometimes via street WiFi too while available, or while dropping in and out of intermittent WiFi. The app generally works fine (aside from not fetching enough quests/bits of map beforehand, there used to be, or sometimes were some issues about zoom levels where I guess only some levels had been cached and I had to zoom out and then back in to get a cached one). But generally it works fine. I rarely add notes directly (only via the ... menu on a quest), so I don't really know if this used to happen. I don't remember seeing it before.

**Comment by westnordost** [comment] 2020-02-02 22:58
> I rarely add notes directly (only via the ... menu on a quest), so I don't really know if this used to happen. I don't remember seeing it before.

I just tested it with an old version. It used to work.

**Comment by westnordost** [comment] 2020-02-02 23:01
Okay, regarding #1589, I will probably disable this one until it is fixed in the library, because #1589 is mostly just a convenience feature while this problem here would make it outright impossible to use the create-note feature for the group of people that use the app like you do.

**Comment by peternewman** [comment] 2020-02-02 23:12
> Okay, regarding #1589, I will probably disable this one until it is fixed in the library, because #1589 is mostly just a convenience feature while this problem here would make it outright impossible to use the create-note feature for the group of people that use the app like you do.

Okay, can you easily sense if the device has a network connection and use that to change the behaviour. #1589 doesn't directly impact me generally, but I raised #1609 which can sometimes be related (i.e. potentially wanting to disable 3D mode), so a more general solution would be nice if it's not too hard.

Plus I guess my usage may be rather niche and it seems a bit unfair for too many others to suffer due to that.

**Comment by westnordost** [comment] 2020-02-02 23:20
Yes it would be possible to find out if the device is connected, but I'd like to keep the amount of workarounds to a necessary minimum. It could also be technically connected, but the connection is so bad that basically nothing gets through.

**Closed** 2020-02-03 12:08 UTC
Labels: bug
