### ISSUE TITLE
Note templates

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#1191] opened 2018-09-07 19:55 UTC
**Use case**
* The "closed shop" thing: https://github.com/westnordost/StreetComplete/issues/450 (and many dupes)
* repetitive notes, in general, such as: "please split way", "disused/closed", common answers to quests (like foot) that we did not include (e.g. in orchard quest or so), …

**Proposed Solution**

* A dropdown when creating a note, where you can select one of your predefined notes, which are then added into the notes field
* an entry in the settings, where you can add/edit/delete these templates

**Comment by matkoniecz** [comment] 2018-09-07 21:09
> The "closed shop" thing: #450 (and many dupes)

Can you read them? It was WONTFIXed by @westnordost and at least once there was thorough explanation for why he considers a note template to be a good idea.

Proposing again something that you know to be duplicate of something rejected by author of program is a poor idea.

Very rarely it may be acceptable when accompanied by a new idea, analysis or information but nothing like this is present here.

**Comment by matkoniecz** [comment] 2018-09-07 21:14
I get that you think that this note template should be available and that sound should be disablable be a SC setting.

But if you disagree with @westnordost you may be sad or irritated or create your own version of StreetComplete or...

On the other hand spamming @westnordost with the same request over and over again is more likely to discourage him from working on StreetComplete than force him to satisfy you vision.

Please stop creatng duplicates.

**Comment by rugk** [comment] 2018-09-08 08:52
> It was WONTFIXed by @westnordost and at least once there was thorough 

Sorry, did not found it there. His close comment was:
> SC does not delete things, this'd open another can of worms. In the case that a quest is not answerable, always simply leave a note.

Also just checked some other issues (https://github.com/westnordost/StreetComplete/issues/575#issuecomment-326085798 and https://github.com/westnordost/StreetComplete/issues/1153). Of course I also searched for "note template" before opening this issue and could not find anything.

So I do not knew and I am still not sure where this is a duplicate of.
Feel free to link this to the duplicate and I can close this.

Maybe I've mentioned this idea earlier somehow, but I could not find an issue, where this is mentioned/described in the way I did. Also, remember, that solving the (obviously often requested feature) of https://github.com/westnordost/StreetComplete/issues/450, is only **one** aspect.

**Comment by rugk** [comment] 2018-09-08 09:12
To make it clearer, let me explain one example: "please split way" could be a useful template. This has nothing to do with @westnordost's previous rejection of "should not delete nodes" and of course SC does not. And it may be a common thing that usually needs to be done (i.e. as for SC it's more or less a "known issue" that it cannot split ways).

**Comment by westnordost** [comment] 2018-09-12 21:39
I thought I have written that before, but I do not want note templates. Main reason is that if a note appears as if it is (semi-)automatically created, it is not trusted in the way that a personal message is (which is also more likely to contain additional information, i.e. what is there now etc.).

**Closed by westnordost** 2018-09-12 21:39 UTC

**Comment by rugk** [comment] 2019-02-18 09:15
And if you - like GitHub e.g. allows it with reply templates - do not provide any defaults there. Then users will need to write the templates themselve, which makes them actually look not auto-generated and users will likely only write templates for things that really happen often.
And things like "please delete, does not exist anymore" have been requested as "Other answers" repeatedly, so these could be solved by that. And whether users need to write that same string again or again or have a template is just a convenience-feature (i.e. makes mapping faster or so). The result is actually the same considering that I do not see many variations how users can express that a building or so is not there anymore.
