### ISSUE TITLE
Don't show solved quests

### ISSUE THREAD

**Issue by DamienCassou** [westnordost/StreetComplete#185] opened 2017-05-05 08:25 UTC
1. solve a quest
2. the quest disappears from the map
3. upload answers (I that sync turned off)
4. download new quests
5. the quest you solved is sometimes back

That's annoying because my map contains quests I solved and I keep clicking them.

**Comment by westnordost** [comment] 2017-05-05 09:00
What?! If this is real, it may be a major issue! Thank you for reporting it, it is very important that this is tracked down. I need the following info from you:

- which quest type
- What did you answer?
- Check you OSM history: was the first answer correctly applied? Please post the link of the changeset
- Optional: what happens if you answer the quest a second time? Please post the link to the changeset

On 5 May 2017 10:25:36 CEST, Damien Cassou <notifications@github.com> wrote:
>1. solve a quest
>2. the quest disappears from the map
>3. upload answers (I that sync turned off)
>4. download new quests
>5. the quest you solved is sometimes back
>
>That's annoying because my map contains quests I solved and I keep
>clicking them.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/185

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by rindlerblabla** [comment] 2017-05-05 11:46
I had the same problem with street name on this one. Kept updating a couple of times and then the quest disappeared. https://www.openstreetmap.org/way/430812314/history . Don't know if you could do anything with that info though.

**Comment by westnordost** [comment] 2017-05-05 16:48
@rindlerblabla: Did the marker not disappear at all or did the marker disappear and later reappear? Did the number next to the star icon increase for every answer you gave? Or did it only increase once? If yes, did it increase when you first answered the quest or when you last answered the quest? Was there any kind of error message? (Like "upload failed, See log")

**Comment by rindlerblabla** [comment] 2017-05-05 17:00
It disappeared and later reappeared. Sorry, don't really remember more. Haven't had the problem since that specific road. Reappeared several times. No error messages. But the update must have gone through in a previous attempt since the street name was visible in the background layer. Will update this post if it appears again.

**Comment by matkoniecz** [comment] 2017-05-11 13:22
@DamienCassou 

> download new quests

Is it done using manual download? In that case #215 would be duplicate of this issue.

**Comment by westnordost** [comment] 2017-07-04 18:38
It'll be a duplicate of that issue.

**Closed by westnordost** 2017-07-04 18:38 UTC
Labels: feedback required
