### ISSUE TITLE
Multiselection of quests

### ISSUE THREAD

**Issue by a123qwertz567** [westnordost/StreetComplete#2353] opened 2020-12-07 21:19 UTC
**Use case**

Save time when adding tags for whole streets and areas. For example for a whole street of townhouses you have to select every house one by one, while the map and ui flings around.

**Proposed Solution**

Add multi select support for quests, so you can tag whole streets more easily.

**Comment by smichel17** [comment] 2020-12-08 04:03
Duplicate of #73 (and others, which you can find from #73)

**Closed by smichel17** 2020-12-08 04:03 UTC

**Comment by a123qwertz567** [comment] 2020-12-08 04:52
Oops, wasn't able to find these issues.
