### ISSUE TITLE
Edit multiple quests of the same type simultaneously 

### ISSUE THREAD

**Issue by Aypac** [westnordost/StreetComplete#274] opened 2017-05-30 21:16 UTC
I live in a suburban area, where there are tons of houses in a row, that have the same amount of levels. It is currently very tedious to add that information currently. It would be super awesome to be able to select several (maybe limit to 20?) quests (of the same  type) and give the same answer. This is also true for some streets types (since the same street/road might be split into many parts).

**Comment by matkoniecz** [comment] 2017-06-01 15:37
duplicate of #264, #73, #149

**Closed** 2017-06-02 17:33 UTC
