### ISSUE TITLE
UI improvements for surface quest

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#405] opened 2017-07-18 10:01 UTC
While answering surface quests one needs to scroll a lot, this could be easily solved.

You need to:
1. Select the quest.
2. Scroll to see all general types of pavements.
3. Click one of them to see and select a specific type.
4. Select and click ok.

Idea: Instead of the three wide images vertically aligned show three small images horizontally aligned to show the generic types so that no scrolling is needed anymore, this would remove 2.

After the users selected one of the general types you can show the large general image.

**Comment by westnordost** [comment] 2017-07-18 14:34
This is a duplicate of another ticket that is floating around somewhere, it is not forgotten.

**Closed by westnordost** 2017-07-18 14:34 UTC

**Comment by wolftune** [comment] 2017-08-07 17:46
If you could find the other ticket and link it here, then it would allow those who land here to see the actual ticket.

**Comment by Binnette** [comment] 2017-08-07 20:53
See #393 and #76
