### ISSUE TITLE
Change the UI so I can chose which quest to answer for a given map feature

### ISSUE THREAD

**Issue by afmenez** [westnordost/StreetComplete#587] opened 2017-09-11 19:03 UTC
Currently, when there is more than one information missing for a given item (build number and number of floors), I have to fill them all in the predefined order.  But I would like to choose which quest I want to answer: I may be able to count the floors from a distance, before I can see the build number.  Another example is a street which I can see the the kind of surface from the corner but don't want to walk the entire street checking for road signs.

**Comment by rugk** [comment] 2017-09-11 20:19
Likely a Duplicate of https://github.com/westnordost/StreetComplete/issues/124

**Comment by afmenez** [comment] 2017-09-11 20:25
Yes, it is.  Sorry for that.

**Closed** 2017-09-11 20:26 UTC

**Comment by forteller** [comment] 2019-07-27 23:18
I actually disagree that this is a duplicate of #124, if I understand both correctly.

124 says, as I understand it, that after clicking on one quest (and filling it out), you should be able to go directly to the next quest "under it", instead of first going back to the map and then clicking the new quest. Kinda like how you can swipe from one pokemon to the next in Pokemon Go.

This issue (587), however, says, as I understand it, that you should be able to see more than just the "top level" quest before clicking it.

If I have understood this correctly, then I would like to open this issue again (unless there are any other issues addressing this).

My reason:

Some times there are three quests for one street: Surface, lighting and speed limit.

If you just sit on the bus, driving by a street like this, you might notice one of the things while you pass by the street, but not the other things. But if you the thing you notice is not the "top level" quest, then you can not contribute anything.

Let's say you only notice that there are lights in the street, and you have no idea about the surface. If you have to answer the surface quest first, then you can not contribute at all. You should be able to, IMO.

Thank you!

**Comment by westnordost** [comment] 2019-07-28 07:00
Actually, I understand this as a duplicate of #124 and so did the OP.

But, the feature you describe used to be implemented in older versions - I eventually disabled this jumping to the next quest because it did not feel good. Partly, if I remember correctly, due to technical limitations: the sliding to the next quest was very jerky because the map needs to refresh after solving a quest which is very slow. Partly, this behaviour is often not what one wants. For example if you go down a street to map addresses, it is annoying to be automatically prompted for building levels and roof shape as well.
