### ISSUE TITLE
Groups for Quest selection?

### ISSUE THREAD

**Issue by natrius** [westnordost/StreetComplete#1746] opened 2020-02-27 16:24 UTC
**Use case**

Group the quests at all and make the whole grouping selectable/deselectable

- Roads
- Walking/Biking
- Buildings
- Company
- Disability
- Public transport
- Parking
- Accessibility

But i guess the problem is that some quests should be in two groups sometimes. Actually, why not? If you select the one in the first grouping you select the one in the other group as well. I see no problem with that as well. 

Aaand... Well, i found my other suggestion already, "let me reset everything" :p

EDIT: Oh, i found now through looking to other issues that i can sort the quests as well. I mean, actually, not i can see its written there on top as well. face -> desk

**Comment by jtracey** [comment] 2020-10-14 15:56
Related: #1654.

This is, IMHO, becoming a more and more necessary feature as the number of quests proliferates. Specifically for sorting, not just enable/disable. My guess is that most users, when prioritizing their quest selections, end up using [insertion sort](https://en.wikipedia.org/wiki/Insertion_sort). This is fine when the number of quests is small, but having just installed StreetComplete on a fresh device, it took much longer than I expected (which makes sense for a O(n^2) algorithm). One UI solution that comes to mind is letting the user sort by achievement (mobility, sixth sense, etc.). Quests associated with more than one achievement could be ranked according to the highest one they're a part of, or by summing priorities so that shared quests get higher priority. Once the user has done that sort of macro-scale sorting, individual sorting of quests should go faster.

Another possible UI to address the problem I'm mentioning, but not directly related to this issue, would be to provide a UI that lets users more easily use another sort algorithm. E.g., ask a series of "which of these should be higher priority?" questions according to [merge sort](https://en.wikipedia.org/wiki/Merge_sort), and spitting out the sorted list at the end.

**Comment by westnordost** [comment] 2020-12-08 15:57
closing as duplicate of #1654

**Closed by westnordost** 2020-12-08 15:57 UTC
