### ISSUE TITLE
Undo button

### ISSUE THREAD

**Issue by Luensche** [westnordost/StreetComplete#522] opened 2017-08-21 09:20 UTC
Yesterday, while testing this app, I was a little bit to fast and suddenly the wrong house number was submitted. So is it possible to add an undo button, maybe for the last two submissions?

**Comment by matkoniecz** [comment] 2017-08-21 11:32
see search results for "undo": https://github.com/westnordost/StreetComplete/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20undo

**Comment by westnordost** [comment] 2017-08-21 11:53
Duplicate

**Comment by rugk** [comment] 2017-08-21 11:53
Duplicate of https://github.com/westnordost/StreetComplete/issues/116

**Closed by westnordost** 2017-08-21 11:53 UTC
