### ISSUE TITLE
App asks for opening hours even there are already indicated

### ISSUE THREAD

**Issue by gupascal** [westnordost/StreetComplete#480] opened 2017-08-14 08:36 UTC
Hello,

For this POI ( http://www.openstreetmap.org/node/4864035556#map=19/45.81178/3.11078 ), StreetComplete displays a quest for opening hours even if they are already indicated.

Hope this help.

Edit: I use v1.1

**Comment by westnordost** [comment] 2017-08-14 09:04
I was about to ask that. In 0.14, this would happen more frequently because the source where the data was pulled from (Overpass) is not always up-to-date with where the data is pushed to (OSM Api).

I cannot reproduce this, the opening hours quest is not displayed for me. This means, that you are simply looking at outdated data. Next time the app decides to download the data there, the quest will vanish. Quests are usually marked as to-be-redownloaded after one week, so it should be already.

To confirm this behavior, could you please go to the map there and hit the "scan for quests here" button? Does the quest vanish?

If it does not vanish, could you please answer the quest and upload your answer? The app should detect that there is a conflict and not apply your answer, instead, mark the whole area around that quest as to-be-redownloaded. So, if you then hit the "scan for quests here" button, the quest should vanish. Does it?

**Comment by gupascal** [comment] 2017-08-14 09:22
Well, opening hours were added 9 days ago for this POI. It's more than a week.

I already tried (and retried) the "Scan for quests here" button but the quest stays here.

When I answered the quest and synced my answer, indeed, no changes were committed in OSM and the quest vanished.

So, it seems that something is broken with both the "Scan for quests here" button and the quests auto refresh.

**Comment by westnordost** [comment] 2017-08-14 09:33
> I already tried (and retried) the "Scan for quests here" button but the quest stays here.

Ok, that's a bug then.

> When I answered the quest and synced my answer, indeed, no changes were committed in OSM and the quest vanished.

Good, so that part is working. This will help to find the problem.

**Comment by westnordost** [comment] 2017-08-14 09:35
> something is broken with [...] the "Scan for quests here"

This one is working fine though as well. The "scan for quests here" button does not re-scan quests which it doesn't consider as to-be-redownloaded. The only thing that is not working well is the detection when something is marked as to-be-redownloaded.

**Comment by westnordost** [comment] 2017-08-25 20:27
Okay, I checked the source and the tests, it all looks good and runs through ([It is also not exactly that much code](https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/data/download/QuestDownload.java#L137-L156)). Further, I retested the whole feature by setting the refresh interval to 1 minute. Everything works as expected. So, I do not see any bug here, only perhaps behaviour that might be unclear to the user:

1. Quests are cached. When you are looking at the map, you are not looking at some "live" version but the version that was downloaded when it was downloaded.
2. It is only re-checked "every now and then" if this quest should be still displayed. The user has no control over that. Specifically, pressing the "scan for quests here" button doesn't make a difference.

**Closed by westnordost** 2017-08-25 20:27 UTC
Labels: bug

**Comment by chrisdebian** [comment] 2017-08-25 20:47
Ahh, thanks; I had assumed that pressing the quests button, would update
things. My mistake.

Chris

**Comment by Phyks** [comment] 2017-11-28 08:31
Hi,

I've just noticed this issue, with a quest to fill-in [this POI](https://www.openstreetmap.org/node/2144646154) opening hours, which have already been filled 6 months ago. 6 months ago seems to be a lot for just some cache invalidation to happen.

> It is only re-checked "every now and then" if this quest should be still displayed. The user has no control over that. Specifically, pressing the "scan for quests here" button doesn't make a difference.

I am not sure to fully understand the behavior of the cache, but wouldn't it be possible to invalidate the cache when scanning for new quests here?


_Note_: I am using StreetComplete 2.3 from F-Droid. I cannot test on later versions since they are not available on F-Droid :/

**Comment by westnordost** [comment] 2017-11-28 12:39
Invalidated quests (quests downloaded more than a week ago) are not deleted. They are only deleted/added when exactly that quest, in this case, the opening hours quest, is re-downloaded. 

On downloading quests, either manually via the menu or automatically, not all possible quest types are (re-)downloaded, but only those that are next in line (=highest importance that have not been downloaded yet, and if downloaded already, have been invalidated).

**Comment by Phyks** [comment] 2017-11-30 13:59
Ok, thanks for the explanation. Not sure what can be technically done to enhance UX, but it is quite frustrating to spend some time adding a few opening hours and discover when uploading that they were already all filled-in :/

**Comment by westnordost** [comment] 2017-12-01 00:20
The easiest way to prevent this is to set autosync to "on" so that changes are immediately uploaded and conflicts immediately detected.

Am 30. November 2017 20:59:44 GMT+07:00 schrieb Lucas Verney <notifications@github.com>:
>Ok, thanks for the explanation. Not sure what can be technically done
>to enhance UX, but it is quite frustrating to spend some time adding a
>few opening hours and discover when uploading that they were already
>all filled-in :/
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/480#issuecomment-348195519

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Phyks** [comment] 2017-12-15 16:41
> The easiest way to prevent this is to set autosync to "on" so that changes are immediately uploaded and conflicts immediately detected.

This automatically detects conflicts, but one still has to fill-in data. I did it for now, but today I got back the issue. Basically, I was at a major square with lots of segments showing quest "What is the type of paving on this road?". I tried to fill them, and it seems all of them were already filled (my number of stars did not increase). I was using autosync set to "on" so I saw it, but StreetComplete still did not invalidate the cache for some reason and there was no way to flush all these old quests without answering them apparently :/

**Comment by westnordost** [comment] 2017-12-16 01:31
Did the app after answering one of these quest trigger a new download of quests? (a toast pops up then)

Am 15. Dezember 2017 23:41:02 GMT+07:00 schrieb Lucas Verney <notifications@github.com>:
>> The easiest way to prevent this is to set autosync to "on" so that
>changes are immediately uploaded and conflicts immediately detected.
>
>This automatically detects conflicts, but one still has to fill-in
>data. I did it for now, but today I got back the issue. Basically, I
>was at a major square with lots of segments showing quest "What is the
>type of paving on this road?". I tried to fill them, and it seems all
>of them were already filled (my number of stars did not increase). I
>was using autosync set to "on" so I saw it, but StreetComplete still
>did not invalidate the cache for some reason and there was no way to
>flush all these old quests without answering them apparently :/
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/480#issuecomment-352052397

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Phyks** [comment] 2017-12-17 19:05
I tried to answer a few quests waiting for a trigger to download new quests, but did not get any such thing. I then clicked the "look for additional quests here" entry, but it did not remove these extra quests either :/
