### ISSUE TITLE
Optionally give more details on object

### ISSUE THREAD

**Issue by JensErat** [westnordost/StreetComplete#1326] opened 2019-02-01 19:09 UTC
**Use case**
Add a clear and concise description of *your use case* and what you thus think is missing, and why. 

In Stuttgart, Germany, currently a large new railroad tunnel is built. Part of this seems to be a small rescue connection between two neighbored tunnels. This was given as a quest ("is this pathway still in construction").

This pathway was somewhere between a busy road and the middle of nowhere in dense bushes. There is no reason to build a pathway here -- on the surface at least.

https://www.openstreetmap.org/note/1652865 

**Proposed Solution**
There may be several different solutions for your idea or use case, add your deliberations about it here to help out sort out the best one.
Also, add screenshots or blueprints to visualize your idea, if applicable.

I propose to optionally show all details on an object (similar to the attribute list in Open Street Map). This would enable to understand what might be wrong, especially in such cases where you'd open map issues otherwise. This is not required in 99,9% of all quests, but another button in the "More answers" menu.

**Comment by ENT8R** [comment] 2019-02-01 19:22
Duplicate of #471

**Comment by matkoniecz** [comment] 2019-02-01 19:35
I thought about special message for construction quest for ways tagged as tunnels ("Is this pathway in tunnel completed?" or something similar).

**Comment by JensErat** [comment] 2019-02-01 20:18
#471 sounds great, although I'd already be happy on a "small" solution. Editing with some auto-completion and checks is much more complex than simply dumping the current values. I would even be fine dropping back to a fully-fledged computer editor for editing complex stuff I found, but to decide whether this is required a simple list of the labels would be helpful already. 

Regarding @matkoniecz comment: if I had to choose amongst "repairing" this special kind of quest vs. getting all tag details, I'd prefer latter -- although StreetComplete's idea is "keeping it simple" for sure. But in those rare cases I'd prefer a general solution that also helps in other cases.

**Comment by rugk** [comment] 2019-02-01 20:43
Having "keeping it simple" in mind, I want to propose a somewhat different solution, which would also not overlap (be a dupe) of #471:
Maybe instead of showing the "RAW" tags, we just let the user click on an (i) or so (that may be subject to change) and then show some details about the object. https://github.com/westnordost/StreetComplete/issues/1270 already went into that direction, but is only about the vertical location (floors).

Maybe have a small "popup"(?) that then shows an icon for the `building` (or so – we should already have these due to the building type quest) or amenity (shop) and some _selected_ details, such as "construction". (which would display a message "Element in construction" or so). Just some kind of bullet list with _parsed_ data from OSM to better identify an object.

**Comment by JensErat** [comment] 2019-02-01 20:46
@rugk this feels like exactly what I wanted to propose. If you feel you need more information, accept (partially) getting out of the comfort zone and get a somewhat technically dump of the object's details. And I'd love to have a general fallback, so we'd probably have to dump all labels because otherwise "the relevant one" will be missing again.

**Comment by rugk** [comment] 2019-02-01 20:49
No, no, I meant no technical dump. I really meant a "parsed, selected list of important labels". SC is not really made for experts. (so that dump may only be possible with an expert mode, ref https://github.com/westnordost/StreetComplete/issues/471 again)
We should be able to make such a list of important ones – I mean we constantly need to select/find the "important" keys/tags for some specific quests, too, so I don't consider this impossible. If a user notices a tag, they can just make a PR. :smile:

**Comment by westnordost** [comment] 2019-02-02 16:41
I can show in this case "in the tunnel:" in front of the question, like here:
https://github.com/westnordost/StreetComplete/issues/1270#issuecomment-455805989

**Closed** 2019-02-03 19:01 UTC
Labels: enhancement

**Comment by JensErat** [comment] 2019-02-08 20:58
It definitely fits the very specific case, but I'd also love to see something more general.
