### ISSUE TITLE
Credits menu gets broken if system language is changed while app is started

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#2103] opened 2020-09-21 18:31 UTC
For start, I really like the new credit menu!

**How to Reproduce**
Start StreetComplete, change system language, get back to credit menu

"See the complete list on GitHub" is also in the old language.

No idea is it just my phone, just very old Android due to unfixable bug or is it indicating some problem.

Restarting app fixes the problem.

**Versions affected**
https://github.com/westnordost/StreetComplete/commit/14bf6e83eb25b92eb4c237900c1235069c8ce0c6 StreetComplete, Android 6.0.1 MMB29M
![Screenshot_2020-09-21-20-23-16-343_de westnordost streetcomplete debug](https://user-images.githubusercontent.com/899988/93805925-af78dd00-fc48-11ea-939b-1e89c35ab1d5.png)

**Comment by westnordost** [comment] 2020-09-21 20:18
"New"? You haven't looked in the credits screen for a while, didn't you :-o

Anyway, thanks for the report!

**Comment by westnordost** [comment] 2020-09-21 20:52
Actually, I can't reproduce this.

**Comment by westnordost** [comment] 2020-09-21 21:13
What would reproducibly not work was changing the language while in the privacy statement screen. Fixed that.

**Comment by matkoniecz** [comment] 2020-09-22 05:16
> Actually, I can't reproduce this. (Android 10 emulator)

I tested it right now and on my Android 10 phone it works fine. I am not sure whatever it should be classified as "probably Android 5 bug, not worth making workaround" like with slightly broken svgs on Adroid 5. Probably yes and it should be closed?

**Comment by westnordost** [comment] 2020-09-22 08:53
Well I think it is worth investigating, Android 6 is not going to be not supported anymore anytime soon

**Comment by westnordost** [comment] 2020-09-22 16:17
I investigated it, `onViewCreated` is correctly called on Android 5/6 and the app's code correctly populates the view. For example, each translation credits row is correctly set with the correct translators. So, everything is fine. Only that the view is not correctly updated after all even though the view passed in at `onViewCreated` is correctly filled.

So, well, no idea. Seems to be some internal Android bug. I'm closing this.

**Closed by westnordost** 2020-09-22 16:17 UTC
Labels: bug, feedback required
