### ISSUE TITLE
Quests for invisible ways

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#1164] opened 2018-08-19 20:01 UTC
Hi there,

today I found a quest pointing to nowhere. In fact it's about an existing way which just didn't appear on the map. See the following screenshots:

![quest1](https://user-images.githubusercontent.com/32601012/44312580-f60d0500-a3fa-11e8-8672-0708da690e7e.png)

![quest2](https://user-images.githubusercontent.com/32601012/44312598-205ec280-a3fb-11e8-82bb-03f73dc522b5.png)

Perhaps it's because the way is tagged with `highway=footway` - if there are quests for this kind of ways they should be shown on the map as well.

(StreetComplete 6.1 on a bq Aquaris M4.5 with Android 5.1)

The cycling cat

**Comment by JeanFred** [comment] 2018-08-19 20:06
Hi there!

This is likely a duplicate of #1011: the tile server is not updated, so a path that has been added since the last update is not shown on the map.

**Comment by westnordost** [comment] 2018-08-19 20:16
See @jeanfred

**Closed by westnordost** 2018-08-19 20:16 UTC
