### ISSUE TITLE
Rendering Artifacts in latest version

### ISSUE THREAD

**Issue by daniel-j-h** [westnordost/StreetComplete#127] opened 2017-04-17 21:56 UTC
Nexus 4, Android 5.1.

Related:
- https://github.com/westnordost/StreetComplete/issues/36
- https://github.com/westnordost/StreetComplete/issues/34

The screenshots don't do it justice, it's flickering like mad all the time to a point where the app is unusable for me at the moment. Most visible in (but not restricted to) street names:

![sc1](https://cloud.githubusercontent.com/assets/527241/25106297/06a7ba9e-23c9-11e7-9ac0-5882541a7d43.png)
![sc0](https://cloud.githubusercontent.com/assets/527241/25106298/06ad1bec-23c9-11e7-962a-6f308db50571.png)

**Comment by westnordost** [comment] 2017-04-17 22:56
Can you perhaps make a short screencap (video) of the flickering? One video says more than thousand pictures ;-)

**Comment by daniel-j-h** [comment] 2017-04-18 09:18
Hm I don't have the developer tools at hand - just think of it as font artifacts jumping around and flickering at the same time. It seems to change a bit when zooming / moving around, but it's always there.

**Comment by westnordost** [comment] 2017-04-18 21:54
Hmm, I cannot reproduce this on my Android 5.1 at the Marchlewskistraße in Berlin. 

Do you have the same problem with version 0.5 of the app?

**Comment by transmit-receive** [comment] 2017-04-20 20:24
Same here for me. Street names flickering, distorted and jumping around. 
Additionally, app crashes all 5-20 seconds.

Version: 0.7 from f-droid
CyanogenOS 12.1.1, Android 5.1.1

**Comment by transmit-receive** [comment] 2017-04-20 21:20
Just tested: v0.5 runs perfectly fine on my phone.

**Comment by welkie** [comment] 2017-04-20 21:37
I used [this](https://play.google.com/store/apps/details?id=com.hecorat.screenrecorder.free) screen recording app on my Nexus 5X to record a bug in another app and it worked well. Free version lets you do short videos fine.

**Comment by hjanetzek** [comment] 2017-04-21 16:00
@transmit-receive could you test if the crash is fixed in these builds https://github.com/westnordost/StreetComplete/issues/130 ?

**Comment by transmit-receive** [comment] 2017-04-21 16:04
I'm on it.

**Comment by westnordost** [comment] 2017-04-21 22:38
nice :-)

**Comment by westnordost** [comment] 2017-04-28 18:54
fixed upstream

**Closed by westnordost** 2017-04-28 18:54 UTC
Labels: blocked, bug
