### ISSUE TITLE
Postbox collection time uses commas instead of semicolons.

### ISSUE THREAD

**Issue by Mbodin** [westnordost/StreetComplete#1578] opened 2019-09-23 10:07 UTC
Hi, I noticed the history of this object: https://www.openstreetmap.org/node/450211913/history
In a nutshell I have added the collection time through StreetComplete in this changeset: https://www.openstreetmap.org/changeset/72027930 (the interface of StreetComplete makes it perfect for this kind of changes)
StreetComplete then added the value “Mo-Fr 09:00, Sa 07:00” to the key “collection_times”. I think that “Mo-Fr 09:00; Sa 07:00” was expected instead (with a semicolon in place of the comma). This has been changed in the meantime for this particular postbox.

**How to Reproduce**
It seems that this happens on all postbox that I filled through StreetComplete (here is another example: https://www.openstreetmap.org/node/6772668486 ).

**Versions affected**
StreetComplete version 14.0, Android version 7.1.2 N2G47H

**Comment by westnordost** [comment] 2019-09-23 12:05
Hi @Mbodin 

Actually, [both versions are correct](https://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Fr%2009%3A00%2C%20Sa%2007%3A00&lat=48.7769&lon=9.1844&mode=1).

This is a duplicate of #1402

**Closed by westnordost** 2019-09-23 12:05 UTC
Labels: bug

**Comment by Mbodin** [comment] 2019-09-23 14:56
Right. I was basing myself on these two webpages, which seem to strongly advise to use the semicolon to separate different day ranges:
https://wiki.openstreetmap.org/wiki/Key:collection_times
https://wiki.openstreetmap.org/wiki/Key:opening_hours
Anyway, sorry about the duplicate, I did look for such, but missed this one.
