### ISSUE TITLE
No decimal point for max_height quest

### ISSUE THREAD

**Issue by Discostu36** [westnordost/StreetComplete#1322] opened 2019-01-26 19:17 UTC
Since the last update it's no longer possible on my device to use a decimal point in the max_height quest, it's missing from the keyboard.

Android 6.0.1
Samsung Galaxy S5
Samsung Keyboard
![screenshot_2019-01-26-19-31-51](https://user-images.githubusercontent.com/30999326/51791726-57ee4980-21a7-11e9-8512-7937136d5fb1.png)

**Comment by Discostu36** [comment] 2019-01-26 19:19
The problem does not occur when installing an alternative keyboard

**Comment by rugk** [comment] 2019-01-26 19:36
Duplicate of https://github.com/westnordost/StreetComplete/issues/1212

It's a known Samsung issue.

**Comment by westnordost** [comment] 2019-01-26 20:55
See @rugk. I also linked some popular keyboard alternatives in #1212 you can try out.

**Closed by westnordost** 2019-01-26 20:55 UTC
