### ISSUE TITLE
Compass breaks through screen overlay after update v5.1

### ISSUE THREAD

**Issue by pkoby** [westnordost/StreetComplete#1045] opened 2018-05-03 13:00 UTC
I'm running the Twilight Android app, which creates an overlay on the screen to red-shift the display.

After the update to 5.1, which I saw had some work done on the compass to help with battery issues, I'm noticing that the compass icon jumps above the overlay layer (e.g. it is not red-shifted). I tried to take a screenshot, but something about that function prevented me from getting the bug in a picture, despite the screenshot showing the overlay.

So here is an actual photo:
![dscn4869](https://user-images.githubusercontent.com/7786285/39577703-09639ce0-4eb0-11e8-8dab-c75f837a8a2d.JPG)

Some extra info: the breakthrough is not constant. It flickers when I'm touching the screen, sometimes not breaking through. The issue persists when locked to GPS or not, when the compass is up, or pointing in any direction, and with the map tilted or not. So basically in any situation.

**Comment by westnordost** [comment] 2018-05-04 09:25
Generally, this is a problem of the Twilight Android app, not of StreetComplete. I bet they have dozens of bug reports like this in their bugtracker, perhaps you could look there what causes this behavior. I suppose it is caused by the opaque draw mode of the surface view.

**Comment by pkoby** [comment] 2018-05-04 11:34
Okay, that makes sense. I'm having trouble finding any bug reports page online, but it does seem to have similar problems now and then.

It's not app-breaking, anyway.

**Comment by rugk** [comment] 2018-05-04 14:03
BTW recent Android versions (or maybe only LineageOS versions) have such a filter built-in. And AFAIK the issue there does not happen.

**Comment by westnordost** [comment] 2018-05-05 12:47
I had another look on what I changed from 5.0 to 5.1 on the CompassView. What I changed was that it only re-renders when the rotation actually changed (and not every frame). While this is probably quite a tiny performance improvement, I do not see how this should effect whether an overlay can be drawn on top of the view or not. I will close this as Will Not Fix.

**Closed by westnordost** 2018-05-05 12:47 UTC
