### ISSUE TITLE
Some of the dialogs are not supporting dark mode very well

### ISSUE THREAD

**Issue by frlan** [westnordost/StreetComplete#1864] opened 2020-05-30 10:22 UTC
* Switch to dark mode on your pone

This happens e.g. on some of the properties pages as well as e.g. when choosing the type of a building. I'd expect to use e.g. grayish colors instead of black on dark gray background.

![Screenshot_2020-05-30-12-13-39-189_de westnordost streetcomplete](https://user-images.githubusercontent.com/1010248/83325856-e711e280-a26f-11ea-8e72-a0671546eb3c.jpg)
![Screenshot_2020-05-30-12-13-28-102_de westnordost streetcomplete](https://user-images.githubusercontent.com/1010248/83325857-e8430f80-a26f-11ea-8045-cf8692ba248c.jpg)
![Screenshot_2020-05-30-12-12-57-330_de westnordost streetcomplete](https://user-images.githubusercontent.com/1010248/83325858-e8dba600-a26f-11ea-8aca-07ab2cc24c38.jpg)

**Versions affected**
* Streetcomplete: 20.0
* Android: 10 QKQ1.190828.002 / MIUI 11.08.0 (Current version)

**Comment by westnordost** [comment] 2020-05-30 15:53
Would you restart the app once please? Does it then look correct?

**Comment by frlan** [comment] 2020-05-30 16:31
@westnordost  It actually does :heavy_check_mark:

**Comment by westnordost** [comment] 2020-05-30 16:36
Ok, then this bug is actually known but there seems to be no ticket for that yet. When switching to dark mode, (some) dialogs do not set the correct colors for the text and maybe other elements.
I have no idea why, since it obviously works after completely restarting the app, I consider(ed) it an Android bug. Considering that it occurs on every Android version from 5 to 10, maybe it is not, but I have no idea how this bug originates and how to fix it.

**Comment by frlan** [comment] 2020-05-30 16:38
Maybe adding a short popup stating this would be a nice idea for users.

**Comment by matkoniecz** [comment] 2020-05-30 16:42
I also tried to track it down, without a real success (except learning how night mode works).

**Comment by westnordost** [comment] 2020-05-30 16:43
That'd be like putting a road damage sign like this instead of fixing the road

![grafik](https://user-images.githubusercontent.com/4661658/83334239-666dd900-a2a5-11ea-8bf2-58467960c113.png)

**Comment by frlan** [comment] 2020-05-31 11:48
:D

**Comment by westnordost** [comment] 2020-06-07 22:37
closing as duplicate of #1807

**Closed by westnordost** 2020-06-07 22:37 UTC
Labels: bug, help wanted
