### ISSUE TITLE
Organize / sort quests (groups/folders)

### ISSUE THREAD

**Issue by Katzenstreu** [westnordost/StreetComplete#2308] opened 2020-11-20 08:25 UTC
Hi!

Now we have a lot of quests. I would like to sort them manually. But it's complex to scroll this long list multiple times.

![Sketch](https://user-images.githubusercontent.com/1107883/99785098-fe45d480-2b1c-11eb-81aa-7f6633d1ac8c.JPG)

Could you add **quest groups/folders**? Maybe Every user could define his own groups/folders. So in first we would name some folders and afterwards we would drag the quest types into this folders. At the end we could sort the priority of folders and also of some single quest types.

Best regards
Tim

**Comment by matkoniecz** [comment] 2020-11-20 08:29
Sounds like #1654

See also

> Your actual issue seems to be that you find you are overwhelmed by quest types that are unimportant. It is true, many are unimportant. I plan to do something here to make it easier for users to have only those quest types enabled that are interesting for them.

from https://github.com/westnordost/StreetComplete/issues/2295#issuecomment-729691822

**Comment by westnordost** [comment] 2020-12-08 15:58
closing as duplicate of #1654

**Closed by westnordost** 2020-12-08 15:58 UTC
