### ISSUE TITLE
No visual confirmation of data upload

### ISSUE THREAD

**Issue by Edoardo-M** [westnordost/StreetComplete#401] opened 2017-07-17 18:51 UTC
When answering questions the star counter is updated but there is no visual confirmation that data has been actually transmitted to OSM. 

I verified my are looking at object history but would be nice to get a notification every time data is uploaded, sucessfully or not.

**Comment by HolgerJeromin** [comment] 2017-07-17 20:44
There is a "(+1)" (or a higher number) behind the star count. You have not seen it before because you had always a working and fast connection.

**Comment by Edoardo-M** [comment] 2017-07-18 09:02
Still is not a clear confirmation, looks like as a count of provided
answares. Just add a (0 to upload) on the side or something like that

Il 17 lug 2017 11:44 PM, "Holger Jeromin" <notifications@github.com> ha
scritto:

**Comment by matkoniecz** [comment] 2017-07-18 14:50
duplicate of #75

**Closed** 2017-07-18 17:45 UTC
