### ISSUE TITLE
Up to date Quest

### ISSUE THREAD

**Issue by schlagi123** [westnordost/StreetComplete#1112] opened 2018-06-28 06:50 UTC
Hello,

I have the idea to create a new quest for checking, if a [amenity](https://wiki.openstreetmap.org/wiki/Key:amenity) is up to date (the amenity itself, opening_hours, etc). I am not sure, if it is possible, because the last update of the data must be check. Furthermore a new tag is needed for showing the up to date status and i do not know, if there exist such a tag. If the amenity is not up to date it should be possible to add another tag to show, that the amenity must be updated.

This is only an idea and should be discussed, because only with such a mechanism is it possible to hold the data up to date.

**Comment by ENT8R** [comment] 2018-06-28 07:04
I think this is a duplicate of #112, and with that also #314 and maybe also #534
The reason why this won't be implemented can be found here: https://github.com/westnordost/StreetComplete/issues/314#issuecomment-397865306

**Comment by schlagi123** [comment] 2018-06-28 07:13
you are right thanks

**Comment by goldfndr** [comment] 2018-06-28 09:18
Perhaps #112 should be reopened?

#314 dealt with a particular mechanism for changing+checking, and #112 was closed because @westnordost thought #314 was a preferred mechanism for changing+checking. But, #314 was closed because said mechanism wasn't preferable after all.

**Comment by westnordost** [comment] 2018-06-28 10:11
Setting a `check_date`-annotation is still the preferred mechanism (because there is no other), but not applicable for #314 because StreetComplete does currently not offer this kind of changing+checking quests.

This ticket is about creating such a class of quests. However, my comment to @schlagi123 is that it is problematic / does not fit into the scope of this app to let a user review *all* tags of a place, rather than just a specific one (opening hours, name, ...).
The way I imagine this up-to-date quest class to be is that the quests we have now will simply pop up again after some time and ask again for the information to be gathered through the quest. If the information supplied by the surveyor is the same, nothing will be changed except for the `check_date:*` tag. If it is different, the current tag (and `check_date`) will be replaced.

Let's open this ticket again to discuss.

**Comment by matkoniecz** [comment] 2018-06-28 10:22
> and ask again for the information to be gathered through the quest

At least I would prefer to have this quest in form "is following opening hours info correct?". Comparing this should take far less time than entering opening hours again.

**Comment by ENT8R** [comment] 2018-06-28 10:41
> At least I would prefer to have this quest in form "is following opening hours info correct?"

I also thought that this would be the preferred solution as I thought about this quest. If the user spots a mistake in the information which is present, he can press "No" which then opens the quest for the element to correct the information. Because if the same quest is shown after 6 months again for the same element and you always have to reenter the same information you already entered 6 months before, users can get easily annoyed by always entering the same information (because in most of the cases the data will not change during 6 months) and they might think "Mmh, didn't I answer this quest already 6 months before? Let's create a new Github issue for that!".

**Comment by rugk** [comment] 2018-06-28 11:48
@schlagi123 BTW as for the next time when suggesting a new quest, please fill out the issue template. Thanks.

**Comment by schlagi123** [comment] 2018-06-29 05:54
@rugk Sorry for that, you are right.

> At least I would prefer to have this quest in form "is following opening hours info correct?"

I also thought this would be a good solution, but I think there are not only two cases (yes/no), there are four cases:

1. Data are up to Date
2. Data must be updated (then a dialog for update)
3. There is a new shop (dialog for name/typ of new shop and then the dialog for update)
4. There is no shop anymore (must set a flag or something like this to indicate, that this element must be reviewd/removed)

> "Mmh, didn't I answer this quest already 6 months before? Let's create a new Github issue for that!"

We can be sensitize the user if the Quest is by default disabled and when the user enable the quest, there is a message, that notice the user about this fakt.

By the way I think that such a mechanisme/quest is very important, because all the collected data is worth nothing, when many of that are outdated in 3/5/10 years and this app can contribute something to the up-to-dateness of the data.

**Comment by ENT8R** [comment] 2018-06-29 05:57
3 and 4 can be solved by posting a new note. This is also the current behaviour because StreetComplete can't delete or create elements.

**Comment by rugk** [comment] 2018-06-29 07:03
And when "no" is pressed the (original) opening hours quest is shown?

**Comment by ENT8R** [comment] 2018-06-29 07:09
I think so, yes, this was the idea I had...

**Comment by schlagi123** [comment] 2018-06-29 07:12
Yes, why not reusing the existing dialog. Otherwise there is code duplication.

**Comment by HolgerJeromin** [comment] 2018-06-29 19:43
> the app needs to be able to parse opening hours

I want to just add the reference to Simons [OpeningHoursParser](https://github.com/simonpoole/OpeningHoursParser).

**Comment by matkoniecz** [comment] 2018-06-29 20:04
>  this would require much more effort then simply asking again, or, in other words, every single "verify information" quest needs to be programmed.

I know, displaying opening hours alone is a massive task. Even after limiting it to a subset of simple ones (that can be added using StreetComplete).

**Comment by matkoniecz** [comment] 2018-07-08 07:56
@westnordost Would you accept PRs implementing "verify information" quests? I am planning to make one for bicycle parkings in my fork and it would be useful to know whatever it would be potentially accepted in StreetComplete.

**Comment by rugk** [comment] 2018-07-08 08:48
Would not best be implemented in some generic way, so it could easily be implemented for all quests later? If it just asks for the same information, but with a different question, this may be possinble.

**Comment by matkoniecz** [comment] 2018-07-08 09:00
> Would not best be implemented in some generic way

Because the only idea for implementing it in generic way is to ask user to solve quest again, see https://github.com/westnordost/StreetComplete/issues/1112#issuecomment-400985259 and later discussion.

**Comment by westnordost** [comment] 2018-07-08 12:22
@matkoniecz In what way would you plan to implement such a verify-information quest? I am uncomfortable with the idea that the type of quest is not implemented generically but only for one quest type because it might make a generic solution more difficult to realise (/would involve throwing the work made for bicycle-parking-verify-quest away).
Additionally, I did not anticipate that someone else would tackle this topic of implementing this kind of quest type. In regards to my last comment, my hope was that if I finally sit down to do this, I will realise that actually showing the current information as it would be convenient for the user will not be that much work after all. I have no control over considering such a solution of course when I am not the one implementing it, but at the same time, I am not prepared to push the boat out on that topic right now.

So, if you plan to implement only the bicycle-parking quest as a "is this info still correct?"-quest without seeking a generic solution, I'd tend to say that it should remain in your fork but can serve as a case study/first iteration of what a generic solution might look like.

If you plan to find such a generic solution, I have to warn you that it will probably be a longer process and that I will butt in (the PR) quite a bit. To avoid this, we should perhaps talk about the (design/architectural) concept before the actual implementation is done. Though, I do have confidence in you that you can pull this off.
I imagine an solution would...
- not require building new QuestTypes and forms, but simply make it possible to specify after what time for each quest the information should be re-checked
- ideally not require new strings for each quest
- possibility to edit it if the current information is not correct 
- ideally have a shortcut (answer "yes" or something, depends on how the form would look) to just acknowledge that the current information is correct.<sup>1</sup>

<sup>1</sup> One complex solution how that could work combined with the previous point: The app first asks "Is this information still correct?: Postbox collection times - Mo-Fr 16:00" and the user can answer yes or no. On no, the normal collection times input is shown.

**Comment by matkoniecz** [comment] 2018-07-10 10:12
> If you plan to find such a generic solution

The idea closest to generic is to show current OSM data as prefilled quest form.

So for example opening hours verification quest would look like a normal form, but would start with opening hours data already added rather than start as blank form. It would require an explanation to user what is happening (probably a different form question), but it would reuse form, allow direct editing, should be familiar to an user, would have a shortcut answer (just select yes without modyfying anything)

It would still require creating code to parse opening_hours tag into internal StreetComplete representation and may require new string(s) but would fullfill other requirements.

Prefilled form plan would be a good interface for bikeway quest but collecting data from OSM into the interface may be tricky (though discarding roads with nearby footways/cycleways should simplify that).

Prefilled form plan should work well car_wash_type, bike_parking_capacity, parking_access, postbox_collection_times, bike_parking_type.

Prefilled form plan would not work for yes/no quests, it would require a new form. It would work poorly for orchard_produce, sport, surface, max_speed - as currently selected answer may be buried deeply and it should be rather displayed on top of everything.

>  I have to warn you that it will probably be a longer process and that I will butt in (the PR) quite a bit.

It is no problem at all with that (for example comments during contruction quest allowed me to learn something new and as result quest got better).

> I am uncomfortable with the idea that the type of quest is not implemented generically

I plan to do it in totally non-generic way: group verification of all bicycle parking quests in one, with question like "Is this bicycle parking existing, of XYZ type, with capacity of N and (un)covered?" to make verification quicker.

> I'd tend to say that it should remain in your fork but can serve as a case study/first iteration of what a generic solution might look like.

OK, I will do it this way. Though it will probably be a test whatever nongeneric solution is worth it.

---------------------------------------------

note: all number below are blatant guesses not based on even limited experiments

As bonus: my reasoning why it may be worth to spend really long time on making good interface for a verification quest (my ideas for how verification quest may look like is below line):

Following factors influence how much of OSM data can be kept up to date and therefore marking upper limit of what can be usefully collected:

- how quickly world changes and making our data outdated - impact of OSM can be ignored in this case
- reports of data mistakes from users (MAPS.ME notes about missing objects are really useful, it would be nice to have more reports like that but it is not influenced by StreetComplete)
- effectiveness of survey tools (how much can be checked in a given time)
- how much time people spend on resurveying

Effectiveness of survey tools directly changes how much mapper can verify in a given time, and I expect that nearly all mappers are not limited by mapped object count ("I checked opening hours of ten objects, that is end for today"), but rather by time "it is end of my 20 minute break, now lets get back to work".

So tool that is six times more efficient will allow to collect six times more data in the same time. But I think that it is only part of the impact. I expect time spend on resurveying to be hugely influenced by tools used for that purpose. For example opening hours asking to collect data over and over again and throwing away collected data on each verification would be quite flustrating.

So I think that tool six times more efficient is not going to result in collecting merely six times more data but something like 10 or 20 times more.

**Comment by matkoniecz** [comment] 2018-07-10 10:18
BTW, do you have a plan how StreetComplete should mark that specific tag was verified? I have no good idea how to do that

- opening_hours:last_verification_date, with :last_verification_date for each tag? Such tag spam sounds like a terrible idea
- set survey:date - but what should be done if generic solution will be used and bicycle parking tags are not bundled in one check (it may be partially solved by adding some randomization to priority so situation where each year the same tag is verified will be avoided)? What about tags not verified by StreetComplete user?
- invent what_was_surveyed=<colon separated list of tags>? I am not too happy about it.

**Comment by awst-baum** [comment] 2018-09-09 17:56
This issue sounds very interesting and promising. Would you consider starting the general "up to date" quest with (what I'd naively think) the most basic question: does this node (shop, doctor, etc.) still exist at all [yes/no] and leaving a note about it if it doesn't? Hopefully that wouldn't require too complicated parsing of existing data?

**Comment by westnordost** [comment] 2020-09-07 12:58
So, this is implemented now.

**Closed by westnordost** 2020-09-07 12:58 UTC
