### ISSUE TITLE
Very Close-By Quests

### ISSUE THREAD

**Issue by ax3l** [westnordost/StreetComplete#71] opened 2017-04-01 08:58 UTC
Yesterday I added the opening hours of a shop close to an other and although I stayed in maximum zoom level did kind of expect that OSM will likely have the opening hours of the 2nd shop next door neither.

Anyway, I completed the quest and about an hour later I got the quest to complete the shop next-door...

Is there a way to make this workflow a bit more clever or should I have somehow triggered a deeper zoom-level quest-update?

**Comment by westnordost** [comment] 2017-04-01 09:54
No idea why the other opening hours quest didn't show up earlier. It should have.

SC downloads all quests in bulk. There is an open issue regarding the display of the quests, there seem to be some problems with that they are sometimes not shown on the map, depending on your zoom level. So this is very possible a duplicate of that one. #50

**Closed by westnordost** 2017-04-01 09:54 UTC

**Comment by ax3l** [comment] 2017-04-01 12:10
Ok makes sense.
