### ISSUE TITLE
Show outline of buildings

### ISSUE THREAD

**Issue by earboxer** [westnordost/StreetComplete#1155] opened 2018-08-11 17:23 UTC
When filling out the building numbers quest, it would be very helpful to see the shape of all of the buildings, not just the one you are answering for. GPS can be a little spotty, and it's easier to say "this is the third house from the street", or "this is next to the L shaped house", rather than "I think I'm next to this house".

![screenshot_20180811-132010](https://user-images.githubusercontent.com/12452738/43994355-811f2fe4-9d69-11e8-9379-4afe739e8d70.jpg)

**Comment by ENT8R** [comment] 2018-08-11 17:39
Duplicate of/covered with #1011
This is a problem with old map data... Can you maybe share a link to the location? Is it outside of Germany?

**Comment by westnordost** [comment] 2018-08-11 17:49
I don't see how sharing his location would help the issue. We already know the map is outdated and investigating alternatives.

**Closed by westnordost** 2018-08-11 17:49 UTC

**Comment by ENT8R** [comment] 2018-08-11 20:43
> I don't see how sharing his location would help the issue

Just thought it might be useful to know wether the map is only outdated in other countries than Germany, but yeah, indeed, nevermind my comment... :shrug:
