### ISSUE TITLE
Config only Quest handling 

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#165] opened 2017-04-29 20:06 UTC
Perhaps it would be possible to have a generic quest infrastructure so (most) quest are defined only with a (JSON?) config file with linked images. 

With this everyone can add own quests similar to the way vespucci and josm handles tag Presets.

**Comment by westnordost** [comment] 2017-04-30 16:42
This is a duplicate of #98

**Closed by westnordost** 2017-04-30 16:42 UTC

**Comment by HolgerJeromin** [comment] 2017-05-01 00:47
Adding a configuration file is imo a different thing compared to a full app which act as a plug in.
