### ISSUE TITLE
What street does the address belong to - not working

### ISSUE THREAD

**Issue by DennisKempel** [westnordost/StreetComplete#1856] opened 2020-05-26 11:22 UTC
Hi, the recently added feature "what Street does ... belong to" and typing on the street to take over its name does not work anymore with the current update. It did work before. Also I noted the quest is English only now whereas it was in German before...

**How to Reproduce**
Answer the "what Street does ... belong to" quest

**Versions affected**
Current Android

**Comment by westnordost** [comment] 2020-05-26 11:39
> [...] does not work anymore with the current update. It did work before.

This statement is contradictory. The new quest was added in Beta 2, so the current beta version.

You mean to say that tapping on a street does not pre-fill the street input field?

**Comment by westnordost** [comment] 2020-05-26 22:20
If so, does it work nowhere, or does it not work at a specific location?

**Comment by DennisKempel** [comment] 2020-05-28 08:15
Exactly, and it seems to work nowhere. But as I wrote, it worked the version before...

**Comment by DennisKempel** [comment] 2020-05-28 08:17
...sorry, just trying it on the address Lyserstraße 30, 22761 Hamburg and taking over the name worked now. But it is still in English while I am relatively sure it the quest has been in German when it was first introduced?

**Comment by DennisKempel** [comment] 2020-05-28 08:22
...sorry again, and I'm just noting I am on the beta version, v20.0-beta2

**Comment by westnordost** [comment] 2020-05-28 10:42
The quest has been introduced in v20.0-beta2, it's very new and there is no German translation yet (I think).

**Comment by westnordost** [comment] 2020-05-28 10:42
Ok then I will close it. If you can reproduce it in the future, please add the info where you can reproduce it.

**Comment by DennisKempel** [comment] 2020-05-29 10:56
Hello, I'm currently Hauptstraße 31, 38543 Hillerse. The quest for this house is still open and tapping on the street does not take over its name...

**Comment by westnordost** [comment] 2020-05-29 12:39
Ok, will have a look!

**Comment by westnordost** [comment] 2020-05-31 15:01
Hm, I cannot reproduce it. I can click on "Hauptstraße" and the name is put into the text field.

Does it not work at all, regardless if you tap on Steilbergsweg or Hauptstraße or anywhere for that matter?
Could you try at some other place? Does it not work for you anywhere?

**Comment by matkoniecz** [comment] 2020-05-31 18:23
For me it sometimes work and sometimes not.

It seems that the difference is whatever it is a fresh download or is it created based on solved `addr:housenumber` quest.

I tried (with just a smartphone, without PC, no log access):

(1) solve `addr:housenumber` quest.
(2) wait for `addr:street`
(3) unable to fill by clicking a street
(4)wait for overpass to catch up
(5) flush cache
(6) redownload `addr:street`
(7) able to fill by clicking a street
(8) revert  `addr:housenumber` solution if it was done with a fake number

**Comment by westnordost** [comment] 2020-05-31 20:06
> It seems that the difference is whatever it is a fresh download or is it created based on solved addr:housenumber quest.

Ah, that's it!

**Comment by westnordost** [comment] 2020-06-01 01:40
I think regrettably there is no better solution than not letting the quest pop up right after the housenumber one was solved. It **must** download the road names first.

**Closed** 2020-06-01 11:18 UTC
Labels: bug

**Comment by smichel17** [comment] 2020-06-01 11:41
How much extra data would it be to just fetch all street names in advance in areas where this quest might be asked?

**Comment by westnordost** [comment] 2020-06-01 11:45
I don't know, but to just always fetch this data would actually be more of an architecture issue. Currently, every quest type is relatively self-contained as in that it can do what it wants on download. So every quest downloads exactly what it needs. Downloading all the street names at the beginning of every download for a bbox is breaking out of this scheme.

**Comment by Theodin** [comment] 2020-06-02 15:43
Im very happy for your adding this quest as I was about to write a proposal for it today :-)
