### ISSUE TITLE
Send notifification when quest nearby

### ISSUE THREAD

**Issue by corsac-s** [westnordost/StreetComplete#177] opened 2017-05-03 19:06 UTC
Hi,

first, let me thank you for the application, it's a really nice/fun way to contribute. I never really bothered using JOSM and other complicated applications, but this is working. I'm not sure how valuable my contributions really are to OSM community, but I hope it's still useful.

Now, I have a small feature request / proposal: I don't always go in “mapping mode”, sometime I just walk (or skate) around with my phone in my pocket. It'd be nice to have some kind of notification when a quest is available nearby (like in line of sight).

I understand that would mean having the GPS always on even when the screen is off, which might not be desirable for a lot of people but I think it'd be a nice addition.

**Comment by westnordost** [comment] 2017-05-03 20:24
Thank you for the feedback. It is duplicate of #48, my reply there.

**Closed by westnordost** 2017-05-03 20:24 UTC
