### ISSUE TITLE
additional operator on recycling:clothes=yes

### ISSUE THREAD

**Issue by rza31** [westnordost/StreetComplete#933] opened 2018-03-02 18:58 UTC
### General
Some Operators for recycling clothes are listed here on the wiki
https://wiki.openstreetmap.org/wiki/Deutsche_Altkleider-Container_Betreiber

Add operator for Textiles collection boxes.

### Checklist

- [X] 🚧 To be added tag is established and has a useful purpose
- [X] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [X] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [ ] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [X] 🕓 Applies to a reasonable number of elements (Worth the effort)

**Comment by ENT8R** [comment] 2018-03-02 19:23
Duplicate of #570. Please use the search feature of the issue tracker before opening new ones!

**Comment by rugk** [comment] 2018-03-02 20:30
Also why did not you tick the "nospam" requirement. AFAIK it is clearly no spam, as there are not even so much recycling containers out there.

**Closed** 2018-03-03 14:12 UTC
