### ISSUE TITLE
Allow marking businesses as closed on particular days

### ISSUE THREAD

**Issue by casept** [westnordost/StreetComplete#736] opened 2017-12-26 19:35 UTC
There currently doesn't seem to be an option to enter that a business is "closed on Sundays", for example. Am I just missing some obvious UI option?

**Comment by rugk** [comment] 2017-12-26 19:41
Just don't select any opening time for Sunday…

**Comment by casept** [comment] 2017-12-26 19:53
Noted! Would still be nice to add that as an explicit UI option though, as users might misinterpret that as telling the app that they don't know the opening times for that day.

**Comment by rugk** [comment] 2017-12-26 20:35
Hmm, in OSM there is no difference between "I don't know opening hours for this day" and "The amenity has notopen at this day.".

**Comment by HolgerJeromin** [comment] 2017-12-26 21:08
> Hmm, in OSM there is no difference between "I don't know opening hours for this day" and "The amenity has notopen at this day.".

That is not true. But adding a gui for that was rejected in #276

**Comment by rugk** [comment] 2017-12-26 21:14
Ah right, you could theoretically add "Off", but I've never seen that tagging in the wild in OSM itself (except for "PH off", of course).

**Comment by HolgerJeromin** [comment] 2017-12-27 18:12
@rugk i always add `off` for known closed days (including PH).

**Comment by westnordost** [comment] 2018-01-02 14:31
This is a duplicate of #276.

**Closed by westnordost** 2018-01-02 14:31 UTC
