### ISSUE TITLE
Add new URLs for overpass API

### ISSUE THREAD

**Issue by Zkir** [westnordost/StreetComplete#1638] opened 2019-11-11 09:01 UTC
There are two urls for overpass api in the app, but both are blocked in Russia currently.

Please add the other ones, listed in https://wiki.openstreetmap.org/wiki/Overpass_API#Public_Overpass_API_instances

**especially:**
http://overpass.openstreetmap.fr/api/

it is still accessible in Russian Federation.

Also it would be nice to display some error message that web api is not accessible. 
Now quests are just not loaded for no apparent reason, so users are confused.

**Comment by matkoniecz** [comment] 2019-11-11 09:25
Note that you can go to settings, advanced section (second entry from the bottom) to switch to alternative overpass server that should be bypassing Russian censorship.

Let me know if more detailed info is needed to find it.

See https://github.com/westnordost/StreetComplete/issues/1389 for Russia specific issue and for https://github.com/westnordost/StreetComplete/issues/1523 that proposes better interface.

It seems that this issue is a duplicate of #1523 

#1523 waits for someone to implement this. I plan to do this at some point but first I will finish what I have half-written. So it would be great if someone would make PR for that one.

-----

And for specific  http://overpass.openstreetmap.fr/api/ - we are not allowed to use it due to its usage policy. I asked and they are not granting exceptions for OpenStreetMap projects like editors.

And we have no way to limit total usage across all users to

> 1000 queries per day per "project" (By "project" I mean if you use this API in a smartphone app and you have 10,000 customer querying once per day then you are above the limit).

**Comment by Zkir** [comment] 2019-11-11 10:12
Hi Mateusz,
Thank you for the quick reply.
I see. So I am not the first and not the last who are reporting this :)
So i guess you can close this one.

<<So it would be great if someone would make PR for that one.>>
I will think how I can help here.

Kirill

**Closed** 2019-11-11 11:57 UTC
Labels: bug

**Comment by mmd-osm** [comment] 2019-11-19 22:24
What about //overpass.openstreetmap.ru/cgi/ ? This should be usable from Russia, right?

Ignore the error message you're seeing in overpass turbo, there's some issue with multiple Access-Control-Allow-Origin headers that need fixing. Nevertheless, I'm getting results via curl, and they look up to date:

`curl -g "https://overpass.openstreetmap.ru/cgi/interpreter?data=%2F*%0AThis%20is%20an%20example%20Overpass%20query.%0ATry%20it%20out%20by%20pressing%20the%20Run%20button%20above%21%0AYou%20can%20find%20more%20examples%20with%20the%20Load%20tool.%0A*%2F%0Anode%0A%20%20%5Bamenity%3Ddrinking_water%5D%0A%20%20%2844.78963254761407%2C-68.5931396484375%2C46.25774588045686%2C-65.9124755859375%29%3B%0Aout%3B"`

**Comment by westnordost** [comment] 2019-11-19 22:58
Is it documented somewhere who maintains the server and who may use it?

**Comment by mmd-osm** [comment] 2019-11-19 22:59
I think Roland maintains it, like in the old days with the rambler instance. Try to ping him to get more details.

**Comment by matkoniecz** [comment] 2019-11-20 09:24
I pinged him (via roland.olbricht@gmx.de)

**Comment by mmd-osm** [comment] 2019-11-20 09:27
It was also announced in weeklyosm 470

**Comment by matkoniecz** [comment] 2020-01-16 12:35
No.
