### ISSUE TITLE
Orientation change does not preserve input widget

### ISSUE THREAD

**Issue by exploide** [westnordost/StreetComplete#953] opened 2018-03-07 11:09 UTC
When an input widget is shown, e.g. for opening hours selection or for the option to describe the opening hours textual, then the widget will close once you change the orientation of your phone.

Minor thing, but is a bit annoying when switching to landscape mode for better text input. This does not happen always, e.g. not for leaving a note.

**Comment by ENT8R** [comment] 2018-03-07 11:59
This is the general behaviour of android:
Once you rotate the phone, this is basically (in the programmatic sense) equal to a (re)opening of the quest... Maybe this could be bypassed by adding a general function for saving the instance state...

**Comment by ENT8R** [comment] 2018-03-07 12:22
It is e.g. already done for the opening_hours quest:
https://github.com/westnordost/StreetComplete/blob/76425e405a8a08fa3f83b457622d732cf4ee2898/app/src/main/java/de/westnordost/streetcomplete/quests/opening_hours/AddOpeningHoursForm.java#L107

**Comment by westnordost** [comment] 2018-03-07 13:14
The data in the opening hours specifically should be preserved. If it is not, it is a bug.

**Comment by exploide** [comment] 2018-03-07 13:27
E.g. for the opening hours quest, if I choose the textual input option with the label (in German) "Keine regelmäßigen Öffnungszeiten", start typing in portrait mode, then decide that is is more comfortable in landscape mode and change the orientation, then the quest reopens without the text box and my text is gone.

**Comment by rugk** [comment] 2018-03-07 14:09
Can reproduce. The funny thing is, it first shows it correctly but with a black background for one second, and only then "decides" to show the quest without the modal/popup again.:grinning:

**Comment by westnordost** [comment] 2018-03-08 21:56
I am sorry, there seems to be no easy solution for this that would justify the effort made. I tried a straightforward/recommended approach [similar to this](https://stackoverflow.com/questions/7557265/prevent-dialog-dismissal-on-screen-rotation-in-android#15729764), but it 1. wouldn't work (perhaps another bug in SC) and 2. had the sideeffect that any other dialog that was opened would close the original one (i.e. the "Are you sure you were there?" and the "You left the form empty" dialog) which is also not really desirable.
So, I will close this as won't do. Perhaps someone else will find an easy solution to this, then a PR is welcome.
Otherwise, I do not find this bug too bad. Basically, it should be relatively well known that dialogs in Android are somewhat volatile. At least, this bug is far from being what I originally thought it was (that the persistance when entering opening hours in the main form is broken).

**Closed by westnordost** 2018-03-08 21:56 UTC
Labels: bug
