### ISSUE TITLE
Installing StreetComplete 4 from fdroid not working

### ISSUE THREAD

**Issue by Mannshoch** [westnordost/StreetComplete#932] opened 2018-03-01 13:33 UTC
Fairphone2 
Android 6
I get a Parsing error if I try to install StreetComplete 4

**Comment by matkoniecz** [comment] 2018-03-01 13:35
duplicate of #809 and out of scope (see https://github.com/westnordost/StreetComplete/issues/809#issuecomment-361078766 )

It is a F-droid bug or Fairphone2 bug and it should be reported to Fairphone2 or F-droid bugtracker.

**Closed** 2018-03-01 17:46 UTC

**Comment by Mannshoch** [comment] 2018-03-07 15:14
https://gitlab.com/fdroid/fdroidclient/issues/1310
