### ISSUE TITLE
closed shop

### ISSUE THREAD

**Issue by Marc-marc-marc** [westnordost/StreetComplete#1153] opened 2018-08-04 22:38 UTC
Hello,
I see a lot of note "unable to answer for opening_hours (or other info)" : the shop is closed.
maybe it's better : 
- to put off in opening_hours in this case
- or add was: to all related tag (shop name website phone fax brand wheelchair opening_hours)
to avoid that someelse need to convert the note to one of those 2 edits :)

**Comment by matkoniecz** [comment] 2018-08-05 05:27
Can you give an example note that you consider as wrong? I expect that affected shops are not existing anymore but are tagged as existing in OSM.

Such notes are extremely useful.

**Comment by rugk** [comment] 2018-08-05 07:49
This is basically a dupe of https://github.com/westnordost/StreetComplete/issues/1046 and https://github.com/westnordost/StreetComplete/issues/450. But it's a request that came several times now…

**Comment by matkoniecz** [comment] 2018-08-09 11:50
@Marc-marc-marc Can you give example of specific problematic notes?

**Closed** 2018-08-09 22:20 UTC
Labels: feedback required
