### ISSUE TITLE
After making a note. Strange display

### ISSUE THREAD

**Issue by arne182** [westnordost/StreetComplete#1947] opened 2020-07-12 12:11 UTC
![Screenshot_20200711-214026_Street­Complete](https://user-images.githubusercontent.com/844102/87245873-73a3e900-c449-11ea-8b2a-7e8f8a78cf49.jpg)

**Comment by westnordost** [comment] 2020-07-12 12:43
Okay... this is new.

Is this always reproducible?

Were these quarter-circles quests? (when) do they go away again? Tab in tab out? Go to settings and back? Restart app?

Am 12. Juli 2020 14:11:15 MESZ schrieb Arne Schwarck <notifications@github.com>:

**Comment by arne182** [comment] 2020-07-12 13:26
Yes quests. After restarting the app everything was back to normal. I went a bit crazy yesterday with making notes for everything. Have not reproduced it yet.

**Comment by westnordost** [comment] 2020-07-12 15:03
Okay, regarding notes, keep in mind that the app shows very little things on the map. So let's say there is a hairdresser, a bench and a bin at one corner, you won't see it on the map displayed by StreetComplete. So you can't assume that if it is not displayed, it is not there.

If you can reproduce it again, please note it here. Even better if you find a way to reliably reproduce it.

**Comment by westnordost** [comment] 2020-09-04 09:26
Closing because not reproducible by me and never reproduced by anyone else.

**Closed by westnordost** 2020-09-04 09:26 UTC
Labels: bug, feedback required

**Comment by matkoniecz** [comment] 2020-09-04 09:28
And also not reproduced by person who spotted it ("Have not reproduced it yet.") anyway. Maybe it is just phone glitch...
