### ISSUE TITLE
[Feature Request] Add a possibility to mark "A change is happening"

### ISSUE THREAD

**Issue by Mannshoch** [westnordost/StreetComplete#621] opened 2017-10-01 18:46 UTC
If some one detect Streetwork, see a Company leave, or other changes, people should be able to mark it on the Map and StreetComplete should ask about details like speed limit and surface or opening times again.

**Comment by rugk** [comment] 2017-10-01 19:53
Unfortunately, I do not really understand what you mean. Could you please describe your issue again?
Maybe just use bullet points and describe it like "If X happens, Y should happen." or "If I do X, Y should be done.".

**Comment by HolgerJeromin** [comment] 2017-10-01 20:23
I think the use case is someone who sees a construction and want to notify osm mappers that here will be a change in the near future.

If i got this right the suggestion is a duplicate of #47

**Comment by westnordost** [comment] 2017-10-01 22:03
I understand your idea, I like it.

It is part of the larger idea to have some kind of system that marks places as to-be-revisited because as everything, places on the map change. Not only (through) construction sites.

So far, the best possibility to implement such a behavior would be #47.

**Closed by westnordost** 2017-10-01 22:03 UTC

**Comment by westnordost** [comment] 2017-10-01 22:06
There is much room for integrating this kind of functionality deeper into StreetComplete and actually the whole OSM eco-system, but so far, there aren't the prerequisites met for that yet. I.e. it is very data intensive, to find out when last a place/tag was resurveyed automatically, too data intensive to be done by this app.

**Comment by Mannshoch** [comment] 2017-10-02 07:40
The Idea came as I told a friend of mine about StreetComplete and he compared it with the Haiti project he heard about. 
https://voices.nationalgeographic.org/2012/07/02/crisis-mapping-haiti/
I wouldn't say It should go that far. But I think it could be important to tell people about Problems and changes.
