### ISSUE TITLE
Select multiples quests before answering

### ISSUE THREAD

**Issue by Jeanuel** [westnordost/StreetComplete#149] opened 2017-04-26 14:22 UTC
Sometimes there are multiple quests attending for the same answer. For instance the nature of the ground or the number of levels for buildings. It would be handy to be able to select multiples quests before answering.

**Comment by matkoniecz** [comment] 2017-04-26 14:28
Do you have any idea how to do that in way that will not be highly confusing?

**Comment by westnordost** [comment] 2017-04-26 14:48
This is a duplicate of #73

**Closed by westnordost** 2017-04-26 14:48 UTC

**Comment by bill-baroud** [comment] 2019-06-03 12:44
I notice a problem with these multiple requests for one objet : the second question comes far after the first answer... so I'm no more near the object and I don't want to come back to complete.
Why the questions don't come continusely when i'm on the right place ?
(precision, I'm working Off line).
