### ISSUE TITLE
Copy speed limit value from roads nearby

### ISSUE THREAD

**Issue by ujos** [westnordost/StreetComplete#964] opened 2018-03-10 18:38 UTC
Could you please add option to copy speed limit from roads nearby? Similar to street names combobox. 

In Poland speed limit is complicated expression and it is not convenient to type it manually from mobile phone.

**Comment by rugk** [comment] 2018-03-10 21:17
Complex expression? E.g.?
I don't even know how one can enter such an expression in sc. Can't you only enter numbers there?

**Comment by ujos** [comment] 2018-03-10 23:34
According to information on [Wiki ](https://wiki.openstreetmap.org/wiki/Key:maxspeed#Values) valid values for the `maxspeed` tag are:

* numeric
* `signals`
* `none`
* country_code:zone

There is also `maxspeed:conditional` tag. That is what I initially meant. In Poland, for example it can contain `60 @ (23:00-05:00)`.

**Comment by ENT8R** [comment] 2018-03-11 07:50
Sound like a duplicate of #353 to me...

As for the `country_code:zone`: you should already be able to do this with the checkbox right to the normal input...

**Comment by ENT8R** [comment] 2018-03-11 07:53
As for the `maxspeed:conditional`: this is a duplicate of #449

**Comment by matkoniecz** [comment] 2018-03-11 09:38
> for example it can contain 60 @ (23:00-05:00).

Implicit speed limit (there is no maxspeed sign and default limits apply) may be tagged by selecting "other answers" and "there is no sign option".

**Comment by westnordost** [comment] 2018-03-14 22:40
Won't implement. See @matkoniecz and @ENT8R. Also, it would be quite complex to do and the gain would be minimal (user doesn't need to type two characters on his keyboard) while it might even have a negative effect (user just clicks "apply apply apply" without actually checking).

**Closed by westnordost** 2018-03-14 22:40 UTC
