### ISSUE TITLE
Prefill comment-field when tast is unsolvable

### ISSUE THREAD

**Issue by petebp** [westnordost/StreetComplete#211] opened 2017-05-10 11:41 UTC
If you cannot solve a task (e.g. task is asking for opening hours, but there a a bunch of facilities with different opening hours) the app should prefill the comment-field with the name of the task (e.g. "opening hours:"). It would be produce more helpful comments, because in-app it looks like you add a comment to the task, not to the general OSM object.

**Comment by westnordost** [comment] 2017-05-10 11:57
Duplicate of #54. Soon to be implemented.

**Closed by westnordost** 2017-05-10 11:57 UTC
