### ISSUE TITLE
Describe quests in config file instead of a java class

### ISSUE THREAD

**Issue by gustavecha** [westnordost/StreetComplete#186] opened 2017-05-06 14:17 UTC
Hi all,

I've recently discovered this project and was looking forward to add new quest.

Files like this more look like a config file than an actual class.
https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/building_levels/AddBuildingLevels.java

Would it sound acceptable to move existing quests to a yaml or json file from all classes?
It will enable more people to develop their own quests than now.

All the best

**Comment by westnordost** [comment] 2017-05-06 15:01
Duplicate of #98

**Closed by westnordost** 2017-05-06 15:01 UTC
Labels: duplicate
